<?
$arrNumPup = array(
	1 => 'Первый',
	2 => 'Второй',
	3 => 'Третий',
	4 => 'Четвертый',
	5 => 'Пятый',
	6 => 'Шестой',
	7 => 'Седьмой',
	8 => 'Восьмой',
);

$arrPedigreeRod = array(
	1 => 'Отец',
	2 => 'Мать',
	3 => 'Дед по отцу',
	4 => 'Бабушка по отцу',
	5 => 'Дед по матери',
	6 => 'Бабушка по матери',
	7 => 'Прадед по отцу',
	8 => 'Прабабушка по отцу',
	9 => 'Прадед по отцу',
	10 => 'Прабабушка по отцу',
	11 => 'Прадед по матери',
	12 => 'Прабабушка по матери',
	13 => 'Прадед по матери',
	14 => 'Прабабушка по матери',
);


$arrFieldRequired = array(
	'BREEDER' => 'Необходимо указать заводчика',
	'CITY' => 'Необходимо указать город',
	'ADDRESS' => 'Необходимо указать адрес',
);


$arrField = array(
	'INFO' => 'PREVIEW_TEXT',
	'BREED' => 'IBLOCK_SECTION_ID',
	'MAIN_PHOTO' => 'DETAIL_PICTURE',
	'PARENT_MTH_NAME' => 'NAME',
	'PARENT_FTH_NAME' => 'NAME',
);
$arrFieldProp = array(
	'MODERATION' => 'MODERATION',
	'BREEDER' => 'BREEDER',
	'FARM' => 'FARM',
	'CITY' => 'CITY',
	'ADDRESS' => 'ADDRESS',
	'CONTACTS' => 'CONTACTS',
	'BIRTHDATE' => 'BIRTHDATE',

	'PUP_SEX_1' => 'PUP_SEX_1',
	'PUP_NAME_1' => 'PUP_NAME_1',
	'PUP_DESC_1' => 'PUP_DESC_1',
	'PUP_WEIGHT_HEIGHT_1' => 'PUP_WEIGHT_HEIGHT_1',
	'PUP_HEIGHT_1' => 'PUP_HEIGHT_1',
	'PUP_COLOR_1' => 'PUP_COLOR_1',
	'PUP_PRICE_1' => 'PUP_PRICE_1',
	'PUP_CURRENCY_1' => 'PUP_CURRENCY_1',
	'PUP_IMAGES_1' => 'PUP_IMAGES_1',
	'PUP_SALE_1' => 'PUP_SALE_1',

	'PUP_SEX_2' => 'PUP_SEX_2',
	'PUP_NAME_2' => 'PUP_NAME_2',
	'PUP_DESC_2' => 'PUP_DESC_2',
	'PUP_WEIGHT_HEIGHT_2' => 'PUP_WEIGHT_HEIGHT_2',
	'PUP_HEIGHT_2' => 'PUP_HEIGHT_2',
	'PUP_COLOR_2' => 'PUP_COLOR_2',
	'PUP_PRICE_2' => 'PUP_PRICE_2',
	'PUP_CURRENCY_2' => 'PUP_CURRENCY_2',
	'PUP_IMAGES_2' => 'PUP_IMAGES_2',
	'PUP_SALE_2' => 'PUP_SALE_2',

	'PUP_SEX_3' => 'PUP_SEX_3',
	'PUP_NAME_3' => 'PUP_NAME_3',
	'PUP_DESC_3' => 'PUP_DESC_3',
	'PUP_WEIGHT_HEIGHT_3' => 'PUP_WEIGHT_HEIGHT_3',
	'PUP_HEIGHT_3' => 'PUP_HEIGHT_3',
	'PUP_COLOR_3' => 'PUP_COLOR_3',
	'PUP_PRICE_3' => 'PUP_PRICE_3',
	'PUP_CURRENCY_3' => 'PUP_CURRENCY_3',
	'PUP_IMAGES_3' => 'PUP_IMAGES_3',
	'PUP_SALE_3' => 'PUP_SALE_3',

	'PUP_SEX_4' => 'PUP_SEX_4',
	'PUP_NAME_4' => 'PUP_NAME_4',
	'PUP_DESC_4' => 'PUP_DESC_4',
	'PUP_WEIGHT_HEIGHT_4' => 'PUP_WEIGHT_HEIGHT_4',
	'PUP_HEIGHT_4' => 'PUP_HEIGHT_4',
	'PUP_COLOR_4' => 'PUP_COLOR_4',
	'PUP_PRICE_4' => 'PUP_PRICE_4',
	'PUP_CURRENCY_4' => 'PUP_CURRENCY_4',
	'PUP_IMAGES_4' => 'PUP_IMAGES_4',
	'PUP_SALE_4' => 'PUP_SALE_4',

	'PUP_SEX_5' => 'PUP_SEX_5',
	'PUP_NAME_5' => 'PUP_NAME_5',
	'PUP_DESC_5' => 'PUP_DESC_5',
	'PUP_WEIGHT_HEIGHT_5' => 'PUP_WEIGHT_HEIGHT_5',
	'PUP_HEIGHT_5' => 'PUP_HEIGHT_5',
	'PUP_COLOR_5' => 'PUP_COLOR_5',
	'PUP_PRICE_5' => 'PUP_PRICE_5',
	'PUP_CURRENCY_5' => 'PUP_CURRENCY_5',
	'PUP_IMAGES_5' => 'PUP_IMAGES_5',
	'PUP_SALE_5' => 'PUP_SALE_5',

	'PUP_SEX_6' => 'PUP_SEX_6',
	'PUP_NAME_6' => 'PUP_NAME_6',
	'PUP_DESC_6' => 'PUP_DESC_6',
	'PUP_WEIGHT_HEIGHT_6' => 'PUP_WEIGHT_HEIGHT_6',
	'PUP_HEIGHT_6' => 'PUP_HEIGHT_6',
	'PUP_COLOR_6' => 'PUP_COLOR_6',
	'PUP_PRICE_6' => 'PUP_PRICE_6',
	'PUP_CURRENCY_6' => 'PUP_CURRENCY_6',
	'PUP_IMAGES_6' => 'PUP_IMAGES_6',
	'PUP_SALE_6' => 'PUP_SALE_6',

	'PUP_SEX_7' => 'PUP_SEX_7',
	'PUP_NAME_7' => 'PUP_NAME_7',
	'PUP_DESC_7' => 'PUP_DESC_7',
	'PUP_WEIGHT_HEIGHT_7' => 'PUP_WEIGHT_HEIGHT_7',
	'PUP_HEIGHT_7' => 'PUP_HEIGHT_7',
	'PUP_COLOR_7' => 'PUP_COLOR_7',
	'PUP_PRICE_7' => 'PUP_PRICE_7',
	'PUP_CURRENCY_7' => 'PUP_CURRENCY_7',
	'PUP_IMAGES_7' => 'PUP_IMAGES_7',
	'PUP_SALE_7' => 'PUP_SALE_7',

	'PUP_SEX_8' => 'PUP_SEX_8',
	'PUP_NAME_8' => 'PUP_NAME_8',
	'PUP_DESC_8' => 'PUP_DESC_8',
	'PUP_WEIGHT_HEIGHT_8' => 'PUP_WEIGHT_HEIGHT_8',
	'PUP_HEIGHT_8' => 'PUP_HEIGHT_8',
	'PUP_COLOR_8' => 'PUP_COLOR_8',
	'PUP_PRICE_8' => 'PUP_PRICE_8',
	'PUP_CURRENCY_8' => 'PUP_CURRENCY_8',
	'PUP_IMAGES_8' => 'PUP_IMAGES_8',
	'PUP_SALE_8' => 'PUP_SALE_8',
	
	'PARENT_MTH_ID' => 'MTH_ID',
	'PARENT_FTH_ID' => 'FTH_ID',
	
	
	'PARENT_MTH_OWNER' => 'OWNER',
	'PARENT_MTH_LOCATIONS_DOGS' => 'LOCATIONS_DOGS',
	'PARENT_MTH_ADDRESS' => 'ADDRESS',
	'PARENT_MTH_BIRTHDATE' => 'BIRTHDATE',
	'PARENT_MTH_WEIGHT' => 'WEIGHT',
	'PARENT_MTH_HEIGHT' => 'HEIGHT',
	'PARENT_MTH_COLOR' => 'COLOR',
	'PARENT_MTH_TITLE' => 'TITLE',
	'PARENT_MTH_PHOTOS' => 'PHOTOS',
	
	'PARENT_MTH_PEDIGREE_1_TITLES' => 'PEDIGREE_1_TITLES',
	'PARENT_MTH_PEDIGREE_1_NAME' => 'PEDIGREE_1_NAME',
	'PARENT_MTH_PEDIGREE_1_COLOR' => 'PEDIGREE_1_COLOR',
	'PARENT_MTH_PEDIGREE_1_PHOTO' => 'PEDIGREE_1_PHOTO',
	
	'PARENT_MTH_PEDIGREE_2_TITLES' => 'PEDIGREE_2_TITLES',
	'PARENT_MTH_PEDIGREE_2_NAME' => 'PEDIGREE_2_NAME',
	'PARENT_MTH_PEDIGREE_2_COLOR' => 'PEDIGREE_2_COLOR',
	'PARENT_MTH_PEDIGREE_2_PHOTO' => 'PEDIGREE_2_PHOTO',
	
	'PARENT_MTH_PEDIGREE_3_TITLES' => 'PEDIGREE_3_TITLES',
	'PARENT_MTH_PEDIGREE_3_NAME' => 'PEDIGREE_3_NAME',
	'PARENT_MTH_PEDIGREE_3_COLOR' => 'PEDIGREE_3_COLOR',
	'PARENT_MTH_PEDIGREE_3_PHOTO' => 'PEDIGREE_3_PHOTO',
	
	'PARENT_MTH_PEDIGREE_4_TITLES' => 'PEDIGREE_4_TITLES',
	'PARENT_MTH_PEDIGREE_4_NAME' => 'PEDIGREE_4_NAME',
	'PARENT_MTH_PEDIGREE_4_COLOR' => 'PEDIGREE_4_COLOR',
	'PARENT_MTH_PEDIGREE_4_PHOTO' => 'PEDIGREE_4_PHOTO',
	
	'PARENT_MTH_PEDIGREE_5_TITLES' => 'PEDIGREE_5_TITLES',
	'PARENT_MTH_PEDIGREE_5_NAME' => 'PEDIGREE_5_NAME',
	'PARENT_MTH_PEDIGREE_5_COLOR' => 'PEDIGREE_5_COLOR',
	'PARENT_MTH_PEDIGREE_5_PHOTO' => 'PEDIGREE_5_PHOTO',
	
	'PARENT_MTH_PEDIGREE_6_TITLES' => 'PEDIGREE_6_TITLES',
	'PARENT_MTH_PEDIGREE_6_NAME' => 'PEDIGREE_6_NAME',
	'PARENT_MTH_PEDIGREE_6_COLOR' => 'PEDIGREE_6_COLOR',
	'PARENT_MTH_PEDIGREE_6_PHOTO' => 'PEDIGREE_6_PHOTO',
	
	'PARENT_MTH_PEDIGREE_7_TITLES' => 'PEDIGREE_7_TITLES',
	'PARENT_MTH_PEDIGREE_7_NAME' => 'PEDIGREE_7_NAME',
	'PARENT_MTH_PEDIGREE_7_COLOR' => 'PEDIGREE_7_COLOR',
	'PARENT_MTH_PEDIGREE_7_PHOTO' => 'PEDIGREE_7_PHOTO',
	
	'PARENT_MTH_PEDIGREE_8_TITLES' => 'PEDIGREE_8_TITLES',
	'PARENT_MTH_PEDIGREE_8_NAME' => 'PEDIGREE_8_NAME',
	'PARENT_MTH_PEDIGREE_8_COLOR' => 'PEDIGREE_8_COLOR',
	'PARENT_MTH_PEDIGREE_8_PHOTO' => 'PEDIGREE_8_PHOTO',
	
	'PARENT_MTH_PEDIGREE_9_TITLES' => 'PEDIGREE_9_TITLES',
	'PARENT_MTH_PEDIGREE_9_NAME' => 'PEDIGREE_9_NAME',
	'PARENT_MTH_PEDIGREE_9_COLOR' => 'PEDIGREE_9_COLOR',
	'PARENT_MTH_PEDIGREE_9_PHOTO' => 'PEDIGREE_9_PHOTO',
	
	'PARENT_MTH_PEDIGREE_10_TITLES' => 'PEDIGREE_10_TITLES',
	'PARENT_MTH_PEDIGREE_10_NAME' => 'PEDIGREE_10_NAME',
	'PARENT_MTH_PEDIGREE_10_COLOR' => 'PEDIGREE_10_COLOR',
	'PARENT_MTH_PEDIGREE_10_PHOTO' => 'PEDIGREE_10_PHOTO',
	
	'PARENT_MTH_PEDIGREE_11_TITLES' => 'PEDIGREE_11_TITLES',
	'PARENT_MTH_PEDIGREE_11_NAME' => 'PEDIGREE_11_NAME',
	'PARENT_MTH_PEDIGREE_11_COLOR' => 'PEDIGREE_11_COLOR',
	'PARENT_MTH_PEDIGREE_11_PHOTO' => 'PEDIGREE_11_PHOTO',
	
	'PARENT_MTH_PEDIGREE_12_TITLES' => 'PEDIGREE_12_TITLES',
	'PARENT_MTH_PEDIGREE_12_NAME' => 'PEDIGREE_12_NAME',
	'PARENT_MTH_PEDIGREE_12_COLOR' => 'PEDIGREE_12_COLOR',
	'PARENT_MTH_PEDIGREE_12_PHOTO' => 'PEDIGREE_12_PHOTO',
	
	'PARENT_MTH_PEDIGREE_13_TITLES' => 'PEDIGREE_13_TITLES',
	'PARENT_MTH_PEDIGREE_13_NAME' => 'PEDIGREE_13_NAME',
	'PARENT_MTH_PEDIGREE_13_COLOR' => 'PEDIGREE_13_COLOR',
	'PARENT_MTH_PEDIGREE_13_PHOTO' => 'PEDIGREE_13_PHOTO',
	
	'PARENT_MTH_PEDIGREE_14_TITLES' => 'PEDIGREE_14_TITLES',
	'PARENT_MTH_PEDIGREE_14_NAME' => 'PEDIGREE_14_NAME',
	'PARENT_MTH_PEDIGREE_14_COLOR' => 'PEDIGREE_14_COLOR',
	'PARENT_MTH_PEDIGREE_14_PHOTO' => 'PEDIGREE_14_PHOTO',
	
	'PARENT_MTH_PEDIGREE_FILE' => 'PEDIGREE_FILE',
	'PARENT_MTH_PEDIGREE_LINK' => 'PEDIGREE_LINK',




	
	'PARENT_FTH_OWNER' => 'OWNER',
	'PARENT_FTH_LOCATIONS_DOGS' => 'LOCATIONS_DOGS',
	'PARENT_FTH_ADDRESS' => 'ADDRESS',
	'PARENT_FTH_BIRTHDATE' => 'BIRTHDATE',
	'PARENT_FTH_WEIGHT' => 'WEIGHT',
	'PARENT_FTH_HEIGHT' => 'HEIGHT',
	'PARENT_FTH_COLOR' => 'COLOR',
	'PARENT_FTH_TITLE' => 'TITLE',
	'PARENT_FTH_PHOTOS' => 'PHOTOS',
	
	'PARENT_FTH_PEDIGREE_1_TITLES' => 'PEDIGREE_1_TITLES',
	'PARENT_FTH_PEDIGREE_1_NAME' => 'PEDIGREE_1_NAME',
	'PARENT_FTH_PEDIGREE_1_COLOR' => 'PEDIGREE_1_COLOR',
	'PARENT_FTH_PEDIGREE_1_PHOTO' => 'PEDIGREE_1_PHOTO',
	
	'PARENT_FTH_PEDIGREE_2_TITLES' => 'PEDIGREE_2_TITLES',
	'PARENT_FTH_PEDIGREE_2_NAME' => 'PEDIGREE_2_NAME',
	'PARENT_FTH_PEDIGREE_2_COLOR' => 'PEDIGREE_2_COLOR',
	'PARENT_FTH_PEDIGREE_2_PHOTO' => 'PEDIGREE_2_PHOTO',
	
	'PARENT_FTH_PEDIGREE_3_TITLES' => 'PEDIGREE_3_TITLES',
	'PARENT_FTH_PEDIGREE_3_NAME' => 'PEDIGREE_3_NAME',
	'PARENT_FTH_PEDIGREE_3_COLOR' => 'PEDIGREE_3_COLOR',
	'PARENT_FTH_PEDIGREE_3_PHOTO' => 'PEDIGREE_3_PHOTO',
	
	'PARENT_FTH_PEDIGREE_4_TITLES' => 'PEDIGREE_4_TITLES',
	'PARENT_FTH_PEDIGREE_4_NAME' => 'PEDIGREE_4_NAME',
	'PARENT_FTH_PEDIGREE_4_COLOR' => 'PEDIGREE_4_COLOR',
	'PARENT_FTH_PEDIGREE_4_PHOTO' => 'PEDIGREE_4_PHOTO',
	
	'PARENT_FTH_PEDIGREE_5_TITLES' => 'PEDIGREE_5_TITLES',
	'PARENT_FTH_PEDIGREE_5_NAME' => 'PEDIGREE_5_NAME',
	'PARENT_FTH_PEDIGREE_5_COLOR' => 'PEDIGREE_5_COLOR',
	'PARENT_FTH_PEDIGREE_5_PHOTO' => 'PEDIGREE_5_PHOTO',
	
	'PARENT_FTH_PEDIGREE_6_TITLES' => 'PEDIGREE_6_TITLES',
	'PARENT_FTH_PEDIGREE_6_NAME' => 'PEDIGREE_6_NAME',
	'PARENT_FTH_PEDIGREE_6_COLOR' => 'PEDIGREE_6_COLOR',
	'PARENT_FTH_PEDIGREE_6_PHOTO' => 'PEDIGREE_6_PHOTO',
	
	'PARENT_FTH_PEDIGREE_7_TITLES' => 'PEDIGREE_7_TITLES',
	'PARENT_FTH_PEDIGREE_7_NAME' => 'PEDIGREE_7_NAME',
	'PARENT_FTH_PEDIGREE_7_COLOR' => 'PEDIGREE_7_COLOR',
	'PARENT_FTH_PEDIGREE_7_PHOTO' => 'PEDIGREE_7_PHOTO',
	
	'PARENT_FTH_PEDIGREE_8_TITLES' => 'PEDIGREE_8_TITLES',
	'PARENT_FTH_PEDIGREE_8_NAME' => 'PEDIGREE_8_NAME',
	'PARENT_FTH_PEDIGREE_8_COLOR' => 'PEDIGREE_8_COLOR',
	'PARENT_FTH_PEDIGREE_8_PHOTO' => 'PEDIGREE_8_PHOTO',
	
	'PARENT_FTH_PEDIGREE_9_TITLES' => 'PEDIGREE_9_TITLES',
	'PARENT_FTH_PEDIGREE_9_NAME' => 'PEDIGREE_9_NAME',
	'PARENT_FTH_PEDIGREE_9_COLOR' => 'PEDIGREE_9_COLOR',
	'PARENT_FTH_PEDIGREE_9_PHOTO' => 'PEDIGREE_9_PHOTO',
	
	'PARENT_FTH_PEDIGREE_10_TITLES' => 'PEDIGREE_10_TITLES',
	'PARENT_FTH_PEDIGREE_10_NAME' => 'PEDIGREE_10_NAME',
	'PARENT_FTH_PEDIGREE_10_COLOR' => 'PEDIGREE_10_COLOR',
	'PARENT_FTH_PEDIGREE_10_PHOTO' => 'PEDIGREE_10_PHOTO',
	
	'PARENT_FTH_PEDIGREE_11_TITLES' => 'PEDIGREE_11_TITLES',
	'PARENT_FTH_PEDIGREE_11_NAME' => 'PEDIGREE_11_NAME',
	'PARENT_FTH_PEDIGREE_11_COLOR' => 'PEDIGREE_11_COLOR',
	'PARENT_FTH_PEDIGREE_11_PHOTO' => 'PEDIGREE_11_PHOTO',
	
	'PARENT_FTH_PEDIGREE_12_TITLES' => 'PEDIGREE_12_TITLES',
	'PARENT_FTH_PEDIGREE_12_NAME' => 'PEDIGREE_12_NAME',
	'PARENT_FTH_PEDIGREE_12_COLOR' => 'PEDIGREE_12_COLOR',
	'PARENT_FTH_PEDIGREE_12_PHOTO' => 'PEDIGREE_12_PHOTO',
	
	'PARENT_FTH_PEDIGREE_13_TITLES' => 'PEDIGREE_13_TITLES',
	'PARENT_FTH_PEDIGREE_13_NAME' => 'PEDIGREE_13_NAME',
	'PARENT_FTH_PEDIGREE_13_COLOR' => 'PEDIGREE_13_COLOR',
	'PARENT_FTH_PEDIGREE_13_PHOTO' => 'PEDIGREE_13_PHOTO',
	
	'PARENT_FTH_PEDIGREE_14_TITLES' => 'PEDIGREE_14_TITLES',
	'PARENT_FTH_PEDIGREE_14_NAME' => 'PEDIGREE_14_NAME',
	'PARENT_FTH_PEDIGREE_14_COLOR' => 'PEDIGREE_14_COLOR',
	'PARENT_FTH_PEDIGREE_14_PHOTO' => 'PEDIGREE_14_PHOTO',
	
	'PARENT_FTH_PEDIGREE_FILE' => 'PEDIGREE_FILE',
	'PARENT_FTH_PEDIGREE_LINK' => 'PEDIGREE_LINK',
	
	
);