CREATE TABLE b_sota_parser
(
	ID		int(11)		NOT NULL auto_increment,
	NAME		VARCHAR(255)	NULL,
    TYPE		VARCHAR(10) DEFAULT 'rss' NOT NULL,
	TIMESTAMP_X timestamp not null,
	RSS		VARCHAR(600)	NULL,
	SORT		int(11)		DEFAULT 100 NOT NULL,
	ACTIVE		CHAR(1)		DEFAULT 'Y' NOT NULL,
	IBLOCK_ID	INT(18) NOT NULL,
	SECTION_ID	INT(18) NOT NULL,
	SELECTOR	VARCHAR(300)	NULL,
	FIRST_URL	VARCHAR(300)	NULL,
	ENCODING	VARCHAR(20)	NULL,
	PREVIEW_TEXT_TYPE VARCHAR(4) NULL,
	DETAIL_TEXT_TYPE VARCHAR(4) NULL,
	BOOL_PREVIEW_DELETE_TAG CHAR(1) NULL,
	BOOL_DETAIL_DELETE_TAG CHAR(1) NULL,
	PREVIEW_DELETE_TAG VARCHAR(300) NULL,
	DETAIL_DELETE_TAG VARCHAR(300) NULL,
	PREVIEW_FIRST_IMG CHAR(1) NULL,
	DETAIL_FIRST_IMG CHAR(1) NULL,
	PREVIEW_SAVE_IMG CHAR(1) NULL,
	DETAIL_SAVE_IMG CHAR(1) NULL,
	PREVIEW_DELETE_ELEMENT VARCHAR(300) NULL,
	DETAIL_DELETE_ELEMENT VARCHAR(300) NULL,
	PREVIEW_DELETE_ATTRIBUTE VARCHAR(300) NULL,
	DETAIL_DELETE_ATTRIBUTE VARCHAR(300) NULL,
	INDEX_ELEMENT CHAR(1) NULL,
	CODE_ELEMENT CHAR(1) NULL,
	RESIZE_IMAGE CHAR(1) NULL,
	DATE_ACTIVE VARCHAR(10) DEFAULT 'N' NOT NULL,
	DATE_PUBLIC VARCHAR(50) DEFAULT 'N' NOT NULL,
	FIRST_TITLE VARCHAR(50) DEFAULT 'N' NOT NULL,
	META_TITLE VARCHAR(50) DEFAULT 'N' NOT NULL,
	META_DESCRIPTION VARCHAR(50) DEFAULT 'N' NOT NULL,
	META_KEYWORDS VARCHAR(50) DEFAULT 'N' NOT NULL,
	START_AGENT CHAR(1) NULL,
	TIME_AGENT INT(11) NULL,
	ACTIVE_ELEMENT CHAR(1) NULL,
	START_LAST_TIME_X DATETIME NULL,
    SETTINGS LONGTEXT NULL,
	TMP VARCHAR(50) DEFAULT 'b_sota_parser_tmp' NOT NULL,
    CATEGORY_ID int(11) DEFAULT 0 NOT NULL,
	PRIMARY KEY (ID)
);
CREATE TABLE b_sota_parser_tmp
(
	ID		int(11)		NOT NULL auto_increment,
	PARSER_ID		int(11)	NULL,
    PRODUCT_ID		int(11) NULL,
	PRIMARY KEY (ID)

	
);
CREATE TABLE b_sota_parser_tmp_old
(
	ID		int(11)		NOT NULL auto_increment,
	PARSER_ID		int(11)	NULL,
    PRODUCT_ID		int(11) NULL,
	PRIMARY KEY (ID)
);
CREATE TABLE b_sota_parser_section
(
    ID        int(11)        NOT NULL auto_increment,
    TIMESTAMP_X timestamp not null,
    DATE_CREATE DATETIME NULL,
    ACTIVE        CHAR(1)        DEFAULT 'Y' NOT NULL,
    SORT        int(11)        DEFAULT 500 NOT NULL,
    NAME        VARCHAR(255)    NULL,
    DESCRIPTION TEXT NULL,
    PARENT_CATEGORY_ID    INT(11) DEFAULT 0 NOT NULL,
    PRIMARY KEY (ID)
);