<?
    include_once(dirname(__FILE__).'/CStartShopEvents.php');
	include_once(dirname(__FILE__).'/CStartShopVariables.php');
	include_once(dirname(__FILE__).'/CStartShopCache.php');
	include_once(dirname(__FILE__).'/CStartShop.php');
	include_once(dirname(__FILE__).'/shop/CStartShopPrice.php');
	include_once(dirname(__FILE__).'/shop/CStartShopCurrency.php');
	include_once(dirname(__FILE__).'/shop/CStartShopCatalog.php');
	include_once(dirname(__FILE__).'/shop/CStartShopCatalogProduct.php');
	include_once(dirname(__FILE__).'/shop/CStartShopBasket.php');
	include_once(dirname(__FILE__).'/shop/CStartShopDelivery.php');
	include_once(dirname(__FILE__).'/shop/CStartShopOrder.php');
    include_once(dirname(__FILE__).'/shop/CStartShopOrderProperty.php');
    include_once(dirname(__FILE__).'/shop/CStartShopOrderStatus.php');
	include_once(dirname(__FILE__).'/shop/CStartShopPayment.php');
	include_once(dirname(__FILE__).'/general/CStartShopClass.php');
	include_once(dirname(__FILE__).'/db/CStartShopDBQuery.php');
	include_once(dirname(__FILE__).'/db/CStartShopDBQueryBX.php');
	include_once(dirname(__FILE__).'/db/CStartShopDBTableModule.php');
	include_once(dirname(__FILE__).'/forms/CStartShopForm.php');
	include_once(dirname(__FILE__).'/forms/CStartShopFormProperty.php');
	include_once(dirname(__FILE__).'/forms/CStartShopFormResult.php');
	include_once(dirname(__FILE__).'/themes/CStartShopTheme.php');
	include_once(dirname(__FILE__).'/CStartShopUtil.php');
    include_once(dirname(__FILE__).'/CStartShopToolsIBlock.php');
    include_once(dirname(__FILE__).'/CStartShopToolsAdmin.php');
    include_once(dirname(__FILE__).'/CStartShopToolsForms.php');
	include_once(dirname(__FILE__).'/utils/CStartShopUtilsDataFile.php');
	include_once(dirname(__FILE__).'/utils/CStartShopUtilsRights.php');
	include_once(dirname(__FILE__).'/exchange/1C/CStartShopExchange1C.php');
	include_once(dirname(__FILE__).'/xml/CStartShopXmlDocument.php');
	include_once(dirname(__FILE__).'/xml/CStartShopXmlNode.php');
	
?>