CREATE TABLE IF NOT EXISTS `api_mail_settings` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(255) NULL DEFAULT NULL,
  `VALUE` LONGTEXT NULL DEFAULT NULL,
  `SITE_ID` CHAR(2) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `NAME` (`NAME`),
  INDEX `SITE_ID` (`SITE_ID`)
);
