<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Партнеры");
?><?$APPLICATION->IncludeComponent(
	"bitrix:news",
	"flyaway",
	Array(
		"ADD_ELEMENT_CHAIN" => "Y",
		"ADD_SECTIONS_CHAIN" => "N",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"BROWSER_TITLE" => "-",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "A",
		"CHECK_DATES" => "Y",
		"COMPONENT_TEMPLATE" => "flyaway",
		"DETAIL_ACTIVE_DATE_FORMAT" => "d.m.Y",
		"DETAIL_DISPLAY_BOTTOM_PAGER" => "Y",
		"DETAIL_DISPLAY_TOP_PAGER" => "N",
		"DETAIL_FIELD_CODE" => array(0=>"",1=>"",),
		"DETAIL_PAGER_SHOW_ALL" => "Y",
		"DETAIL_PAGER_TEMPLATE" => "",
		"DETAIL_PAGER_TITLE" => "Страница",
		"DETAIL_PROPERTY_CODE" => array(0=>"",1=>"",),
		"DETAIL_SET_CANONICAL_URL" => "N",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"DISPLAY_NAME" => "Y",
		"DISPLAY_TOP_PAGER" => "N",
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"IBLOCK_ID" => "#IBLOCK_ID_services_partners#",
		"IBLOCK_TYPE" => "services",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"LIST_ACTIVE_DATE_FORMAT" => "d.m.Y",
		"LIST_FIELD_CODE" => array(0=>"ID",1=>"CODE",2=>"XML_ID",3=>"NAME",4=>"TAGS",5=>"SORT",6=>"PREVIEW_TEXT",7=>"PREVIEW_PICTURE",8=>"DETAIL_TEXT",9=>"DETAIL_PICTURE",10=>"DATE_ACTIVE_FROM",11=>"ACTIVE_FROM",12=>"DATE_ACTIVE_TO",13=>"ACTIVE_TO",14=>"SHOW_COUNTER",15=>"SHOW_COUNTER_START",16=>"IBLOCK_TYPE_ID",17=>"IBLOCK_ID",18=>"IBLOCK_CODE",19=>"IBLOCK_NAME",20=>"IBLOCK_EXTERNAL_ID",21=>"DATE_CREATE",22=>"CREATED_BY",23=>"CREATED_USER_NAME",24=>"TIMESTAMP_X",25=>"MODIFIED_BY",26=>"USER_NAME",27=>"",),
		"LIST_PROPERTY_CODE" => array(0=>"",1=>"",),
		"MESSAGE_404" => "",
		"META_DESCRIPTION" => "-",
		"META_KEYWORDS" => "-",
		"NEWS_COUNT" => "12",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => "flyaway",
		"PAGER_TITLE" => "Новости",
		"PREVIEW_TRUNCATE_LEN" => "",
		"RSFLYAWAY_BLOCK_NAME_IS_LINK_DETAIL" => "N",
		"RSFLYAWAY_BLOCK_NAME_IS_LINK_LIST" => "N",
		"RSFLYAWAY_COLS_IN_ROW_LIST" => "4",
		"RSFLYAWAY_DETAIL_SUBSCRIBE_NOTE" => "",
		"RSFLYAWAY_DETAIL_SUBSCRIBE_PAGE" => "",
		"RSFLYAWAY_DETAIL_TEMPLATES" => "news",
		"RSFLYAWAY_DETAIL_USE_SUBSCRIBE" => "N",
		"RSFLYAWAY_LIST_TEMPLATES_DETAIL" => "partners",
		"RSFLYAWAY_LIST_TEMPLATES_DETAIL_USE" => "N",
		"RSFLYAWAY_LIST_TEMPLATES_LIST" => "services",
		"RSFLYAWAY_OWL_CHANGE_DELAY_DETAIL" => "8000",
		"RSFLYAWAY_OWL_CHANGE_SPEED_DETAIL" => "2000",
		"RSFLYAWAY_OWL_PC_DETAIL" => "5",
		"RSFLYAWAY_OWL_PHONE_DETAIL" => "2",
		"RSFLYAWAY_OWL_TABLET_DETAIL" => "3",
		"RSFLYAWAY_SHOW_BLOCK_NAME_DETAIL" => "Y",
		"RSFLYAWAY_SHOW_BLOCK_NAME_LIST" => "N",
		"RSFLYAWAY_USE_OWL_DETAIL" => "Y",
		"RSFLYAWAY_USE_OWL_LIST" => "N",
		"SEF_FOLDER" => "#SITE_DIR#about/partners/",
		"SEF_MODE" => "Y",
		"SEF_URL_TEMPLATES" => array("news"=>"","section"=>"","detail"=>"#ELEMENT_CODE#/",),
		"SET_LAST_MODIFIED" => "N",
		"SET_STATUS_404" => "N",
		"SET_TITLE" => "Y",
		"SHOW_404" => "N",
		"SORT_BY1" => "ACTIVE_FROM",
		"SORT_BY2" => "SORT",
		"SORT_ORDER1" => "DESC",
		"SORT_ORDER2" => "ASC",
		"USE_CATEGORIES" => "N",
		"USE_FILTER" => "N",
		"USE_PERMISSIONS" => "N",
		"USE_RATING" => "N",
		"USE_REVIEW" => "N",
		"USE_RSS" => "N",
		"USE_SEARCH" => "N"
	)
);?>
<br>
<div class="row">
	<div class="col col-md-9">
<?$APPLICATION->IncludeComponent(
	"rsflyaway:forms",
	"flyaway",
	Array(
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"CACHE_TIME" => "3600",
		"CACHE_TYPE" => "A",
		"COMPONENT_TEMPLATE" => "flyaway",
		"EMAIL_TO" => "",
		"EVENT_TYPE" => "RS_FLYAWAY_PARTNER",
		"FORM_DESCRIPTION" => "Наша компания всегда открыта к сотрудничеству. Если вы хотите стать нашим партнером, пожалуйста заполните нижеприведенную форму.",
		"FORM_TITLE" => "Стать партнером",
		"MESSAGE_AGREE" => "Спасибо, ваша заявка принята!",
		"REQUIRED_FIELDS" => array(0=>"RS_NAME",1=>"RS_PHONE",2=>"RS_ORGANISATION_NAME",),
		"RS_FLYAWAY_EXT_FIELDS_COUNT" => "0",
		"SHOW_FIELDS" => array(0=>"RS_NAME",1=>"RS_PHONE",2=>"RS_ORGANISATION_NAME",3=>"RS_EMAIL",4=>"RS_TEXTAREA",),
		"USE_CAPTCHA" => "Y"
	)
);?>
</div>
</div><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>
