<table>
            <thead>
            <tr>
              <td></td>
              <td>XXS</td>
              <td>XS</td>
              <td>S</td>
              <td>M</td>
              <td>L</td>
              <td>XL</td>
              <td>XXL</td>
            </tr>
            </thead>
            <tbody>
            <tr>
              <th>Бюст</th>
              <td>78</td>
              <td>82</td>
              <td>86</td>
              <td>90</td>
              <td>96</td>
              <td>103</td>
              <td>110</td>
            </tr>
            <tr>
              <th>Талия</th>
              <td>60</td>
              <td>64</td>
              <td>68</td>
              <td>72</td>
              <td>78</td>
              <td>85</td>
              <td>92</td>
            </tr>
            <tr>
              <th>Таз</th>
              <td>86</td>
              <td>90</td>
              <td>94</td>
              <td>98</td>
              <td>104</td>
              <td>111</td>
              <td>118</td>
            </tr>
            </tbody>
</table>