<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Материалы");
?>
<div class="row production">
	<div class="col col-md-10">
	<?$APPLICATION->IncludeComponent(
		"bitrix:news.detail",
		"imagetop",
		array(
			"COMPONENT_TEMPLATE" => "imagetop",
			"IBLOCK_TYPE" => "company",
			"IBLOCK_ID" => "#IBLOCK_ID_company_production#",
			"ELEMENT_ID" => "IBLOCK_ID_company_production_ELEMENT",
			"ELEMENT_CODE" => "",
			"CHECK_DATES" => "Y",
			"FIELD_CODE" => array(
				0 => "",
				1 => "",
			),
			"PROPERTY_CODE" => array(
				0 => "",
				1 => "",
			),
			"IBLOCK_URL" => "",
			"AJAX_MODE" => "N",
			"AJAX_OPTION_JUMP" => "N",
			"AJAX_OPTION_STYLE" => "Y",
			"AJAX_OPTION_HISTORY" => "N",
			"CACHE_TYPE" => "A",
			"CACHE_TIME" => "36000000",
			"CACHE_GROUPS" => "Y",
			"SET_TITLE" => "N",
			"SET_BROWSER_TITLE" => "N",
			"BROWSER_TITLE" => "-",
			"SET_META_KEYWORDS" => "N",
			"META_KEYWORDS" => "-",
			"SET_META_DESCRIPTION" => "N",
			"META_DESCRIPTION" => "-",
			"SET_STATUS_404" => "N",
			"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
			"ADD_SECTIONS_CHAIN" => "N",
			"ADD_ELEMENT_CHAIN" => "N",
			"ACTIVE_DATE_FORMAT" => "d.m.Y",
			"USE_PERMISSIONS" => "N",
			"DISPLAY_DATE" => "Y",
			"DISPLAY_NAME" => "Y",
			"DISPLAY_PICTURE" => "Y",
			"DISPLAY_PREVIEW_TEXT" => "Y",
			"USE_SHARE" => "N",
			"PAGER_TEMPLATE" => "flyaway",
			"DISPLAY_TOP_PAGER" => "N",
			"DISPLAY_BOTTOM_PAGER" => "N",
			"PAGER_TITLE" => "Страница",
			"PAGER_SHOW_ALL" => "N",
			"DETAIL_URL" => "",
			"AJAX_OPTION_ADDITIONAL" => "",
			"SET_CANONICAL_URL" => "N",
			"SET_LAST_MODIFIED" => "N",
			"RSFLYAWAY_PROP_MARKER_TEXT" => "-",
			"RSFLYAWAY_PROP_MARKER_COLOR" => "-",
			"RSFLYAWAY_PROP_ACTION_DATE" => "-",
			"PAGER_BASE_LINK_ENABLE" => "N",
			"SHOW_404" => "N",
			"MESSAGE_404" => ""
		),
		false
	);?>
	<?$APPLICATION->IncludeComponent(
	"bitrix:catalog.section.list",
	"gallery",
	array(
		"COMPONENT_TEMPLATE" => "gallery",
		"IBLOCK_TYPE" => "catalog",
		"IBLOCK_ID" => "#IBLOCK_ID_catalog_catalog#",
		"SECTION_ID" => "",
		"SECTION_CODE" => "",
		"COUNT_ELEMENTS" => "N",
		"TOP_DEPTH" => "1",
		"SECTION_FIELDS" => array(
			0 => "",
			1 => "",
		),
		"SECTION_USER_FIELDS" => array(
			0 => "",
			1 => "",
		),
		"VIEW_MODE" => "LINE",
		"SHOW_PARENT_NAME" => "Y",
		"SECTION_URL" => "",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "36000000",
		"CACHE_GROUPS" => "Y",
		"ADD_SECTIONS_CHAIN" => "Y",
		"RSMONOPOLY_BLOCK_NAME" => "Каталог",
		"RSMONOPOLY_USE_OWL" => "Y",
		"RSMONOPOLY_CHANGE_SPEED" => "2000",
		"RSMONOPOLY_CHANGE_DELAY" => "8000",
		"RSMONOPOLY_COLS_IN_ROW" => "3",
		"RSMONOPOLY_SHOW_BLOCK_NAME" => "Y",
		"RSMONOPOLY_BLOCK_NAME_IS_LINK" => "N",
		"RSMONOPOLY_OWL_CHANGE_SPEED" => "2000",
		"RSMONOPOLY_OWL_CHANGE_DELAY" => "8000",
		"RSMONOPOLY_OWL_PHONE" => "1",
		"RSMONOPOLY_OWL_TABLET" => "2",
		"RSMONOPOLY_OWL_PC" => "3",
		"RSMONOPOLY_BLOCK_LINK" => "",
		"RSFLYAWAY_BLOCK_NAME" => "Каталог товаров",
		"RSFLYAWAY_BLOCK_LINK" => "",
		"RSFLYAWAY_SHOW_BLOCK_NAME" => "Y",
		"RSFLYAWAY_BLOCK_NAME_IS_LINK" => "N",
		"RSFLYAWAY_USE_OWL" => "Y",
		"RSFLYAWAY_COLS_IN_ROW" => "4",
		"RSFLYAWAY_OWL_CHANGE_SPEED" => "2000",
		"RSFLYAWAY_OWL_CHANGE_DELAY" => "8000",
		"RSFLYAWAY_OWL_PHONE" => "1",
		"RSFLYAWAY_OWL_TABLET" => "2",
		"RSFLYAWAY_OWL_PC" => "3"
	),
	false
);?>
	</div>
</div>
<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>