CREATE TABLE IF NOT EXISTS `api_message` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `ACTIVE` CHAR(1) NULL DEFAULT 'Y',
  `ACTIVE_FROM` DATETIME NULL DEFAULT NULL,
  `ACTIVE_TO` DATETIME NULL DEFAULT NULL,
  `SORT` INT(11) NULL DEFAULT '500',
  `NAME` VARCHAR(255) NULL DEFAULT NULL,
  `EXPIRES` INT(11) NULL DEFAULT NULL,
  `TYPE` VARCHAR(255) NOT NULL,
  `COLOR` VARCHAR(255) NOT NULL DEFAULT '',
  `MESSAGE` LONGTEXT NOT NULL,
  `MESSAGE_TYPE` CHAR(4) NOT NULL DEFAULT 'text',
  `CLOSE_TEXT` VARCHAR(255) NULL DEFAULT '',
  `CLOSE_CLASS` VARCHAR(255) NULL DEFAULT '',
  `PAGE_URL` LONGTEXT NULL,
  `SITE_ID` VARCHAR(255) NULL DEFAULT NULL,
  `GROUP_ID` VARCHAR(255) NULL DEFAULT NULL,
  `USER_ID` VARCHAR(255) NULL DEFAULT NULL,
  `BLOCK` CHAR(1) NOT NULL DEFAULT 'N',
  `TIMESTAMP_X` DATETIME NULL DEFAULT NULL,
  `MODIFIED_BY` INT(18) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`)
);
CREATE TABLE IF NOT EXISTS `api_message_config` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(255) NOT NULL,
  `VALUE` TEXT NULL,
  `SITE_ID` CHAR(2) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `NAME` (`NAME`),
  INDEX `SITE_ID` (`SITE_ID`)
);
