<?
if (!defined("B_PROLOG_INCLUDED") || B_PROLOG_INCLUDED !== true)
    die();

if (!defined("WIZARD_TEMPLATE_ID"))
    return;

function InnetAddEvent($EventType, $EventTypeName, $EventDescription, $EventTemplateMessage, $EventTemplateSubjects, $EmailTo = "#DEFAULT_EMAIL_FROM#")
{

    $CEventType = new CEventType;
    $EventTypeIDCallback = $CEventType->Add(array(
            "LID" => "ru",
            "EVENT_NAME" => $EventType,
            "NAME" => $EventTypeName,
            "DESCRIPTION" => $EventDescription
        )
    );

    if ($EventTypeIDCallback > 0) {
        $arSites = array();
        $rsSites = CSite::GetList();
        while ($arSite = $rsSites->Fetch()) {
            $arSites[] = $arSite["LID"];
        }

        $Fields["ACTIVE"] = "Y";
        $Fields["EVENT_NAME"] = $EventType;
        $Fields["LID"] = $arSites;
        $Fields["EMAIL_FROM"] = "#DEFAULT_EMAIL_FROM#";
        $Fields["EMAIL_TO"] = $EmailTo;
        $Fields["BCC"] = "";
        $Fields["SUBJECT"] = $EventTemplateSubjects;
        $Fields["BODY_TYPE"] = "text";
        $Fields["MESSAGE"] = $EventTemplateMessage;

        $CEventMessage = new CEventMessage;
        $EventTemplateID = $CEventMessage->Add($Fields);
    }

}


//services
InnetAddEvent("INNET_SERVICE_ORDER", GetMessage('INNET_SERVICE_ORDER'), GetMessage('INNET_SERVICE_ORDER_DESCRIPTION'), GetMessage('INNET_SERVICE_ORDER_MESSAGE'), GetMessage('INNET_SERVICE_ORDER_SUBJECT'));
InnetAddEvent("INNET_SERVICE_ORDER_USER", GetMessage('INNET_SERVICE_ORDER_USER'), GetMessage('INNET_SERVICE_ORDER_USER_DESCRIPTION'), GetMessage('INNET_SERVICE_ORDER_USER_MESSAGE'), GetMessage('INNET_SERVICE_ORDER_USER_SUBJECT'), "#EMAIL_TO#");

InnetAddEvent("INNET_SERVICE_QUESTIONS", GetMessage('INNET_SERVICE_QUESTIONS'), GetMessage('INNET_SERVICE_QUESTIONS_DESCRIPTION'), GetMessage('INNET_SERVICE_QUESTIONS_MESSAGE'), GetMessage('INNET_SERVICE_QUESTIONS_SUBJECT'));
InnetAddEvent("INNET_SERVICE_QUESTIONS_USER", GetMessage('INNET_SERVICE_QUESTIONS_USER'), GetMessage('INNET_SERVICE_QUESTIONS_USER_DESCRIPTION'), GetMessage('INNET_SERVICE_QUESTIONS_USER_MESSAGE'), GetMessage('INNET_SERVICE_QUESTIONS_USER_SUBJECT'), "#EMAIL_TO#");


//catalog
InnetAddEvent("INNET_CATALOG_ORDER", GetMessage('INNET_CATALOG_ORDER'), GetMessage('INNET_CATALOG_ORDER_DESCRIPTION'), GetMessage('INNET_CATALOG_ORDER_MESSAGE'), GetMessage('INNET_CATALOG_ORDER_SUBJECT'));
InnetAddEvent("INNET_CATALOG_ORDER_USER", GetMessage('INNET_CATALOG_ORDER_USER'), GetMessage('INNET_CATALOG_ORDER_DESCRIPTION'), GetMessage('INNET_CATALOG_ORDER_USER_MESSAGE'), GetMessage('INNET_CATALOG_ORDER_USER_SUBJECT'), "#EMAIL_TO#");

InnetAddEvent("INNET_CATALOG_QUESTIONS", GetMessage('INNET_CATALOG_QUESTIONS'), GetMessage('INNET_CATALOG_QUESTIONS_DESCRIPTION'), GetMessage('INNET_CATALOG_QUESTIONS_MESSAGE'), GetMessage('INNET_CATALOG_QUESTIONS_SUBJECT'));
InnetAddEvent("INNET_CATALOG_QUESTIONS_USER", GetMessage('INNET_CATALOG_QUESTIONS_USER'), GetMessage('INNET_CATALOG_QUESTIONS_USER_DESCRIPTION'), GetMessage('INNET_CATALOG_QUESTIONS_USER_MESSAGE'), GetMessage('INNET_CATALOG_QUESTIONS_USER_SUBJECT'), "#EMAIL_TO#");

InnetAddEvent("INNET_CATALOG_REVIEWS", GetMessage('INNET_CATALOG_REVIEWS'), GetMessage('INNET_CATALOG_REVIEWS_DESCRIPTION'), GetMessage('INNET_CATALOG_REVIEWS_MESSAGE'), GetMessage('INNET_CATALOG_REVIEWS_SUBJECT'));
InnetAddEvent("INNET_CATALOG_REVIEWS_USER", GetMessage('INNET_CATALOG_REVIEWS_USER'), GetMessage('INNET_CATALOG_REVIEWS_USER_DESCRIPTION'), GetMessage('INNET_CATALOG_REVIEWS_USER_MESSAGE'), GetMessage('INNET_CATALOG_REVIEWS_USER_SUBJECT'));


//projects
InnetAddEvent("INNET_PROJECTS_REVIEWS", GetMessage('INNET_PROJECTS_REVIEWS'), GetMessage('INNET_PROJECTS_REVIEWS_DESCRIPTION'), GetMessage('INNET_PROJECTS_REVIEWS_MESSAGE'), GetMessage('INNET_PROJECTS_REVIEWS_SUBJECT'));
InnetAddEvent("INNET_PROJECTS_REVIEWS_USER", GetMessage('INNET_PROJECTS_REVIEWS_USER'), GetMessage('INNET_PROJECTS_REVIEWS_USER_DESCRIPTION'), GetMessage('INNET_PROJECTS_REVIEWS_USER_MESSAGE'), GetMessage('INNET_PROJECTS_REVIEWS_USER_SUBJECT'));

InnetAddEvent("INNET_PROJECTS_ORDER", GetMessage('INNET_PROJECTS_ORDER'), GetMessage('INNET_PROJECTS_ORDER_DESCRIPTION'), GetMessage('INNET_PROJECTS_ORDER_MESSAGE'), GetMessage('INNET_PROJECTS_ORDER_SUBJECT'));
InnetAddEvent("INNET_PROJECTS_ORDER_USER", GetMessage('INNET_PROJECTS_ORDER_USER'), GetMessage('INNET_PROJECTS_ORDER_USER_DESCRIPTION'), GetMessage('INNET_PROJECTS_ORDER_USER_MESSAGE'), GetMessage('INNET_PROJECTS_ORDER_USER_SUBJECT'), "#EMAIL_TO#");


//question answer
InnetAddEvent("INNET_NEW_QUESTION", GetMessage('INNET_NEW_QUESTION'), GetMessage('INNET_NEW_QUESTION_DESCRIPTION'), GetMessage('INNET_NEW_QUESTION_MESSAGE'), GetMessage('INNET_NEW_QUESTION_SUBJECT'));
InnetAddEvent("INNET_NEW_QUESTION_USER", GetMessage('INNET_NEW_QUESTION_USER'), GetMessage('INNET_NEW_QUESTION_USER_DESCRIPTION'), GetMessage('INNET_NEW_QUESTION_USER_MESSAGE'), GetMessage('INNET_NEW_QUESTION_USER_SUBJECT'));
//InnetAddEvent("INNET_NEW_QUESTION_REPLY", GetMessage('INNET_NEW_QUESTION_REPLY'), GetMessage('INNET_NEW_QUESTION_REPLY_DESCRIPTION'), GetMessage('INNET_NEW_QUESTION_REPLY_MESSAGE'), GetMessage('INNET_NEW_QUESTION_REPLY_SUBJECT'), "#NEW_QUESTION_EMAIL_USER#");


//feedback
InnetAddEvent("INNET_FEEDBACK", GetMessage('INNET_FEEDBACK'), GetMessage('INNET_FEEDBACK_DESCRIPTION'), GetMessage('INNET_FEEDBACK_MESSAGE'), GetMessage('INNET_FEEDBACK_SUBJECT'));
InnetAddEvent("INNET_FEEDBACK_USER", GetMessage('INNET_FEEDBACK_USER'), GetMessage('INNET_FEEDBACK_USER_DESCRIPTION'), GetMessage('INNET_FEEDBACK_USER_MESSAGE'), GetMessage('INNET_FEEDBACK_USER_SUBJECT'));


//callback
InnetAddEvent("INNET_CALLBACK", GetMessage('INNET_CALLBACK'), GetMessage('INNET_CALLBACK_DESCRIPTION'), GetMessage('INNET_CALLBACK_MESSAGE'), GetMessage('INNET_CALLBACK_SUBJECT'));
//InnetAddEvent("INNET_CALLBACK_USER", GetMessage('INNET_CALLBACK_USER'), GetMessage('INNET_CALLBACK_USER_DESCRIPTION'), GetMessage('INNET_CALLBACK_USER_MESSAGE'), GetMessage('INNET_CALLBACK_USER_SUBJECT'));
?>