<?
$arTooltips = array(
	"SHOW_HIDDEN" => GetMessage("SHOW_HIDDEN_TIP"),
	"SHOW_RUBS" => GetMessage("SHOW_RUBS_TIP"),
	"SHOW_POST_FORM" => GetMessage("SHOW_POST_FORM"),
	"SHOW_SMS_FORM" => GetMessage("SHOW_SMS_FORM"),
	"TEMPLATE_ID" => GetMessage("TEMPLATE_ID"),
	"ALLOW_ANONYMOUS" => GetMessage("ALLOW_ANONYMOUS_TIP"),
	"SHOW_AUTH_LINKS" => GetMessage("SHOW_AUTH_LINKS_TIP"),
	"CACHE_TYPE" => GetMessage("CACHE_TYPE_TIP"),
	"CACHE_TIME" => GetMessage("CACHE_TIME_TIP"),
	"SET_TITLE" => GetMessage("SET_TITLE_TIP"),
	"AJAX_MODE" => GetMessage("AJAX_MODE_TIP"),
	"AJAX_OPTION_SHADOW" => GetMessage("AJAX_OPTION_SHADOW_TIP"),
	"AJAX_OPTION_JUMP" => GetMessage("AJAX_OPTION_JUMP_TIP"),
	"AJAX_OPTION_STYLE" => GetMessage("AJAX_OPTION_STYLE_TIP"),
	"AJAX_OPTION_HISTORY" => GetMessage("AJAX_OPTION_HISTORY_TIP"),
);
?>