<?if(!defined("B_PROLOG_INCLUDED")||B_PROLOG_INCLUDED!==true)die();$dbSite=CSite::GetByID(WIZARD_SITE_ID);if($arSite=$dbSite->Fetch())
$lid=$arSite["LANGUAGE_ID"];if(strlen($lid)<=0)
$lid="ru";IncludeModuleLangFile($_SERVER["DOCUMENT_ROOT"]."/bitrix/modules/sale/install/events.php",$lid);WizardServices::IncludeServiceLang("mail.php",$lid);$CHARSET=defined("BX_UTF")?"UTF-8":$lid=="ru"?"windows-1251":"ISO-8859-1";$dbEvent=CEventType::GetList(Array("LID"=>$lid));while($ar=$dbEvent->Fetch())
$dbEvent_[$ar["EVENT_NAME"]]=$ar;$et=new CEventType;$event_name="SALE_QUICKLY_ORDER";$description=GetMessage("SALE_QUICKLY_ORDER_DESC");if(array_key_exists($event_name,$dbEvent_))
$et->Update(array("ID"=>$dbEvent_[$event_name]["ID"]),array("DESCRIPTION"=>$description));else
$et->Add(array("LID"=>$lid,"EVENT_NAME"=>$event_name,"NAME"=>GetMessage("SALE_QUICKLY_ORDER_NAME"),"DESCRIPTION"=>$description,));$et=new CEventType;$event_name="SALE_CHEAP_ORDER";$description=GetMessage("SALE_CHEAP_ORDER_DESC");if(array_key_exists($event_name,$dbEvent_))
$et->Update(array("ID"=>$dbEvent_[$event_name]["ID"]),array("DESCRIPTION"=>$description));else
$et->Add(array("LID"=>$lid,"EVENT_NAME"=>$event_name,"NAME"=>GetMessage("SALE_CHEAP_ORDER_NAME"),"DESCRIPTION"=>$description,));$et=new CEventType;$event_name="FEEDBACK_FORM";$description=GetMessage("MF_EVENT_DESCRIPTION");if(array_key_exists($event_name,$dbEvent_))
$et->Update(array("ID"=>$dbEvent_[$event_name]["ID"]),array("DESCRIPTION"=>$description));else
$et->Add(array("LID"=>$lid,"EVENT_NAME"=>$event_name,"NAME"=>GetMessage("MF_EVENT_NAME"),"DESCRIPTION"=>$description,));$et=new CEventType;$event_name="SALE_NEW_ORDER";$description=GetMessage("SALE_NEW_ORDER_DESC");if(array_key_exists($event_name,$dbEvent_))
$et->Update(array("ID"=>$dbEvent_[$event_name]["ID"]),array("DESCRIPTION"=>$description));else
$et->Add(array("LID"=>$lid,"EVENT_NAME"=>$event_name,"NAME"=>GetMessage("SALE_NEW_ORDER_NAME"),"DESCRIPTION"=>$description,));$et=new CEventType;$event_name="SALE_NEW_ORDER_RECURRING";$description=GetMessage("SALE_NEW_ORDER_RECURRING_DESC");if(array_key_exists($event_name,$dbEvent_))
$et->Update(array("ID"=>$dbEvent_[$event_name]["ID"]),array("DESCRIPTION"=>$description));else
$et->Add(array("LID"=>$lid,"EVENT_NAME"=>$event_name,"NAME"=>GetMessage("SALE_NEW_ORDER_RECURRING_NAME"),"DESCRIPTION"=>$description,));$et=new CEventType;$event_name="SALE_ORDER_REMIND_PAYMENT";$description=GetMessage("SALE_ORDER_REMIND_PAYMENT_DESC");if(array_key_exists($event_name,$dbEvent_))
$et->Update(array("ID"=>$dbEvent_[$event_name]["ID"]),array("DESCRIPTION"=>$description));else
$et->Add(array("LID"=>$lid,"EVENT_NAME"=>$event_name,"NAME"=>GetMessage("SALE_ORDER_REMIND_PAYMENT_NAME"),"DESCRIPTION"=>$description,));$et=new CEventType;$event_name="SALE_ORDER_CANCEL";$description=GetMessage("SALE_ORDER_CANCEL_DESC");if(array_key_exists($event_name,$dbEvent_))
$et->Update(array("ID"=>$dbEvent_[$event_name]["ID"]),array("DESCRIPTION"=>$description));else
$et->Add(array("LID"=>$lid,"EVENT_NAME"=>$event_name,"NAME"=>GetMessage("SALE_ORDER_CANCEL_NAME"),"DESCRIPTION"=>$description,));$et=new CEventType;$event_name="SALE_ORDER_PAID";$description=GetMessage("SALE_ORDER_PAID_DESC");if(array_key_exists($event_name,$dbEvent_))
$et->Update(array("ID"=>$dbEvent_[$event_name]["ID"]),array("DESCRIPTION"=>$description));else
$et->Add(array("LID"=>$lid,"EVENT_NAME"=>$event_name,"NAME"=>GetMessage("SALE_ORDER_PAID_NAME"),"DESCRIPTION"=>$description,));$et=new CEventType;$event_name="SALE_ORDER_DELIVERY";$description=GetMessage("SALE_ORDER_DELIVERY_DESC");if(array_key_exists($event_name,$dbEvent_))
$et->Update(array("ID"=>$dbEvent_[$event_name]["ID"]),array("DESCRIPTION"=>$description));else
$et->Add(array("LID"=>$lid,"EVENT_NAME"=>$event_name,"NAME"=>GetMessage("SALE_ORDER_DELIVERY_NAME"),"DESCRIPTION"=>$description,));$et=new CEventType;$event_name="SALE_RECURRING_CANCEL";$description=GetMessage("SALE_RECURRING_CANCEL_DESC");if(array_key_exists($event_name,$dbEvent_))
$et->Update(array("ID"=>$dbEvent_[$event_name]["ID"]),array("DESCRIPTION"=>$description));else
$et->Add(array("LID"=>$lid,"EVENT_NAME"=>$event_name,"NAME"=>GetMessage("SALE_RECURRING_CANCEL_NAME"),"DESCRIPTION"=>$description,));$et=new CEventType;$event_name="SALE_SUBSCRIBE_PRODUCT";$description=GetMessage("UP_TYPE_SUBJECT_DESC");if(array_key_exists($event_name,$dbEvent_))
$et->Update(array("ID"=>$dbEvent_[$event_name]["ID"]),array("DESCRIPTION"=>$description));else
$et->Add(array("LID"=>$lid,"EVENT_NAME"=>$event_name,"NAME"=>GetMessage("UP_TYPE_SUBJECT"),"DESCRIPTION"=>$description,));$dbEvent_=array();$dbEvent=CEventMessage::GetList($b="ID",$order="ASC",Array("SITE_ID"=>WIZARD_SITE_ID));while($ar=$dbEvent->Fetch())
$dbEvent_[$ar["EVENT_NAME"].$ar["SUBJECT"]]=$ar;$emess=new CEventMessage;$event_name="SALE_QUICKLY_ORDER";$subject=GetMessage("SALE_QUICKLY_ORDER_SUBJECT");$message=str_replace("#SITE_CHARSET#",$CHARSET,GetMessage("SALE_QUICKLY_ORDER_MESSAGE"));if(array_key_exists($event_name.$subject,$dbEvent_))
$emess->Update($dbEvent_[$event_name.$subject]["ID"],array("MESSAGE"=>$message,"BODY_TYPE"=>"html"));else
$emess->Add(array("ACTIVE"=>"Y","EVENT_NAME"=>$event_name,"LID"=>WIZARD_SITE_ID,"EMAIL_FROM"=>"#DEFAULT_EMAIL_FROM#","EMAIL_TO"=>"#SALE_EMAIL#","BCC"=>"#BCC#","SUBJECT"=>$subject,"MESSAGE"=>$message,"BODY_TYPE"=>"html",));$emess=new CEventMessage;$event_name="SALE_CHEAP_ORDER";$subject=GetMessage("SALE_CHEAP_ORDER_SUBJECT");$message=str_replace("#SITE_CHARSET#",$CHARSET,GetMessage("SALE_CHEAP_ORDER_MESSAGE"));if(array_key_exists($event_name.$subject,$dbEvent_))
$emess->Update($dbEvent_[$event_name.$subject]["ID"],array("MESSAGE"=>$message,"BODY_TYPE"=>"html"));else
$emess->Add(array("ACTIVE"=>"Y","EVENT_NAME"=>$event_name,"LID"=>WIZARD_SITE_ID,"EMAIL_FROM"=>"#DEFAULT_EMAIL_FROM#","EMAIL_TO"=>"#SALE_EMAIL#","BCC"=>"#BCC#","SUBJECT"=>$subject,"MESSAGE"=>$message,"BODY_TYPE"=>"html",));$emess=new CEventMessage;$event_name="FEEDBACK_FORM";$subject=GetMessage("MF_EVENT_SUBJECT");$message=str_replace("#SITE_CHARSET#",$CHARSET,GetMessage("MF_EVENT_MESSAGE"));if(array_key_exists($event_name.$subject,$dbEvent_))
$emess->Update($dbEvent_[$event_name.$subject]["ID"],array("MESSAGE"=>$message,"BODY_TYPE"=>"html"));else
$emess->Add(array("ACTIVE"=>"Y","EVENT_NAME"=>$event_name,"LID"=>WIZARD_SITE_ID,"EMAIL_FROM"=>"#DEFAULT_EMAIL_FROM#","EMAIL_TO"=>"#EMAIL_TO#","BCC"=>"#BCC#","SUBJECT"=>$subject,"MESSAGE"=>$message,"BODY_TYPE"=>"html",));$emess=new CEventMessage;$event_name="SALE_NEW_ORDER";$subject=GetMessage("SALE_NEW_ORDER_SUBJECT");$message=str_replace("#SITE_CHARSET#",$CHARSET,GetMessage("SALE_NEW_ORDER_MESSAGE"));if(array_key_exists($event_name.$subject,$dbEvent_))
$emess->Update($dbEvent_[$event_name.$subject]["ID"],array("MESSAGE"=>$message,"BODY_TYPE"=>"html"));else
$emess->Add(array("ACTIVE"=>"Y","EVENT_NAME"=>$event_name,"LID"=>WIZARD_SITE_ID,"EMAIL_FROM"=>"#SALE_EMAIL#","EMAIL_TO"=>"#EMAIL#","BCC"=>"#BCC#","SUBJECT"=>$subject,"MESSAGE"=>$message,"BODY_TYPE"=>"html",));$emess=new CEventMessage;$event_name="SALE_NEW_ORDER_RECURRING";$subject=GetMessage("SALE_NEW_ORDER_RECURRING_SUBJECT");$message=GetMessage("SALE_NEW_ORDER_RECURRING_MESSAGE");if(array_key_exists($event_name.$subject,$dbEvent_))
$emess->Update($dbEvent_[$event_name.$subject]["ID"],array("MESSAGE"=>$message,"BODY_TYPE"=>"html"));else
$emess->Add(array("ACTIVE"=>"Y","EVENT_NAME"=>$event_name,"LID"=>WIZARD_SITE_ID,"EMAIL_FROM"=>"#SALE_EMAIL#","EMAIL_TO"=>"#EMAIL#","BCC"=>"#BCC#","SUBJECT"=>$subject,"MESSAGE"=>$message,"BODY_TYPE"=>"html",));$emess=new CEventMessage;$event_name="SALE_ORDER_CANCEL";$subject=GetMessage("SALE_ORDER_CANCEL_SUBJECT");$message=GetMessage("SALE_ORDER_CANCEL_MESSAGE");if(array_key_exists($event_name.$subject,$dbEvent_))
$emess->Update($dbEvent_[$event_name.$subject]["ID"],array("MESSAGE"=>$message,"BODY_TYPE"=>"html"));else
$emess->Add(array("ACTIVE"=>"Y","EVENT_NAME"=>$event_name,"LID"=>WIZARD_SITE_ID,"EMAIL_FROM"=>"#SALE_EMAIL#","EMAIL_TO"=>"#EMAIL#","BCC"=>"#BCC#","SUBJECT"=>$subject,"MESSAGE"=>$message,"BODY_TYPE"=>"html",));$emess=new CEventMessage;$event_name="SALE_ORDER_DELIVERY";$subject=GetMessage("SALE_ORDER_DELIVERY_SUBJECT");$message=GetMessage("SALE_ORDER_DELIVERY_MESSAGE");if(array_key_exists($event_name.$subject,$dbEvent_))
$emess->Update($dbEvent_[$event_name.$subject]["ID"],array("MESSAGE"=>$message,"BODY_TYPE"=>"html"));else
$emess->Add(array("ACTIVE"=>"Y","EVENT_NAME"=>$event_name,"LID"=>WIZARD_SITE_ID,"EMAIL_FROM"=>"#SALE_EMAIL#","EMAIL_TO"=>"#EMAIL#","BCC"=>"#BCC#","SUBJECT"=>$subject,"MESSAGE"=>$message,"BODY_TYPE"=>"html",));$emess=new CEventMessage;$event_name="SALE_ORDER_PAID";$subject=GetMessage("SALE_ORDER_PAID_SUBJECT");$message=GetMessage("SALE_ORDER_PAID_MESSAGE");if(array_key_exists($event_name.$subject,$dbEvent_))
$emess->Update($dbEvent_[$event_name.$subject]["ID"],array("MESSAGE"=>$message,"BODY_TYPE"=>"html"));else
$emess->Add(array("ACTIVE"=>"Y","EVENT_NAME"=>$event_name,"LID"=>WIZARD_SITE_ID,"EMAIL_FROM"=>"#SALE_EMAIL#","EMAIL_TO"=>"#EMAIL#","BCC"=>"#BCC#","SUBJECT"=>$subject,"MESSAGE"=>$message,"BODY_TYPE"=>"html",));$emess=new CEventMessage;$event_name="SALE_RECURRING_CANCEL";$subject=GetMessage("SALE_RECURRING_CANCEL_SUBJECT");$message=GetMessage("SALE_RECURRING_CANCEL_MESSAGE");if(array_key_exists($event_name.$subject,$dbEvent_))
$emess->Update($dbEvent_[$event_name.$subject]["ID"],array("MESSAGE"=>$message,"BODY_TYPE"=>"html"));else
$emess->Add(array("ACTIVE"=>"Y","EVENT_NAME"=>$event_name,"LID"=>WIZARD_SITE_ID,"EMAIL_FROM"=>"#SALE_EMAIL#","EMAIL_TO"=>"#EMAIL#","BCC"=>"#BCC#","SUBJECT"=>$subject,"MESSAGE"=>$message,"BODY_TYPE"=>"html",));$emess=new CEventMessage;$event_name="SALE_ORDER_REMIND_PAYMENT";$subject=GetMessage("SALE_ORDER_REMIND_PAYMENT_SUBJECT");$message=GetMessage("SALE_ORDER_REMIND_PAYMENT_MESSAGE");if(array_key_exists($event_name.$subject,$dbEvent_))
$emess->Update($dbEvent_[$event_name.$subject]["ID"],array("MESSAGE"=>$message,"BODY_TYPE"=>"html"));else
$emess->Add(array("ACTIVE"=>"Y","EVENT_NAME"=>$event_name,"LID"=>WIZARD_SITE_ID,"EMAIL_FROM"=>"#SALE_EMAIL#","EMAIL_TO"=>"#EMAIL#","BCC"=>"#BCC#","SUBJECT"=>$subject,"MESSAGE"=>$message,"BODY_TYPE"=>"html",));$emess=new CEventMessage;$event_name="SALE_SUBSCRIBE_PRODUCT";$subject=GetMessage("UP_SUBJECT");$message=GetMessage("UP_MESSAGE");if(array_key_exists($event_name.$subject,$dbEvent_))
$emess->Update($dbEvent_[$event_name.$subject]["ID"],array("MESSAGE"=>$message,"BODY_TYPE"=>"html"));else
$emess->Add(array("ACTIVE"=>"Y","EVENT_NAME"=>$event_name,"LID"=>WIZARD_SITE_ID,"EMAIL_FROM"=>"#SALE_EMAIL#","EMAIL_TO"=>"#EMAIL#","BCC"=>"#BCC#","SUBJECT"=>$subject,"MESSAGE"=>$message,"BODY_TYPE"=>"html",));if(CModule::IncludeModule("sale"))
{$dbStatus=CSaleStatus::GetList(array($by=>$order),array(),false,false,array("ID","SORT","LID","NAME","DESCRIPTION"));while($arStatus=$dbStatus->Fetch())
{$ID=$arStatus["ID"];$eventType=new CEventType;$eventMessage=new CEventMessage;IncludeModuleLangFile($_SERVER["DOCUMENT_ROOT"]."/bitrix/modules/sale/general/status.php",$lid);$arStatusLang=CSaleStatus::GetLangByID($ID,$lid);$dbEventType=$eventType->GetList(array("EVENT_NAME"=>"SALE_STATUS_CHANGED_".$ID,"LID"=>$lid));if(!($arEventType=$dbEventType->Fetch()))
{$str="";$str.="#ORDER_ID# - ".GetMessage("SKGS_ORDER_ID")."\n";$str.="#ORDER_DATE# - ".GetMessage("SKGS_ORDER_DATE")."\n";$str.="#ORDER_STATUS# - ".GetMessage("SKGS_ORDER_STATUS")."\n";$str.="#EMAIL# - ".GetMessage("SKGS_ORDER_EMAIL")."\n";$str.="#ORDER_DESCRIPTION# - ".GetMessage("SKGS_STATUS_DESCR")."\n";$str.="#TEXT# - ".GetMessage("SKGS_STATUS_TEXT")."\n";$str.="#SALE_EMAIL# - ".GetMessage("SKGS_SALE_EMAIL")."\n";$eventTypeID=$eventType->Add(array("LID"=>$lid,"EVENT_NAME"=>"SALE_STATUS_CHANGED_".$ID,"NAME"=>GetMessage("SKGS_CHANGING_STATUS_TO")." \"".$arStatusLang["NAME"]."\"","DESCRIPTION"=>$str));}
$dbEventMessage=$eventMessage->GetList(($b=""),($o=""),array("EVENT_NAME"=>"SALE_STATUS_CHANGED_".$ID,"SITE_ID"=>WIZARD_SITE_ID));if(!($arEventMessage=$dbEventMessage->Fetch()))
{$message=GetMessage("SKGS_STATUS_MAIL_BODY1");$message.="------------------------------------------\n\n";$message.=GetMessage("SKGS_STATUS_MAIL_BODY2");$message.=GetMessage("SKGS_STATUS_MAIL_BODY3");$message.="#ORDER_STATUS#\n";$message.="#ORDER_DESCRIPTION#\n";$message.="#TEXT#\n\n";$message.=GetMessage("SKGS_STATUS_MAIL_BODY4");$message.="#SITE_NAME#\n";$arFields=Array("ACTIVE"=>"Y","EVENT_NAME"=>"SALE_STATUS_CHANGED_".$ID,"LID"=>WIZARD_SITE_ID,"EMAIL_FROM"=>"#SALE_EMAIL#","EMAIL_TO"=>"#EMAIL#","SUBJECT"=>GetMessage("SKGS_STATUS_MAIL_SUBJ"),"MESSAGE"=>$message,"BODY_TYPE"=>"html");$eventMessageID=$eventMessage->Add($arFields);}}}?>