<?if(!defined("B_PROLOG_INCLUDED")||B_PROLOG_INCLUDED!==true)die();if(!CModule::IncludeModule("sale"))return;if(CModule::IncludeModule('subscribe'))
{$templates_dir=$_SERVER["DOCUMENT_ROOT"].BX_PERSONAL_ROOT."/php_interface/subscribe/templates";$template=$templates_dir."/store_news_".WIZARD_SITE_ID;if(!file_exists($template))
{CopyDirFiles($_SERVER["DOCUMENT_ROOT"]."/bitrix/modules/subscribe/install/php_interface/subscribe/templates/news",$template,false,true);$fname=$template."/template.php";if(file_exists($fname)&&is_file($fname)&&($fh=fopen($fname,"rb")))
{$php_source=fread($fh,filesize($fname));$php_source=preg_replace("#([\"'])(SITE_ID)(\\1)(\\s*=>\s*)([\"'])(.*?)(\\5)#","\\1\\2\\3\\4\\5".WIZARD_SITE_ID."\\7",$php_source);$php_source=str_replace("Windows-1251",$arSite["CHARSET"],$php_source);$php_source=str_replace("Hello!",GetMessage("SUBSCR_1"),$php_source);$php_source=str_replace("<P>Best Regards!</P>","",$php_source);fclose($fh);$fh=fopen($fname,"wb");if($fh)
{fwrite($fh,$php_source);fclose($fh);}}}
$rsRubric=CRubric::GetList(array(),array("NAME"=>GetMessage("SUBSCR_1"),"LID"=>WIZARD_SITE_ID,));if(!$rsRubric->Fetch())
{$arFields=Array("ACTIVE"=>"Y","SORT"=>100,"LID"=>WIZARD_SITE_ID,"VISIBLE"=>"Y","NAME"=>GetMessage("SUBSCR_1"),"DESCRIPTION"=>GetMessage("SUBSCR_2"),"AUTO"=>"Y","DAYS_OF_MONTH"=>"","DAYS_OF_WEEK"=>"1,2,3,4,5,6,7","TIMES_OF_DAY"=>"05:00","LAST_EXECUTED"=>ConvertTimeStamp(false,"FULL"),"TEMPLATE"=>substr($template,strlen($_SERVER["DOCUMENT_ROOT"]."/")),"FROM_FIELD"=>COption::GetOptionString("main","email_from","info@mysite.ru"),);$obRubric=new CRubric;$ID=$obRubric->Add($arFields);}
COption::SetOptionString('subscribe','subscribe_section','#SITE_DIR#personal/subscribe/');}
$editProfileTask=false;$dbResult=CTask::GetList(Array(),Array("NAME"=>"main_change_profile"));if($arTask=$dbResult->Fetch())
$editProfileTask=$arTask["ID"];$dbResult=CGroup::GetList($by,$order,Array("STRING_ID"=>"REGISTERED_USERS"));if(!$dbResult->Fetch())
{$group=new CGroup;$arFields=Array("ACTIVE"=>"Y","C_SORT"=>3,"NAME"=>GetMessage("REGISTERED_USERS"),"STRING_ID"=>"REGISTERED_USERS",);$groupID=$group->Add($arFields);if($groupID>0)
{COption::SetOptionString("main","new_user_registration_def_group",$groupID);if($editProfileTask)
CGroup::SetTasks($groupID,Array($editProfileTask),true);}}
$rsGroups=CGroup::GetList(($by="c_sort"),($order="desc"),array("ACTIVE"=>"Y","ADMIN"=>"N","ANONYMOUS"=>"N"));if(!($rsGroups->Fetch()))
{$group=new CGroup;$arFields=Array("ACTIVE"=>"Y","C_SORT"=>100,"NAME"=>GetMessage("REGISTERED_USERS"),"DESCRIPTION"=>"",);$NEW_GROUP_ID=$group->Add($arFields);COption::SetOptionString('main','new_user_registration_def_group',$NEW_GROUP_ID);$rsTasks=CTask::GetList(array(),array("MODULE_ID"=>"main","SYS"=>"Y","BINDIG"=>"module","LETTER"=>"P"));if($arTask=$rsTasks->Fetch())
CGroup::SetModulePermission($NEW_GROUP_ID,$arTask["MODULE_ID"],$arTask["ID"]);}
$userGroupID="";$dbGroup=CGroup::GetList($by="",$order="",Array("STRING_ID"=>"sale_administrator"));if($arGroup=$dbGroup->Fetch())
$userGroupID=$arGroup["ID"];else
{$group=new CGroup;$arFields=Array("ACTIVE"=>"Y","C_SORT"=>200,"NAME"=>GetMessage("SALE_WIZARD_ADMIN_SALE"),"DESCRIPTION"=>GetMessage("SALE_WIZARD_ADMIN_SALE_DESCR"),"USER_ID"=>array(),"STRING_ID"=>"sale_administrator",);$userGroupID=$group->Add($arFields);}
if(IntVal($userGroupID)>0)
{WizardServices::SetFilePermission(Array(WIZARD_SITE_ID,"/bitrix/admin"),Array($userGroupID=>"R"));WizardServices::SetFilePermission(Array(WIZARD_SITE_ID,"/bitrix/admin"),Array($userGroupID=>"R"));$new_task_id=CTask::Add(array("NAME"=>GetMessage("SALE_WIZARD_ADMIN_SALE"),"DESCRIPTION"=>GetMessage("SALE_WIZARD_ADMIN_SALE_DESCR"),"LETTER"=>"Q","BINDING"=>"module","MODULE_ID"=>"main",));if($new_task_id)
{$arOps=array();$rsOp=COperation::GetList(array(),array("NAME"=>"cache_control|view_own_profile|edit_own_profile"));while($arOp=$rsOp->Fetch())
$arOps[]=$arOp["ID"];CTask::SetOperations($new_task_id,$arOps);}
$rsTasks=CTask::GetList(array(),array("MODULE_ID"=>"main","SYS"=>"N","BINDIG"=>"module","LETTER"=>"Q"));if($arTask=$rsTasks->Fetch())
CGroup::SetModulePermission($userGroupID,$arTask["MODULE_ID"],$arTask["ID"]);CMain::SetGroupRight("sale",$userGroupID,"U");$rsTasks=CTask::GetList(array(),array("MODULE_ID"=>"catalog","SYS"=>"Y","BINDIG"=>"module","LETTER"=>"T"));while($arTask=$rsTasks->Fetch())
CGroup::SetModulePermission($userGroupID,$arTask["MODULE_ID"],$arTask["ID"]);}
$userGroupID="";$dbGroup=CGroup::GetList($by="",$order="",Array("STRING_ID"=>"content_editor"));if($arGroup=$dbGroup->Fetch())
{$userGroupID=$arGroup["ID"];}
else
{$group=new CGroup;$arFields=Array("ACTIVE"=>"Y","C_SORT"=>300,"NAME"=>GetMessage("SALE_WIZARD_CONTENT_EDITOR"),"DESCRIPTION"=>GetMessage("SALE_WIZARD_CONTENT_EDITOR_DESCR"),"USER_ID"=>array(),"STRING_ID"=>"content_editor",);$userGroupID=$group->Add($arFields);$DB->Query("INSERT INTO b_sticker_group_task(GROUP_ID, TASK_ID) SELECT ".intVal($userGroupID).", ID FROM b_task WHERE NAME='stickers_edit' AND MODULE_ID='fileman'",false,"FILE: ".__FILE__."<br> LINE: ".__LINE__);}
if(IntVal($userGroupID)>0)
{WizardServices::SetFilePermission(Array(WIZARD_SITE_ID,"/bitrix/admin"),Array($userGroupID=>"R"));$rsTasks=CTask::GetList(array(),array("MODULE_ID"=>"main","SYS"=>"Y","BINDIG"=>"module","LETTER"=>"P"));if($arTask=$rsTasks->Fetch())
CGroup::SetModulePermission($userGroupID,$arTask["MODULE_ID"],$arTask["ID"]);$rsTasks=CTask::GetList(array(),array("MODULE_ID"=>"fileman","SYS"=>"Y","BINDIG"=>"module","LETTER"=>"F"));if($arTask=$rsTasks->Fetch())
CGroup::SetModulePermission($userGroupID,$arTask["MODULE_ID"],$arTask["ID"]);WizardServices::SetFilePermission(Array(WIZARD_SITE_ID,WIZARD_SITE_DIR."index.php"),Array($userGroupID=>"W"));WizardServices::SetFilePermission(Array(WIZARD_SITE_ID,WIZARD_SITE_DIR."about/"),Array($userGroupID=>"W"));WizardServices::SetFilePermission(Array(WIZARD_SITE_ID,WIZARD_SITE_DIR."delivery/"),Array($userGroupID=>"W"));WizardServices::SetFilePermission(Array(WIZARD_SITE_ID,WIZARD_SITE_DIR."contacts/"),Array($userGroupID=>"W"));WizardServices::SetFilePermission(Array(WIZARD_SITE_ID,WIZARD_SITE_DIR."news/"),Array($userGroupID=>"W"));WizardServices::SetFilePermission(Array(WIZARD_SITE_ID,WIZARD_SITE_DIR."articles/"),Array($userGroupID=>"W"));WizardServices::SetFilePermission(Array(WIZARD_SITE_ID,WIZARD_SITE_DIR."faq/"),Array($userGroupID=>"W"));WizardServices::SetFilePermission(Array(WIZARD_SITE_ID,WIZARD_SITE_DIR."catalog/"),Array($userGroupID=>"W"));WizardServices::SetFilePermission(Array(WIZARD_SITE_ID,WIZARD_SITE_DIR."actions/"),Array($userGroupID=>"W"));WizardServices::SetFilePermission(Array(WIZARD_SITE_ID,WIZARD_SITE_DIR."new/"),Array($userGroupID=>"W"));WizardServices::SetFilePermission(Array(WIZARD_SITE_ID,WIZARD_SITE_DIR."sale/"),Array($userGroupID=>"W"));WizardServices::SetFilePermission(Array(WIZARD_SITE_ID,WIZARD_SITE_DIR."personal/"),Array($userGroupID=>"W"));}?>