<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Блоги компании");
?> <?$APPLICATION->IncludeComponent("bitrix:blog", ".default", array(
	"MESSAGE_COUNT" => "25",
	"PERIOD_DAYS" => "30",
	"MESSAGE_COUNT_MAIN" => "6",
	"BLOG_COUNT_MAIN" => "6",
	"MESSAGE_LENGTH" => "100",
	"BLOG_COUNT" => "20",
	"DATE_TIME_FORMAT" => "d.m.Y H:i:s",
	"NAV_TEMPLATE" => "",
	"SMILES_COUNT" => "4",
	"IMAGE_MAX_WIDTH" => "800",
	"IMAGE_MAX_HEIGHT" => "800",
	"EDITOR_RESIZABLE" => "Y",
	"EDITOR_DEFAULT_HEIGHT" => "300",
	"EDITOR_CODE_DEFAULT" => "N",
	"SEF_MODE" => "Y",
	"SEF_FOLDER" => "#SITE_DIR#blog/",
	"CACHE_TYPE" => "A",
	"CACHE_TIME" => "3600",
	"CACHE_TIME_LONG" => "604800",
	"PATH_TO_SMILE" => "/bitrix/images/blog/smile/",
	"SET_TITLE" => "Y",
	"SET_NAV_CHAIN" => "Y",
	"USER_PROPERTY" => array(
	),
	"BLOG_PROPERTY" => array(
	),
	"BLOG_PROPERTY_LIST" => array(
	),
	"POST_PROPERTY" => array(
	),
	"POST_PROPERTY_LIST" => array(
	),
	"USE_ASC_PAGING" => "N",
	"SHOW_RATING" => "N",
	"RATING_TYPE" => "",
	"ALLOW_POST_CODE" => "Y",
	"USE_GOOGLE_CODE" => "Y",
	"COMMENTS_COUNT" => "25",
	"NOT_USE_COMMENT_TITLE" => "N",
	"AJAX_POST" => "N",
	"COMMENT_EDITOR_RESIZABLE" => "Y",
	"COMMENT_EDITOR_DEFAULT_HEIGHT" => "200",
	"COMMENT_EDITOR_CODE_DEFAULT" => "N",
	"COMMENT_ALLOW_VIDEO" => "N",
	"COMMENT_ALLOW_IMAGE_UPLOAD" => "N",
	"SHOW_SPAM" => "N",
	"NO_URL_IN_COMMENTS" => "",
	"NO_URL_IN_COMMENTS_AUTHORITY" => "",
	"THEME" => "blue",
	"GROUP_ID" => array(
		0 => "",
		1 => "",
	),
	"SHOW_NAVIGATION" => "Y",
	"USER_PROPERTY_NAME" => "",
	"PERIOD_NEW_TAGS" => "",
	"PERIOD" => "",
	"COLOR_TYPE" => "Y",
	"WIDTH" => "100%",
	"SEO_USER" => "N",
	"NAME_TEMPLATE" => "#NOBR##LAST_NAME# #NAME##/NOBR#",
	"SHOW_LOGIN" => "Y",
	"USE_SHARE" => "N",
	"PATH_TO_SONET_USER_PROFILE" => "#SITE_DIR#club/user/#user_id#/",
	"PATH_TO_MESSAGES_CHAT" => "#SITE_DIR#club/messages/chat/#user_id#/",
	"ALLOW_POST_MOVE" => "N",
	"SEF_URL_TEMPLATES" => array(
		"index" => "index.php",
		"group" => "group/#group_id#/",
		"blog" => "#blog#/",
		"user" => "user/#user_id#/",
		"user_friends" => "friends/#user_id#/",
		"search" => "search.php",
		"user_settings" => "#blog#/user_settings.php",
		"user_settings_edit" => "#blog#/user_settings_edit.php?id=#user_id#",
		"group_edit" => "#blog#/group_edit.php",
		"blog_edit" => "#blog#/blog_edit.php",
		"category_edit" => "#blog#/category_edit.php",
		"post_edit" => "#blog#/post_edit.php?id=#post_id#",
		"draft" => "#blog#/draft.php",
		"moderation" => "#blog#/moderation.php",
		"trackback" => POST_FORM_ACTION_URI."&blog=#blog#&id=#post_id#&page=trackback",
		"post" => "#blog#/#post_id#/",
		"post_rss" => "#blog#/rss/#type#/#post_id#",
		"rss" => "#blog#/rss/#type#",
		"rss_all" => "rss/#type#/#group_id#",
	),
	"VARIABLE_ALIASES" => array(
		"user_settings_edit" => array(
			"user_id" => "id",
		),
		"post_edit" => array(
			"post_id" => "id",
		),
		"trackback" => array(
			"blog" => "blog",
			"post_id" => "id",
		),
	)
	),
	false
);?><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>