<?php
/**
 * Created by http://bitcall.ru
 * User: Kurdikov P.S.
 * Date: 17.05.2014
 */


namespace Bitcall\Client\Models\Requests;


class IvrTaskRequest extends TaskRequest {
    private $taskCalls;


    /**
     * @param IvrTaskCall[] $taskCalls
     * @param int $callerPhone
     * @param int $maxRetries
     * @param int $retryTime
     * @param null $sendDate
     * @param null $taskName
     * @param int $waitTime
     */
    function __construct($taskCalls, $callerPhone,$taskName = null, $maxRetries = 0, $retryTime = 5, $sendDate = null,  $waitTime = 45)
    {
        parent::__construct($callerPhone, $maxRetries, $retryTime, $sendDate, $taskName, $waitTime); // TODO: Change the autogenerated stub
        $this->taskCalls = $taskCalls;
    }


    /**
     * @param IvrTaskCall[] $taskCalls
     */
    public function setTaskCalls($taskCalls)
    {
        $this->taskCalls = $taskCalls;
    }

    /**
     * @return IvrTaskCall[]
     */
    public function getTaskCalls()
    {
        return $this->taskCalls;
    }


    /**
     * @param IvrTaskCall $taskCall
     */
    public function appendCall(IvrTaskCall $taskCall)
    {
        if($this->taskCalls === null){
            $this->taskCalls = array();
        }
        $this->taskCalls[] = $taskCall;
    }
} 