CREATE TABLE b_comments
(
    id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    post_id VARCHAR(200) NOT NULL DEFAULT '',
    user_id MEDIUMINT(8) NOT NULL DEFAULT '0',
    date DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
    autor VARCHAR(40) NOT NULL DEFAULT '',
    email VARCHAR(40) NOT NULL DEFAULT '',
    text TEXT NOT NULL,
    ip VARCHAR(16) NOT NULL DEFAULT '',
    is_register TINYINT(1) NOT NULL DEFAULT '0',
    approve TINYINT(1) NOT NULL DEFAULT '1',
    user_agent VARCHAR(64) NOT NULL DEFAULT '',
    PRIMARY KEY (id)
);