<?
$arTooltips = array(
	'USE_QUANTITY' => GetMessage('1CB_PARAMETER_USE_QUANTITY_TIP'),
	'USE_DEBUG_MESSAGES' => GetMessage('1CB_PARAMETER_USE_DEBUG_MESSAGES_TIP'),
	'SEF_FOLDERIX' => GetMessage('1CB_PARAMETER_SEF_FOLDERIX_TIP'),
	'BUY_MODE' => GetMessage('1CB_PARAMETER_BUY_MODE_TIP'),
	'USE_SKU' => GetMessage('1CB_PARAMETER_USE_SKU_TIP'),
	'USE_ANTISPAM' => GetMessage('1CB_PARAMETER_USE_ANTISPAM_TIP'),
);?>
