<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Actions");
?>
<?$APPLICATION->IncludeComponent("bitrix:catalog", "actions", array(
	"IBLOCK_TYPE" => "#IBLOCK_TYPE#",
	"IBLOCK_ID" => "#IBLOCK_ID#",
	"HIDE_NOT_AVAILABLE" => "N",
	"BASKET_URL" => "#SITE_DIR#personal/cart/",
	"ACTION_VARIABLE" => "eshop",
	"PRODUCT_ID_VARIABLE" => "id",
	"SECTION_ID_VARIABLE" => "SECTION_ID",
	"PRODUCT_QUANTITY_VARIABLE" => "quantity",
	"PRODUCT_PROPS_VARIABLE" => "prop",
	"SEF_MODE" => "Y",
	"SEF_FOLDER" => "#SITE_DIR#actions/",
	"AJAX_MODE" => "N",
	"AJAX_OPTION_JUMP" => "N",
	"AJAX_OPTION_STYLE" => "N",
	"AJAX_OPTION_HISTORY" => "N",
	"CACHE_TYPE" => "A",
	"CACHE_TIME" => "36000000",
	"CACHE_FILTER" => "Y",
	"CACHE_GROUPS" => "Y",
	"SET_TITLE" => "Y",
	"SET_STATUS_404" => "Y",
	"USE_ELEMENT_COUNTER" => "Y",
	"USE_FILTER" => "Y",
	"FILTER_NAME" => "arrFilter",
	"FILTER_FIELD_CODE" => array(
		0 => "",
		1 => "",
	),
	"FILTER_PROPERTY_CODE" => array(
		0 => "",
		1 => "",
	),
	"FILTER_PRICE_CODE" => array(
	),
	"FILTER_OFFERS_FIELD_CODE" => array(
		0 => "",
		1 => "",
	),
	"FILTER_OFFERS_PROPERTY_CODE" => array(
		0 => "",
		1 => "",
	),
	"USE_REVIEW" => "Y",
	"MESSAGES_PER_PAGE" => "5",
	"USE_CAPTCHA" => "Y",
	"REVIEW_AJAX_POST" => "N",
	"PATH_TO_SMILE" => "/bitrix/images/forum/smile/",
	"FORUM_ID" => "#FORUM_ID#",
	"URL_TEMPLATES_READ" => "",
	"SHOW_LINK_TO_FORUM" => "N",
	"POST_FIRST_MESSAGE" => "N",
	"USE_COMPARE" => "N",
	"PRICE_CODE" => array(
		0 => "#PRICE_CODE#",
	),
	"USE_PRICE_COUNT" => "N",
	"SHOW_PRICE_COUNT" => "1",
	"PRICE_VAT_INCLUDE" => "Y",
	"PRICE_VAT_SHOW_VALUE" => "N",
	"PRODUCT_PROPERTIES" => array(
		0 => "ARTNUMBER",
		1 => "SIZE",
		2 => "COLOR",
	),
	"USE_PRODUCT_QUANTITY" => "Y",
	"CONVERT_CURRENCY" => "N",
	"CURRENCY_ID" => "RUB",
	"QUANTITY_FLOAT" => "N",	
	"OFFERS_CART_PROPERTIES" => array(
		0 => "ARTNUMBER",
		1 => "SIZE",
		2 => "COLOR",
	),
	"SHOW_TOP_ELEMENTS" => "N",
	"SECTION_COUNT_ELEMENTS" => "Y",
	"SECTION_TOP_DEPTH" => "1",
	"PAGE_ELEMENT_COUNT" => "#PAGE_ELEMENT_COUNT#",
	"LINE_ELEMENT_COUNT" => "1",
	"ELEMENT_SORT_FIELD" => "sort",
	"ELEMENT_SORT_ORDER" => "asc",
	"ELEMENT_SORT_FIELD2" => "id",
	"ELEMENT_SORT_ORDER2" => "desc",
	"LIST_PROPERTY_CODE" => array(
		0 => "ARTNUMBER",
		1 => "BREND",
		2 => "COLLECTION",
		3 => "COUNTRY",
		4 => "SIZE",
		5 => "COLOR",
		6 => "SPECIALOFFER",
		7 => "NEWPRODUCT",
		8 => "SALELEADER",
		9 => "ACTION",
		10 => "",
	),
	"INCLUDE_SUBSECTIONS" => "Y",
	"LIST_META_KEYWORDS" => "UF_KEYWORDS",
	"LIST_META_DESCRIPTION" => "UF_META_DESCRIPTION",
	"LIST_BROWSER_TITLE" => "UF_BROWSER_TITLE",
	"LIST_OFFERS_FIELD_CODE" => array(
		0 => "NAME",
		1 => "",
	),
	"LIST_OFFERS_PROPERTY_CODE" => array(
		0 => "ARTNUMBER",
		1 => "SIZE",
		2 => "COLOR",
		3 => "",
	),
	"LIST_OFFERS_LIMIT" => "0",
	"DETAIL_PROPERTY_CODE" => array(
		0 => "ARTNUMBER",
		1 => "BREND",
		2 => "COLLECTION",
		3 => "COUNTRY",
		4 => "SIZE",
		5 => "COLOR",
		6 => "SPECIALOFFER",
		7 => "NEWPRODUCT",
		8 => "SALELEADER",
		9 => "ACTION",
		10 => "",
	),
	"DETAIL_META_KEYWORDS" => "KEYWORDS",
	"DETAIL_META_DESCRIPTION" => "META_DESCRIPTION",
	"DETAIL_BROWSER_TITLE" => "TITLE",
	"DETAIL_OFFERS_FIELD_CODE" => array(
		0 => "NAME",
		1 => "",
	),
	"DETAIL_OFFERS_PROPERTY_CODE" => array(
		0 => "ARTNUMBER",
		1 => "SIZE",
		2 => "COLOR",
		3 => "",
	),
	"LINK_IBLOCK_TYPE" => "#LINK_IBLOCK_TYPE#",
	"LINK_IBLOCK_ID" => "#LINK_IBLOCK_ID#",
	"LINK_PROPERTY_SID" => "CML2_LINK",
	"LINK_ELEMENTS_URL" => "",
	"USE_ALSO_BUY" => "Y",
	"ALSO_BUY_ELEMENT_COUNT" => "4",
	"ALSO_BUY_MIN_BUYES" => "1",
	"USE_STORE" => "Y",
	"USE_STORE_PHONE" => "Y",
	"USE_STORE_SCHEDULE" => "Y",
	"USE_MIN_AMOUNT" => "Y",
	"MIN_AMOUNT" => "10",
	"STORE_PATH" => "#SITE_DIR#store/#store_id#",
	"MAIN_TITLE" => "Warehouse",
	"OFFERS_SORT_FIELD" => "sort",
	"OFFERS_SORT_ORDER" => "asc",
	"OFFERS_SORT_FIELD2" => "id",
	"OFFERS_SORT_ORDER2" => "desc",
	"DISPLAY_TOP_PAGER" => "N",
	"DISPLAY_BOTTOM_PAGER" => "Y",
	"PAGER_TITLE" => "Goods",
	"PAGER_SHOW_ALWAYS" => "N",
	"PAGER_TEMPLATE" => "arrows",	
	"PAGER_DESC_NUMBERING" => "N",
	"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000000",
	"PAGER_SHOW_ALL" => "N",
	"OFFERS_FIELDS" => array(
		0 => "NAME",
		1 => "",
	),
	"OFFERS_PROPERTIES" => array(
		0 => "ARTNUMBER",
		1 => "SIZE",
		2 => "COLOR",
		3 => "",
	),
	"AJAX_OPTION_ADDITIONAL" => "",
	"SEF_URL_TEMPLATES" => array(
		"sections" => "",
		"section" => "#SECTION_CODE#/",
		"element" => "#SECTION_CODE#/#ELEMENT_ID#/",
		"compare" => "compare/",
	)
	),
	false
);?><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>