CREATE TABLE IF NOT EXISTS `b_tcs_order` (
  `ID` int(18) NOT NULL AUTO_INCREMENT,
  `ORDER_ID` int(18) NOT NULL,
  `STATUS` VARCHAR(3) NOT NULL,
  `APPROVED` VARCHAR(1) NOT NULL DEFAULT 'N',
  `PRINTED` VARCHAR(1) NOT NULL DEFAULT 'N',
  `SUBSCRIBED` VARCHAR(1) NOT NULL DEFAULT 'N',
  `CANCELED` VARCHAR(1) NOT NULL DEFAULT 'N',
  `CANCEL_STATUS` VARCHAR(50) NOT NULL DEFAULT '',
  `DOWN_PAYMENT` decimal(18, 2) not null,
  `MAX_LOAN_AMOUNT` decimal(18, 2) not null,
  `MONTHLY_PAYMENT` decimal(18, 2) not null,
  `PAYMENT_COUNT` int(18),
  `SIGNING_DEADLINE` DATE,
  `DELIVERY_DEADLINE` DATE,
  `SIGNING_TYPE` VARCHAR(50),
  `COMMENT` TEXT,
  PRIMARY KEY (`ID`)
) AUTO_INCREMENT=1;
