<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Online shop \"SergeLand\"");
?> 
<?$APPLICATION->IncludeComponent("sergeland:supersized.jquery.plugin", "", array(
	"BANNER_IMAGES_BIG" => array(
		0  => "#SITE_DIR#images/supersized/slides/slide_01.jpg",
		1  => "#SITE_DIR#images/supersized/slides/slide_02.jpg",
		2  => "#SITE_DIR#images/supersized/slides/slide_03.jpg",
		3  => "#SITE_DIR#images/supersized/slides/slide_04.jpg",
		4  => "#SITE_DIR#images/supersized/slides/slide_05.jpg",
		5  => "#SITE_DIR#images/supersized/slides/slide_07.jpg",
		6  => "#SITE_DIR#images/supersized/slides/slide_19.jpg",
		7  => "#SITE_DIR#images/supersized/slides/slide_15.jpg",
		8  => "#SITE_DIR#images/supersized/slides/slide_08.jpg",
		9  => "#SITE_DIR#images/supersized/slides/slide_06.jpg",
		10 => "#SITE_DIR#images/supersized/slides/slide_09.jpg",
		11 => "#SITE_DIR#images/supersized/slides/slide_10.jpg",
		12 => "#SITE_DIR#images/supersized/slides/slide_11.jpg",
		13 => "#SITE_DIR#images/supersized/slides/slide_12.jpg",
		14 => "#SITE_DIR#images/supersized/slides/slide_13.jpg",
		15 => "#SITE_DIR#images/supersized/slides/slide_14.jpg",
		16 => "#SITE_DIR#images/supersized/slides/slide_16.jpg",
		17 => "#SITE_DIR#images/supersized/slides/slide_17.jpg",
		18 => "#SITE_DIR#images/supersized/slides/slide_18.jpg",
		19 => "#SITE_DIR#images/supersized/slides/slide_20.jpg",
		20 => "",
	),
	"BANNER_IMAGES_SMALL" => array(
		0  => "#SITE_DIR#images/supersized/thumb/slide_01_thb.jpg",
		1  => "#SITE_DIR#images/supersized/thumb/slide_02_thb.jpg",
		2  => "#SITE_DIR#images/supersized/thumb/slide_03_thb.jpg",
		3  => "#SITE_DIR#images/supersized/thumb/slide_04_thb.jpg",
		4  => "#SITE_DIR#images/supersized/thumb/slide_05_thb.jpg",
		5  => "#SITE_DIR#images/supersized/thumb/slide_07_thb.jpg",
		6  => "#SITE_DIR#images/supersized/thumb/slide_19_thb.jpg",
		7  => "#SITE_DIR#images/supersized/thumb/slide_15_thb.jpg",
		8  => "#SITE_DIR#images/supersized/thumb/slide_08_thb.jpg",
		9  => "#SITE_DIR#images/supersized/thumb/slide_06_thb.jpg",
		10 => "#SITE_DIR#images/supersized/thumb/slide_09_thb.jpg",
		11 => "#SITE_DIR#images/supersized/thumb/slide_10_thb.jpg",
		12 => "#SITE_DIR#images/supersized/thumb/slide_11_thb.jpg",
		13 => "#SITE_DIR#images/supersized/thumb/slide_12_thb.jpg",
		14 => "#SITE_DIR#images/supersized/thumb/slide_13_thb.jpg",
		15 => "#SITE_DIR#images/supersized/thumb/slide_14_thb.jpg",
		16 => "#SITE_DIR#images/supersized/thumb/slide_16_thb.jpg",
		17 => "#SITE_DIR#images/supersized/thumb/slide_17_thb.jpg",
		18 => "#SITE_DIR#images/supersized/thumb/slide_18_thb.jpg",
		19 => "#SITE_DIR#images/supersized/thumb/slide_20_thb.jpg",
		20 => "",
	),
	"BANNER_HEAD" => array(
		0 => "#BANNER_HEAD_0#",
		1 => "#BANNER_HEAD_1#",
		2 => "#BANNER_HEAD_2#",
		3 => "#BANNER_HEAD_3#",
		4 => "#BANNER_HEAD_4#",
		5 => "#BANNER_HEAD_5#",
		6 => "#BANNER_HEAD_6#",
		7 => "#BANNER_HEAD_7#",
		8 => "#BANNER_HEAD_8#",
		9 => "",
	),
	"BANNER_TEXT" => array(
		0 => "#BANNER_TEXT_0#",
		1 => "#BANNER_TEXT_1#",
		2 => "#BANNER_TEXT_2#",
		3 => "#BANNER_TEXT_3#",
		4 => "#BANNER_TEXT_4#",
		5 => "#BANNER_TEXT_5#",
		6 => "#BANNER_TEXT_6#",
		7 => "#BANNER_TEXT_7#",
		8 => "#BANNER_TEXT_8#",
		9 => "",
	),
	"AUTOPLAY" => "Y",
	"START_SLIDE" => "Y",
	"SLIDE_INTERVAL" => "9000",
	"TRANSITION" => "1",
	"TRANSITION_SPEED" => "600",
	"SLIDE_LINKS" => "empty",
	"THEMEVARS_IMAGE_PATH" => "#SITE_DIR#images/supersized/"
	),
	false
);?>
<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>