<?define('NEED_AUTH', true);
require($_SERVER['DOCUMENT_ROOT'].'/bitrix/header.php');

if (isset($_REQUEST['backurl']) && strlen($_REQUEST['backurl'])>0)
	LocalRedirect($backurl);

$APPLICATION->SetTitle("Авторизация");

?><p style="margin-bottom: 30px">Вы успешно зарегистрировались и авторизовались на сайте!</p>
<h2>Лучшие товары</h2>
<?$APPLICATION->IncludeComponent(
	"bitrix:catalog.section",
	"flyaway",
	Array(
		"ACTION_VARIABLE" => "action",
		"ADD_PICT_PROP" => "-",
		"ADD_PROPERTIES_TO_BASKET" => "Y",
		"ADD_SECTIONS_CHAIN" => "N",
		"ADD_TO_BASKET_ACTION" => "ADD",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"BACKGROUND_IMAGE" => "-",
		"BASKET_URL" => "#SITE_DIR#personal/cart/",
		"BROWSER_TITLE" => "-",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "A",
		"COMPARE_PATH" => "",
		"COMPONENT_TEMPLATE" => "flyaway",
		"CONVERT_CURRENCY" => "N",
		"DETAIL_URL" => "",
		"DISABLE_INIT_JS_IN_COMPONENT" => "N",
		"DISPLAY_BOTTOM_PAGER" => "N",
		"DISPLAY_COMPARE" => "Y",
		"DISPLAY_TOP_PAGER" => "N",
		"ELEMENT_SORT_FIELD" => "sort",
		"ELEMENT_SORT_FIELD2" => "timestamp_x",
		"ELEMENT_SORT_ORDER" => "asc",
		"ELEMENT_SORT_ORDER2" => "asc",
		"FILTER_NAME" => "arrFilter",
		"HIDE_NOT_AVAILABLE" => "N",
		"IBLOCK_ID" => "#IBLOCK_ID_catalog_catalog#",
		"IBLOCK_TYPE" => "catalog",
		"INCLUDE_SUBSECTIONS" => "A",
		"LABEL_PROP" => "-",
		"LINE_ELEMENT_COUNT" => "4",
		"MAIN_TITLE" => "Наличие",
		"MESSAGE_404" => "",
		"MESS_BTN_ADD_TO_BASKET" => "В корзину",
		"MESS_BTN_BUY" => "Купить",
		"MESS_BTN_COMPARE" => "Сравнить",
		"MESS_BTN_DETAIL" => "Подробнее",
		"MESS_BTN_SUBSCRIBE" => "Подписаться",
		"MESS_NOT_AVAILABLE" => "Нет в наличии",
		"META_DESCRIPTION" => "-",
		"META_KEYWORDS" => "-",
		"MIN_AMOUNT" => "10",
		"OFFERS_CART_PROPERTIES" => array(),
		"OFFERS_FIELD_CODE" => array(0=>"ID",1=>"",),
		"OFFERS_LIMIT" => "5",
		"OFFERS_PROPERTY_CODE" => array(0=>"COLOR_DIRECTORY",1=>"SKU_FASOVKA",2=>"SKU_SIZE",3=>"MORE_PHOTO",4=>"",),
		"OFFERS_SORT_FIELD" => "sort",
		"OFFERS_SORT_FIELD2" => "id",
		"OFFERS_SORT_ORDER" => "asc",
		"OFFERS_SORT_ORDER2" => "desc",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => ".default",
		"PAGER_TITLE" => "Товары",
		"PAGE_ELEMENT_COUNT" => "5",
		"PARTIAL_PRODUCT_PROPERTIES" => "N",
		"PRICE_CODE" => array(0=>"BASE",),
		"PRICE_VAT_INCLUDE" => "Y",
		"PRODUCT_DISPLAY_MODE" => "N",
		"PRODUCT_ID_VARIABLE" => "id",
		"PRODUCT_PROPERTIES" => array(),
		"PRODUCT_PROPS_VARIABLE" => "prop",
		"PRODUCT_QUANTITY_VARIABLE" => "",
		"PRODUCT_SUBSCRIPTION" => "N",
		"PROPERTY_CODE" => array(0=>"CML2_ARTICLE",1=>"ACTION_ITEM",2=>"BEST_SELLER",3=>"NEW_ITEM",4=>"BRAND",5=>"MOSHNOST",6=>"DIAMETR",7=>"FOR_TAB_SOSTAV",8=>"ACCESSORIES",9=>"COLOR_HL",10=>"PRICE",11=>"DISCOUNT",12=>"CURRENCY",13=>"QUANTITY",14=>"",),
		"RSFLYAWAY_PROP_ARTICLE" => "CML2_ARTICLE",
		"RSFLYAWAY_PROP_ARTICLEE" => "CML2_ARTICLE",
		"RSFLYAWAY_PROP_CURRENCY" => "CURRENCY",
		"RSFLYAWAY_PROP_DISCOUNT" => "DISCOUNT",
		"RSFLYAWAY_PROP_MORE_PHOTO" => "MORE_PHOTO",
		"RSFLYAWAY_PROP_OFF_POPUP" => "N",
		"RSFLYAWAY_PROP_PRICE" => "PRICE",
		"RSFLYAWAY_PROP_PRICE_DECIMALS" => "2",
		"RSFLYAWAY_PROP_QUANTITY" => "QUANTITY",
		"RSFLYAWAY_SHOW_SORTER" => "Y",
		"RSFLYAWAY_SORTER_TEMPLATE_DEFAULT" => "showcase",
		"RSFLYAWAY_USE_FAVORITE" => "Y",
		"SECTION_CODE" => "",
		"SECTION_CODE_PATH" => "",
		"SECTION_ID" => "",
		"SECTION_ID_VARIABLE" => "SECTION_ID",
		"SECTION_URL" => "",
		"SECTION_USER_FIELDS" => array(0=>"",1=>"",),
		"SEF_MODE" => "N",
		"SEF_RULE" => "",
		"STORES" => array(0=>"1",1=>"2",2=>"3",),
		"STORES_FIELDS" => array(0=>"TITLE",1=>"ADDRESS",2=>"",),
		"STORE_PATH" => "#SITE_DIR#store/#store_id#",
		"TEMPLATE_THEME" => "blue",
		"USER_FIELDS" => array(0=>"",1=>"",),
		"USE_MAIN_ELEMENT_SECTION" => "N",
		"USE_MIN_AMOUNT" => "Y",
		"USE_PRICE_COUNT" => "N",
		"USE_PRODUCT_QUANTITY" => "N",
    "SHOW_SECTION_URL" => "Y",
		"USE_STORE" => "Y"
	)
);?><?require($_SERVER['DOCUMENT_ROOT'].'/bitrix/footer.php');?>
