<?
if(!defined("B_PROLOG_INCLUDED") || B_PROLOG_INCLUDED!==true)
	die();
$et = new CEventType;
$em = new CEventMessage;
$eventTypes=
		Array(
			);

foreach($eventTypes as $typeId => $eventType)
{
	foreach($eventType as $lang=>$event)
	{
		$rsET = CEventType::GetByID($typeId, $lang);
		if(!$arET = $rsET->Fetch())
			$et->Add($event);
	}
}

$eventMessages=array(
		Array(
			'EVENT_NAME' => 'EDIT_FORUM_MESSAGE',
			'ACTIVE' => 'Y',
			'SITE_ID' => 's1',
			'EMAIL_FROM' => '#FROM_EMAIL#',
			'EMAIL_TO' => '#RECIPIENT#',
			'SUBJECT' => '#SITE_NAME#: [F] #TOPIC_TITLE# : #FORUM_NAME#',
			'MESSAGE' => GetMessage('message_11_MESSAGE'),
			'BODY_TYPE' => 'text',
			'BCC' => '',
			'REPLY_TO' => '',
			'CC' => '',
			'IN_REPLY_TO' => '',
			'PRIORITY' => '',
			'FIELD1_NAME' => '',
			'FIELD1_VALUE' => '',
			'FIELD2_NAME' => '',
			'FIELD2_VALUE' => '',
			'EVENT_TYPE' => GetMessage('message_11_EVENT_TYPE'),
			),
	Array(
			'EVENT_NAME' => 'FEEDBACK_FORM',
			'ACTIVE' => 'Y',
			'SITE_ID' => 's1',
			'EMAIL_FROM' => '#DEFAULT_EMAIL_FROM#',
			'EMAIL_TO' => '#EMAIL_TO#',
			'SUBJECT' => GetMessage('message_7_SUBJECT'),
			'MESSAGE' => GetMessage('message_7_MESSAGE'),
			'BODY_TYPE' => 'text',
			'BCC' => '',
			'REPLY_TO' => '',
			'CC' => '',
			'IN_REPLY_TO' => '',
			'PRIORITY' => '',
			'FIELD1_NAME' => '',
			'FIELD1_VALUE' => '',
			'FIELD2_NAME' => '',
			'FIELD2_VALUE' => '',
			'EVENT_TYPE' => GetMessage('message_7_EVENT_TYPE'),
			),
	Array(
			'EVENT_NAME' => 'FORUM_NEW_MESSAGE_MAIL',
			'ACTIVE' => 'Y',
			'SITE_ID' => 's1',
			'EMAIL_FROM' => '#FROM_EMAIL#',
			'EMAIL_TO' => '#RECIPIENT#',
			'SUBJECT' => '#TOPIC_TITLE#',
			'MESSAGE' => GetMessage('message_12_MESSAGE'),
			'BODY_TYPE' => 'text',
			'BCC' => '',
			'REPLY_TO' => '',
			'CC' => '',
			'IN_REPLY_TO' => '',
			'PRIORITY' => '',
			'FIELD1_NAME' => '',
			'FIELD1_VALUE' => '',
			'FIELD2_NAME' => '',
			'FIELD2_VALUE' => '',
			'EVENT_TYPE' => GetMessage('message_12_EVENT_TYPE'),
			),
	Array(
			'EVENT_NAME' => 'NEW_FORUM_MESSAGE',
			'ACTIVE' => 'Y',
			'SITE_ID' => 's1',
			'EMAIL_FROM' => '#FROM_EMAIL#',
			'EMAIL_TO' => '#RECIPIENT#',
			'SUBJECT' => '#SITE_NAME#: [F] #TOPIC_TITLE# : #FORUM_NAME#',
			'MESSAGE' => GetMessage('message_8_MESSAGE'),
			'BODY_TYPE' => 'text',
			'BCC' => '',
			'REPLY_TO' => '',
			'CC' => '',
			'IN_REPLY_TO' => '',
			'PRIORITY' => '',
			'FIELD1_NAME' => '',
			'FIELD1_VALUE' => '',
			'FIELD2_NAME' => '',
			'FIELD2_VALUE' => '',
			'EVENT_TYPE' => GetMessage('message_8_EVENT_TYPE'),
			),
	Array(
			'EVENT_NAME' => 'NEW_FORUM_PRIV',
			'ACTIVE' => 'Y',
			'SITE_ID' => 's1',
			'EMAIL_FROM' => '#FROM_EMAIL#',
			'EMAIL_TO' => '#TO_EMAIL#',
			'SUBJECT' => '#SITE_NAME#: [private] #SUBJECT#',
			'MESSAGE' => GetMessage('message_9_MESSAGE'),
			'BODY_TYPE' => 'text',
			'BCC' => '',
			'REPLY_TO' => '',
			'CC' => '',
			'IN_REPLY_TO' => '',
			'PRIORITY' => '',
			'FIELD1_NAME' => '',
			'FIELD1_VALUE' => '',
			'FIELD2_NAME' => '',
			'FIELD2_VALUE' => '',
			'EVENT_TYPE' => GetMessage('message_9_EVENT_TYPE'),
			),
	Array(
			'EVENT_NAME' => 'NEW_FORUM_PRIVATE_MESSAGE',
			'ACTIVE' => 'Y',
			'SITE_ID' => 's1',
			'EMAIL_FROM' => '#FROM_EMAIL#',
			'EMAIL_TO' => '#TO_EMAIL#',
			'SUBJECT' => '#SITE_NAME#: [private] #SUBJECT#',
			'MESSAGE' => GetMessage('message_10_MESSAGE'),
			'BODY_TYPE' => 'text',
			'BCC' => '',
			'REPLY_TO' => '',
			'CC' => '',
			'IN_REPLY_TO' => '',
			'PRIORITY' => '',
			'FIELD1_NAME' => '',
			'FIELD1_VALUE' => '',
			'FIELD2_NAME' => '',
			'FIELD2_VALUE' => '',
			'EVENT_TYPE' => GetMessage('message_10_EVENT_TYPE'),
			),
	Array(
			'EVENT_NAME' => 'NEW_USER',
			'ACTIVE' => 'Y',
			'SITE_ID' => 's1',
			'EMAIL_FROM' => '#DEFAULT_EMAIL_FROM#',
			'EMAIL_TO' => '#DEFAULT_EMAIL_FROM#',
			'SUBJECT' => GetMessage('message_1_SUBJECT'),
			'MESSAGE' => GetMessage('message_1_MESSAGE'),
			'BODY_TYPE' => 'text',
			'BCC' => '',
			'REPLY_TO' => '',
			'CC' => '',
			'IN_REPLY_TO' => '',
			'PRIORITY' => '',
			'FIELD1_NAME' => '',
			'FIELD1_VALUE' => '',
			'FIELD2_NAME' => '',
			'FIELD2_VALUE' => '',
			'EVENT_TYPE' => GetMessage('message_1_EVENT_TYPE'),
			),
	Array(
			'EVENT_NAME' => 'NEW_USER_CONFIRM',
			'ACTIVE' => 'Y',
			'SITE_ID' => 's1',
			'EMAIL_FROM' => '#DEFAULT_EMAIL_FROM#',
			'EMAIL_TO' => '#EMAIL#',
			'SUBJECT' => GetMessage('message_5_SUBJECT'),
			'MESSAGE' => GetMessage('message_5_MESSAGE'),
			'BODY_TYPE' => 'text',
			'BCC' => '',
			'REPLY_TO' => '',
			'CC' => '',
			'IN_REPLY_TO' => '',
			'PRIORITY' => '',
			'FIELD1_NAME' => '',
			'FIELD1_VALUE' => '',
			'FIELD2_NAME' => '',
			'FIELD2_VALUE' => '',
			'EVENT_TYPE' => GetMessage('message_5_EVENT_TYPE'),
			),
	Array(
			'EVENT_NAME' => 'SALE_NEW_ORDER',
			'ACTIVE' => 'Y',
			'SITE_ID' => 's1',
			'EMAIL_FROM' => '#SALE_EMAIL#',
			'EMAIL_TO' => '#EMAIL#',
			'SUBJECT' => GetMessage('message_13_SUBJECT'),
			'MESSAGE' => GetMessage('message_13_MESSAGE'),
			'BODY_TYPE' => 'text',
			'BCC' => '#BCC#',
			'REPLY_TO' => '',
			'CC' => '',
			'IN_REPLY_TO' => '',
			'PRIORITY' => '',
			'FIELD1_NAME' => '',
			'FIELD1_VALUE' => '',
			'FIELD2_NAME' => '',
			'FIELD2_VALUE' => '',
			'EVENT_TYPE' => GetMessage('message_13_EVENT_TYPE'),
			),
	Array(
			'EVENT_NAME' => 'SALE_NEW_ORDER_RECURRING',
			'ACTIVE' => 'Y',
			'SITE_ID' => 's1',
			'EMAIL_FROM' => '#SALE_EMAIL#',
			'EMAIL_TO' => '#EMAIL#',
			'SUBJECT' => GetMessage('message_14_SUBJECT'),
			'MESSAGE' => GetMessage('message_14_MESSAGE'),
			'BODY_TYPE' => 'text',
			'BCC' => '#BCC#',
			'REPLY_TO' => '',
			'CC' => '',
			'IN_REPLY_TO' => '',
			'PRIORITY' => '',
			'FIELD1_NAME' => '',
			'FIELD1_VALUE' => '',
			'FIELD2_NAME' => '',
			'FIELD2_VALUE' => '',
			'EVENT_TYPE' => GetMessage('message_14_EVENT_TYPE'),
			),
	Array(
			'EVENT_NAME' => 'SALE_ORDER_CANCEL',
			'ACTIVE' => 'Y',
			'SITE_ID' => 's1',
			'EMAIL_FROM' => '#SALE_EMAIL#',
			'EMAIL_TO' => '#EMAIL#',
			'SUBJECT' => GetMessage('message_15_SUBJECT'),
			'MESSAGE' => GetMessage('message_15_MESSAGE'),
			'BODY_TYPE' => 'text',
			'BCC' => '#BCC#',
			'REPLY_TO' => '',
			'CC' => '',
			'IN_REPLY_TO' => '',
			'PRIORITY' => '',
			'FIELD1_NAME' => '',
			'FIELD1_VALUE' => '',
			'FIELD2_NAME' => '',
			'FIELD2_VALUE' => '',
			'EVENT_TYPE' => GetMessage('message_15_EVENT_TYPE'),
			),
	Array(
			'EVENT_NAME' => 'SALE_ORDER_DELIVERY',
			'ACTIVE' => 'Y',
			'SITE_ID' => 's1',
			'EMAIL_FROM' => '#SALE_EMAIL#',
			'EMAIL_TO' => '#EMAIL#',
			'SUBJECT' => GetMessage('message_16_SUBJECT'),
			'MESSAGE' => GetMessage('message_16_MESSAGE'),
			'BODY_TYPE' => 'text',
			'BCC' => '#BCC#',
			'REPLY_TO' => '',
			'CC' => '',
			'IN_REPLY_TO' => '',
			'PRIORITY' => '',
			'FIELD1_NAME' => '',
			'FIELD1_VALUE' => '',
			'FIELD2_NAME' => '',
			'FIELD2_VALUE' => '',
			'EVENT_TYPE' => GetMessage('message_16_EVENT_TYPE'),
			),
	Array(
			'EVENT_NAME' => 'SALE_ORDER_PAID',
			'ACTIVE' => 'Y',
			'SITE_ID' => 's1',
			'EMAIL_FROM' => '#SALE_EMAIL#',
			'EMAIL_TO' => '#EMAIL#',
			'SUBJECT' => GetMessage('message_17_SUBJECT'),
			'MESSAGE' => GetMessage('message_17_MESSAGE'),
			'BODY_TYPE' => 'text',
			'BCC' => '#BCC#',
			'REPLY_TO' => '',
			'CC' => '',
			'IN_REPLY_TO' => '',
			'PRIORITY' => '',
			'FIELD1_NAME' => '',
			'FIELD1_VALUE' => '',
			'FIELD2_NAME' => '',
			'FIELD2_VALUE' => '',
			'EVENT_TYPE' => GetMessage('message_17_EVENT_TYPE'),
			),
	Array(
			'EVENT_NAME' => 'SALE_ORDER_REMIND_PAYMENT',
			'ACTIVE' => 'Y',
			'SITE_ID' => 's1',
			'EMAIL_FROM' => '#SALE_EMAIL#',
			'EMAIL_TO' => '#EMAIL#',
			'SUBJECT' => GetMessage('message_19_SUBJECT'),
			'MESSAGE' => GetMessage('message_19_MESSAGE'),
			'BODY_TYPE' => 'text',
			'BCC' => '#BCC#',
			'REPLY_TO' => '',
			'CC' => '',
			'IN_REPLY_TO' => '',
			'PRIORITY' => '',
			'FIELD1_NAME' => '',
			'FIELD1_VALUE' => '',
			'FIELD2_NAME' => '',
			'FIELD2_VALUE' => '',
			'EVENT_TYPE' => GetMessage('message_19_EVENT_TYPE'),
			),
	Array(
			'EVENT_NAME' => 'SALE_RECURRING_CANCEL',
			'ACTIVE' => 'Y',
			'SITE_ID' => 's1',
			'EMAIL_FROM' => '#SALE_EMAIL#',
			'EMAIL_TO' => '#EMAIL#',
			'SUBJECT' => GetMessage('message_18_SUBJECT'),
			'MESSAGE' => GetMessage('message_18_MESSAGE'),
			'BODY_TYPE' => 'text',
			'BCC' => '#BCC#',
			'REPLY_TO' => '',
			'CC' => '',
			'IN_REPLY_TO' => '',
			'PRIORITY' => '',
			'FIELD1_NAME' => '',
			'FIELD1_VALUE' => '',
			'FIELD2_NAME' => '',
			'FIELD2_VALUE' => '',
			'EVENT_TYPE' => GetMessage('message_18_EVENT_TYPE'),
			),
	Array(
			'EVENT_NAME' => 'SALE_STATUS_CHANGED_F',
			'ACTIVE' => 'Y',
			'SITE_ID' => 's1',
			'EMAIL_FROM' => '#SALE_EMAIL#',
			'EMAIL_TO' => '#EMAIL#',
			'SUBJECT' => GetMessage('message_21_SUBJECT'),
			'MESSAGE' => GetMessage('message_21_MESSAGE'),
			'BODY_TYPE' => 'text',
			'BCC' => '',
			'REPLY_TO' => '',
			'CC' => '',
			'IN_REPLY_TO' => '',
			'PRIORITY' => '',
			'FIELD1_NAME' => '',
			'FIELD1_VALUE' => '',
			'FIELD2_NAME' => '',
			'FIELD2_VALUE' => '',
			'EVENT_TYPE' => GetMessage('message_21_EVENT_TYPE'),
			),
	Array(
			'EVENT_NAME' => 'SALE_STATUS_CHANGED_N',
			'ACTIVE' => 'Y',
			'SITE_ID' => 's1',
			'EMAIL_FROM' => '#SALE_EMAIL#',
			'EMAIL_TO' => '#EMAIL#',
			'SUBJECT' => GetMessage('message_20_SUBJECT'),
			'MESSAGE' => GetMessage('message_20_MESSAGE'),
			'BODY_TYPE' => 'text',
			'BCC' => '',
			'REPLY_TO' => '',
			'CC' => '',
			'IN_REPLY_TO' => '',
			'PRIORITY' => '',
			'FIELD1_NAME' => '',
			'FIELD1_VALUE' => '',
			'FIELD2_NAME' => '',
			'FIELD2_VALUE' => '',
			'EVENT_TYPE' => GetMessage('message_20_EVENT_TYPE'),
			),
	Array(
			'EVENT_NAME' => 'SUBSCRIBE_CONFIRM',
			'ACTIVE' => 'Y',
			'SITE_ID' => 's1',
			'EMAIL_FROM' => '#DEFAULT_EMAIL_FROM#',
			'EMAIL_TO' => '#EMAIL#',
			'SUBJECT' => GetMessage('message_23_SUBJECT'),
			'MESSAGE' => GetMessage('message_23_MESSAGE'),
			'BODY_TYPE' => 'text',
			'BCC' => '',
			'REPLY_TO' => '',
			'CC' => '',
			'IN_REPLY_TO' => '',
			'PRIORITY' => '',
			'FIELD1_NAME' => '',
			'FIELD1_VALUE' => '',
			'FIELD2_NAME' => '',
			'FIELD2_VALUE' => '',
			'EVENT_TYPE' => GetMessage('message_23_EVENT_TYPE'),
			),
	Array(
			'EVENT_NAME' => 'USER_INFO',
			'ACTIVE' => 'Y',
			'SITE_ID' => 's1',
			'EMAIL_FROM' => '#DEFAULT_EMAIL_FROM#',
			'EMAIL_TO' => '#EMAIL#',
			'SUBJECT' => GetMessage('message_2_SUBJECT'),
			'MESSAGE' => GetMessage('message_2_MESSAGE'),
			'BODY_TYPE' => 'text',
			'BCC' => '',
			'REPLY_TO' => '',
			'CC' => '',
			'IN_REPLY_TO' => '',
			'PRIORITY' => '',
			'FIELD1_NAME' => '',
			'FIELD1_VALUE' => '',
			'FIELD2_NAME' => '',
			'FIELD2_VALUE' => '',
			'EVENT_TYPE' => GetMessage('message_2_EVENT_TYPE'),
			),
	Array(
			'EVENT_NAME' => 'USER_INVITE',
			'ACTIVE' => 'Y',
			'SITE_ID' => 's1',
			'EMAIL_FROM' => '#DEFAULT_EMAIL_FROM#',
			'EMAIL_TO' => '#EMAIL#',
			'SUBJECT' => GetMessage('message_6_SUBJECT'),
			'MESSAGE' => GetMessage('message_6_MESSAGE'),
			'BODY_TYPE' => 'text',
			'BCC' => '',
			'REPLY_TO' => '',
			'CC' => '',
			'IN_REPLY_TO' => '',
			'PRIORITY' => '',
			'FIELD1_NAME' => '',
			'FIELD1_VALUE' => '',
			'FIELD2_NAME' => '',
			'FIELD2_VALUE' => '',
			'EVENT_TYPE' => GetMessage('message_6_EVENT_TYPE'),
			),
	Array(
			'EVENT_NAME' => 'USER_PASS_CHANGED',
			'ACTIVE' => 'Y',
			'SITE_ID' => 's1',
			'EMAIL_FROM' => '#DEFAULT_EMAIL_FROM#',
			'EMAIL_TO' => '#EMAIL#',
			'SUBJECT' => GetMessage('message_4_SUBJECT'),
			'MESSAGE' => GetMessage('message_4_MESSAGE'),
			'BODY_TYPE' => 'text',
			'BCC' => '',
			'REPLY_TO' => '',
			'CC' => '',
			'IN_REPLY_TO' => '',
			'PRIORITY' => '',
			'FIELD1_NAME' => '',
			'FIELD1_VALUE' => '',
			'FIELD2_NAME' => '',
			'FIELD2_VALUE' => '',
			'EVENT_TYPE' => GetMessage('message_4_EVENT_TYPE'),
			),
	Array(
			'EVENT_NAME' => 'USER_PASS_REQUEST',
			'ACTIVE' => 'Y',
			'SITE_ID' => 's1',
			'EMAIL_FROM' => '#DEFAULT_EMAIL_FROM#',
			'EMAIL_TO' => '#EMAIL#',
			'SUBJECT' => GetMessage('message_3_SUBJECT'),
			'MESSAGE' => GetMessage('message_3_MESSAGE'),
			'BODY_TYPE' => 'text',
			'BCC' => '',
			'REPLY_TO' => '',
			'CC' => '',
			'IN_REPLY_TO' => '',
			'PRIORITY' => '',
			'FIELD1_NAME' => '',
			'FIELD1_VALUE' => '',
			'FIELD2_NAME' => '',
			'FIELD2_VALUE' => '',
			'EVENT_TYPE' => GetMessage('message_3_EVENT_TYPE'),
			),
	Array(
			'EVENT_NAME' => 'VIRUS_DETECTED',
			'ACTIVE' => 'Y',
			'SITE_ID' => 's1',
			'EMAIL_FROM' => '#DEFAULT_EMAIL_FROM#',
			'EMAIL_TO' => '#EMAIL#',
			'SUBJECT' => GetMessage('message_22_SUBJECT'),
			'MESSAGE' => GetMessage('message_22_MESSAGE'),
			'BODY_TYPE' => 'text',
			'BCC' => '',
			'REPLY_TO' => '',
			'CC' => '',
			'IN_REPLY_TO' => '',
			'PRIORITY' => '',
			'FIELD1_NAME' => '',
			'FIELD1_VALUE' => '',
			'FIELD2_NAME' => '',
			'FIELD2_VALUE' => '',
			'EVENT_TYPE' => GetMessage('message_22_EVENT_TYPE'),
			),

);
foreach($eventMessages as $eventMessage)
{
	$rsMess = CEventMessage::GetList($by="site_id", $order="desc", array('TYPE_ID' => $eventMessage['EVENT_NAME'], 'SUBJECT' => $eventMessage['SUBJECT']));
	if($arMess=$rsMess->GetNext())
	{		
		$onCurrentSite=false;
		$mesSites=array();
		$new =$arMess['ID'];
		if($arMess['SITE_ID']==WIZARD_SITE_ID || $arMess['LID']==WIZARD_SITE_ID)
			$onCurrentSite=true;
		else
		{
			$db_LID = CEventMessage::GetLang($arMess['ID']);
			while($arSite= $db_LID->GetNext())
			{			
				if($arSite['LID']==WIZARD_SITE_ID)
				{
					$onCurrentSite=true;
					break;
				}
				else
					$mesSites[]=$arSite['LID'];
			}
		}
		if(!$onCurrentSite && $arMess['MESSAGE']==$eventMessage['MESSAGE'])
		{
			$mesSites[]=WIZARD_SITE_ID;
			$res = $em->Update($arMess['ID'], array("LID"=>$mesSites));
		}
		elseif($onCurrentSite && $arMess['MESSAGE']!=$eventMessage['MESSAGE'])
		{
			$res = $em->Update($arMess['ID'], array("MESSAGE"=>$eventMessage['MESSAGE']));
		}
		elseif(!$onCurrentSite && $arMess['MESSAGE']!=$eventMessage['MESSAGE'])
		{
			$eventMessage["LID"]=array(WIZARD_SITE_ID);
			$new = $em->Add($eventMessage);	
		}				
	}
	else
	{
		$eventMessage["LID"]=array(WIZARD_SITE_ID);
		$new = $em->Add($eventMessage);		
	}
	
	if($eventMessage['EVENT_NAME'] == 'FEEDBACK_FORM' && $new)
	{
		CWizardUtil::ReplaceMacros(WIZARD_SITE_PATH.WIZARD_SITE_DIR."about/contacts/index.php", Array("FEEDBACK_EVENT_MES_ID" => $new));
	}	
}
?>