<?
global $MESS;
$MESS["S2U_MAIN_AUTO_SECTION"] = "Редирект создан автоматически при изменении символьного кода раздела: ID: #ID# инфоблока IBLOCK_ID: #IBLOCK_ID#";
$MESS["S2U_MAIN_AUTO_ELEMENT"] = "Редирект создан автоматически при изменении URL элемента: ID: #ID# инфоблока IBLOCK_ID: #IBLOCK_ID#";
$MESS["S2U_MAIN_AUTO_ELEMENT_DEACTIVATE"] = "Редирект создан автоматически при деактивации элемента: ID: #ID# инфоблока IBLOCK_ID: #IBLOCK_ID#";
$MESS["S2U_MAIN_AUTO_ELEMENT_ADD"] = "Деактивировался автоматически при добавлении нового элемента ID: #ID# инфоблока IBLOCK_ID: #IBLOCK_ID#";
$MESS["S2U_MAIN_AUTO_ELEMENT_DELETE"] = "Редирект создан автоматически при удалении элемента: ID: #ID# инфоблока IBLOCK_ID: #IBLOCK_ID#";
$MESS["S2U_MAIN_AUTO_SECTIONS_CNANGE"] = "Редирект создан автоматически при изменении разделов элемента: ID: #ID# инфоблока IBLOCK_ID: #IBLOCK_ID#";
$MESS["atl_license_expired"] = '<b>Ваша лицензия на Битрикс скоро истекает!</b> (активна лишь до #DATE#)<br/>У компании Атлант есть уникальное предложение &mdash; <a href="https://atlant2010.ru/services/prodlenie-1c-bitrix/?_openstat=c3RlcDJ1c2UucmVkaXJlY3RzO9C_0YDQvtC00LvQtdC90LjQtSDQu9C40YbQtdC90LfQuNC4O9GB0YHRi9C70LrQsDE7" target="_blank">продление лицензии с выгодой до 30%</a>.<br/><a href="https://atlant2010.ru/services/prodlenie-1c-bitrix/?_openstat=c3RlcDJ1c2UucmVkaXJlY3RzO9C_0YDQvtC00LvQtdC90LjQtSDQu9C40YbQtdC90LfQuNC4O9C30LDRh9C10Lwg0L_RgNC-0LTQu9C10LLQsNGC0Yw7" target="_blank">Зачем пролевать лицензию?</a><p style="text-align: center;"><a href="https://atlant2010.ru/services/prodlenie-1c-bitrix/?_openstat=c3RlcDJ1c2UucmVkaXJlY3RzO9C_0YDQvtC00LvQtdC90LjQtSDQu9C40YbQtdC90LfQuNC4O9C30LXQu9C10L3QsNGPINC60L3QvtC_0LrQsDs" target="_blank" class="adm-btn adm-btn-save">Продлить лицензию с выгодой до 30%</a></p>';
$MESS['atl_update_notify_1_2_5'] = 'В модуле «Редирект Мастер» обновилась логика создания автоматических редиректов. <br/>Все прежние настройки авторедиректов отключены! <br/>Активируйте авторедиректы <a href="/bitrix/admin/settings.php?mid=step2use.redirects" target="_blank">в новом интерфейсе настроек</a>.';
$MESS["atl_module_expired"] = 'У модуля <a href="https://atlant2010.ru/modules/redirekt-bitrix/" target="_blank">Редирект Мастер</a> <b>вышел срок пробной версии!</b><br/><span style="color: red;">Настроенные ранее редиректы больше не работают!</span><br/><a href="http://marketplace.1c-bitrix.ru/tobasket.php?ID=step2use.redirects" target="_blank">Приобрести полную версию</a> вы можете через Маркетплейс.<p style="text-align: center;"><a href="http://marketplace.1c-bitrix.ru/tobasket.php?ID=step2use.redirects" target="_blank" class="adm-btn adm-btn-save">Купить полную версию Редирект Мастера</a></p>Если у вас возникли вопросы или пожелания по модулю - <a href="mailto:mp@atlant2010.ru">обратитесь к разработчиками модуля</a> - мы вам обязательно поможем!';
?>
