<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Personalized recommendations");
?>
<div class="context-wrap">
<?$APPLICATION->IncludeComponent(
	"bitrix:catalog.bigdata.products",
	"al",
	array(
		"COMPONENT_TEMPLATE" => "al",
		"RCM_TYPE" => "bestsell",
		"ID" => "",
		"IBLOCK_TYPE" => "catalog",
		"IBLOCK_ID" => "#CATALOG_IBLOCK_ID#",
		"SHOW_FROM_SECTION" => "N",
		"SECTION_ID" => "",
		"SECTION_CODE" => "",
		"SECTION_ELEMENT_ID" => "",
		"SECTION_ELEMENT_CODE" => "",
		"DEPTH" => "",
		"HIDE_NOT_AVAILABLE" => "N",
		"SHOW_DISCOUNT_PERCENT" => "Y",
		"PRODUCT_SUBSCRIPTION" => "N",
		"SHOW_NAME" => "Y",
		"SHOW_IMAGE" => "Y",
		"MESS_BTN_BUY" => "Buy",
		"MESS_BTN_DETAIL" => "More",
		"MESS_BTN_SUBSCRIBE" => "Subscribe",
		"PAGE_ELEMENT_COUNT" => "20",
		"TEMPLATE_VIEW" => "showcase",
		"NOVELTY_TIME" => "720",
		"USE_FAVORITE" => "Y",
		"USE_SHARE" => "Y",
		"SHOW_ERROR_EMPTY_ITEMS" => "Y",
		"SHOW_PARENT" => "N",
		"SHOW_SECTION_URL" => "Y",
		"SECTION_PAGE_MORE_URL" => "",
		"USE_HOVER_POPUP" => "Y",
		"USE_SLIDER_MODE" => "N",
		"SOCIAL_SERVICES" => array(
			0 => "facebook",
			1 => "gplus",
			2 => "moimir",
			3 => "odnoklassniki",
			4 => "twitter",
			5 => "vkontakte",
			6 => "moikrug",
			7 => "",
		),
		"SOCIAL_SKIN" => "default",
		"SOCIAL_POPUP_TYPE" => "none",
		"DETAIL_URL" => "",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "3600",
		"CACHE_GROUPS" => "Y",
		"SHOW_OLD_PRICE" => "N",
		"PRICE_CODE" => array(
			0 => "BASE",
		),
		"SHOW_PRICE_COUNT" => "1",
		"PRICE_VAT_INCLUDE" => "N",
		"CONVERT_CURRENCY" => "N",
		"BASKET_URL" => "#SITE_DIR#personal/cart/",
		"ACTION_VARIABLE" => "action",
		"PRODUCT_ID_VARIABLE" => "id",
		"PRODUCT_QUANTITY_VARIABLE" => "",
		"ADD_PROPERTIES_TO_BASKET" => "N",
		"PRODUCT_PROPS_VARIABLE" => "prop",
		"PARTIAL_PRODUCT_PROPERTIES" => "N",
		"USE_PRODUCT_QUANTITY" => "Y",
		"SHOW_PRODUCTS_1" => "Y",
		"PROPERTY_CODE_1" => array(
			0 => "",
			1 => "",
		),
		"CART_PROPERTIES_1" => "",
		"ADDITIONAL_PICT_PROP_1" => "MORE_PHOTO",
		"LABEL_PROP_1" => "-",
		"ICON_NOVELTY_PROP_1" => "ICON_NOVELTY",
		"ICON_DEALS_PROP_1" => "ICON_DEALS",
		"ICON_DISCOUNT_PROP_1" => "ICON_DISCOUNT",
		"ICON_HITS_PROP_1" => "ICON_HIT",
		"PROPERTY_CODE_10" => array(
			0 => "",
			1 => "",
		),
		"CART_PROPERTIES_10" => array(
			0 => "undefined",
		),
		"ADDITIONAL_PICT_PROP_10" => "MORE_PHOTO",
		"OFFER_TREE_PROPS_10" => array(
			0 => "COLOR_DIRECTORY",
			1 => "COLOR2_DIRECTORY",
			2 => "STORAGE",
		),
		"OFFER_TREE_COLOR_PROPS_10" => array(
			0 => "COLOR_DIRECTORY",
			1 => "COLOR2_DIRECTORY",
		),
		"OFFER_TREE_BTN_PROPS" => array(
			0 => "-",
		),
		"SECTION_TITLE" => "",
		"USE_LIKES" => "Y",
		"POPUP_DETAIL_VARIABLE" => "",
		"SOCIAL_COUNTER" => "N",
		"SOCIAL_COPY" => "first",
		"SOCIAL_LIMIT" => "",
		"SOCIAL_SIZE" => "m",
		"TEMPLATE_AJAXID" => "ajaxpages_catalog_identifier",
		"PREVIEW_TRUNCATE_LEN" => "",
		"DISPLAY_COMPARE" => "N",
		"SHOW_PRODUCTS_#CATALOG_IBLOCK_ID#" => "Y",
		"PROPERTY_CODE_#CATALOG_IBLOCK_ID#" => array(
			0 => "",
			1 => "",
		),
		"CART_PROPERTIES_#CATALOG_IBLOCK_ID#" => array(
		),
		"ADDITIONAL_PICT_PROP_#CATALOG_IBLOCK_ID#" => "MORE_PHOTO",
		"LABEL_PROP_#CATALOG_IBLOCK_ID#" => "RECOMENDED",
		"BRAND_PROP_#CATALOG_IBLOCK_ID#" => "MAKER",
		"CATALOG_FILTER_NAME_#CATALOG_IBLOCK_ID#" => "arrFilter",
		"LIKES_COUNT_PROP_#CATALOG_IBLOCK_ID#" => "LIKES_COUNT",
		"ICON_NOVELTY_PROP_#CATALOG_IBLOCK_ID#" => "NEW_ICON",
		"ICON_DEALS_PROP_#CATALOG_IBLOCK_ID#" => "ACTION_ICON",
		"ICON_DISCOUNT_PROP_#CATALOG_IBLOCK_ID#" => "DISCOUNT_ICON",
		"ICON_MEN_PROP_#CATALOG_IBLOCK_ID#" => "FOR_MEN",
		"ICON_WOMEN_PROP_#CATALOG_IBLOCK_ID#" => "FOR_WOMEN",
		"PROPERTY_CODE_#OFFERS_IBLOCK_ID#" => array(
			0 => "",
			1 => "",
		),
		"CART_PROPERTIES_#OFFERS_IBLOCK_ID#" => array(
		),
		"ADDITIONAL_PICT_PROP_#OFFERS_IBLOCK_ID#" => "SKU_MORE_PHOTO",
		"OFFER_TREE_PROPS_#OFFERS_IBLOCK_ID#" => array(
		),
		"OFFER_TREE_COLOR_PROPS_#OFFERS_IBLOCK_ID#" => array(
		),
		"LINE_ELEMENT_COUNT" => "5"
	),
	false
);?>
</div>
<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>