<?
$aMenuLinks = Array(
	Array(
		"Образы", 
		"#SITE_DIR#imageries/",
		Array(), 
		Array("MAIN_MENU"=>"1"), 
		"" 
	),
	Array(
		"Блог",
        "#SITE_DIR#blogs/",
		Array(), 
		Array("MAIN_MENU"=>"1"), 
		"" 
	),
    /*Array(
        "Контакты",
        "/about/contacts/",
        Array(),
        Array("MAIN_MENU"=>"1"),
        ""
    )*/
);
?>