<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Вопросы и ответы");
?><?$APPLICATION->IncludeComponent(
	"bitrix:news.list",
	"faq",
	Array(
		"ACTIVE_DATE_FORMAT" => "d.m.Y",
		"ADD_SECTIONS_CHAIN" => "Y",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "A",
		"CHECK_DATES" => "Y",
		"COMPONENT_TEMPLATE" => "faq",
		"DETAIL_URL" => "",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"DISPLAY_TOP_PAGER" => "N",
		"FIELD_CODE" => array(0=>"",1=>"",),
		"FILTER_NAME" => "",
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"IBLOCK_ID" => "#IBLOCK_ID_services_faq#",
		"IBLOCK_TYPE" => "services",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "Y",
		"INCLUDE_SUBSECTIONS" => "Y",
		"MESSAGE_404" => "",
		"NEWS_COUNT" => "12",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => "monopoly2",
		"PAGER_TITLE" => "Новости",
		"PARENT_SECTION" => "",
		"PARENT_SECTION_CODE" => "",
		"PREVIEW_TRUNCATE_LEN" => "",
		"PROPERTY_CODE" => array(0=>"FAQ_TYPE",1=>"",),
		"RSFLYAWAY_PROP_FAQ_TYPE" => "FAQ_TYPE",
		"RSMONOPOLY_BLOCK_NAME_IS_LINK" => "N",
		"RSMONOPOLY_PROP_FAQ_TYPE" => "FAQ_TYPE",
		"RSMONOPOLY_SHOW_BLOCK_NAME" => "N",
		"SET_BROWSER_TITLE" => "Y",
		"SET_LAST_MODIFIED" => "N",
		"SET_META_DESCRIPTION" => "Y",
		"SET_META_KEYWORDS" => "Y",
		"SET_STATUS_404" => "N",
		"SET_TITLE" => "Y",
		"SHOW_404" => "N",
		"SORT_BY1" => "ACTIVE_FROM",
		"SORT_BY2" => "SORT",
		"SORT_ORDER1" => "DESC",
		"SORT_ORDER2" => "ASC"
	)
);?><div class="row"><div class="col col-md-9"><a name="addquestion"></a><?$APPLICATION->IncludeComponent(
	"rsflyaway:forms",
	"flyaway",
	array(
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"CACHE_TIME" => "3600",
		"CACHE_TYPE" => "A",
		"EMAIL_TO" => "",
		"EVENT_TYPE" => "RS_FLYAWAY_FAQ",
		"FORM_DESCRIPTION" => "Пожалуйста задайте ваш вопрос, используя форму. Чтобы получить ответ на электронную почту или по телефону, пожалуйста укажите ваши контактные данные.",
		"FORM_TITLE" => "Задать вопрос",
		"MESSAGE_AGREE" => "Спасибо, ваша заявка принята!",
		"REQUIRED_FIELDS" => array(
			0 => "RS_NAME",
			1 => "RS_TEXTAREA",
		),
		"RS_MONOPOLY_EXT_FIELDS_COUNT" => "0",
		"SHOW_FIELDS" => array(
			0 => "RS_NAME",
			1 => "RS_PHONE",
			2 => "RS_ORGANISATION_NAME",
			3 => "RS_EMAIL",
			4 => "RS_TEXTAREA",
		),
		"USE_CAPTCHA" => "Y",
		"COMPONENT_TEMPLATE" => "flyaway",
		"RS_FLYAWAY_EXT_FIELDS_COUNT" => "0"
	),
	false
);?></div></div><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>
