<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Пресса о нас");
?><?$APPLICATION->IncludeComponent(
	"bitrix:news",
	"flyaway",
	array(
		"IBLOCK_TYPE" => "services",
		"IBLOCK_ID" => "#IBLOCK_ID_services_press_about_us#",
		"NEWS_COUNT" => "20",
		"USE_SEARCH" => "N",
		"USE_RSS" => "N",
		"USE_RATING" => "N",
		"USE_CATEGORIES" => "N",
		"USE_FILTER" => "N",
		"SORT_BY1" => "ACTIVE_FROM",
		"SORT_ORDER1" => "DESC",
		"SORT_BY2" => "SORT",
		"SORT_ORDER2" => "ASC",
		"CHECK_DATES" => "Y",
		"SEF_MODE" => "Y",
		"SEF_FOLDER" => "#SITE_DIR#about/press_center/press_about/",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"AJAX_OPTION_HISTORY" => "N",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "36000000",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"SET_STATUS_404" => "N",
		"SET_TITLE" => "Y",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"ADD_SECTIONS_CHAIN" => "N",
		"ADD_ELEMENT_CHAIN" => "Y",
		"USE_PERMISSIONS" => "N",
		"PREVIEW_TRUNCATE_LEN" => "",
		"LIST_ACTIVE_DATE_FORMAT" => "d.m.Y",
		"LIST_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"LIST_PROPERTY_CODE" => array(
			0 => "PUBLISHER_NAME",
			1 => "PUBLISHER_DESCR",
			2 => "",
		),
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"RSFLYAWAY_LIST_TEMPLATES_LIST" => "news",
		"RSFLYAWAY_SHOW_BLOCK_NAME_LIST" => "N",
		"DISPLAY_NAME" => "Y",
		"META_KEYWORDS" => "-",
		"META_DESCRIPTION" => "-",
		"BROWSER_TITLE" => "-",
		"DETAIL_ACTIVE_DATE_FORMAT" => "d.m.Y",
		"DETAIL_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"DETAIL_PROPERTY_CODE" => array(
			0 => "PUBLISHER_NAME",
			1 => "PUBLISHER_DESCR",
			2 => "",
		),
		"RSFLYAWAY_DETAIL_TEMPLATES" => "news-side",
		"RSFLYAWAY_LIST_TEMPLATES_DETAIL" => "news",
		"RSFLYAWAY_SHOW_BLOCK_NAME_DETAIL" => "N",
		"DETAIL_DISPLAY_TOP_PAGER" => "N",
		"DETAIL_DISPLAY_BOTTOM_PAGER" => "Y",
		"DETAIL_PAGER_TITLE" => "Страница",
		"DETAIL_PAGER_TEMPLATE" => "",
		"DETAIL_PAGER_SHOW_ALL" => "Y",
		"PAGER_TEMPLATE" => "flyaway",
		"DISPLAY_TOP_PAGER" => "N",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"PAGER_TITLE" => "Новости",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"RSFLYAWAY_BLOCK_NAME_IS_LINK_LIST" => "N",
		"RSFLYAWAY_LIST_TEMPLATES_DETAIL_USE" => "N",
		"RSFLYAWAY_USE_OWL_LIST" => "N",
		"RSFLYAWAY_COLS_IN_ROW_LIST" => "12",
		"RSFLYAWAY_PROP_PUBLISHER_NAME_LIST" => "PUBLISHER_NAME",
		"RSFLYAWAY_PROP_PUBLISHER_LINK_LIST" => "PUBLISHER_LINK",
		"RSFLYAWAY_PROP_PUBLISHER_BLANK_LIST" => "Y",
		"RSFLYAWAY_PROP_PUBLISHER_DESCR_LIST" => "PUBLISHER_DESCR",
		"COMPONENT_TEMPLATE" => "flyaway",
		"DETAIL_SET_CANONICAL_URL" => "N",
		"RSFLYAWAY_DETAIL_USE_SUBSCRIBE" => "Y",
		"RSFLYAWAY_DETAIL_SUBSCRIBE_PAGE" => "#SITE_DIR#about/press_center/subscribe/",
		"RSFLYAWAY_DETAIL_SUBSCRIBE_NOTE" => "",
		"USE_REVIEW" => "N",
		"SET_LAST_MODIFIED" => "N",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"SHOW_404" => "N",
		"MESSAGE_404" => "",
		"SEF_URL_TEMPLATES" => array(
			"news" => "",
			"section" => "",
			"detail" => "#ELEMENT_CODE#/",
		)
	),
	false
);?><br><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>
