CREATE TABLE IF NOT EXISTS `b_wd_reviews2_fields` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) NOT NULL,
  `CODE` varchar(255) NOT NULL,
  `DESCRIPTION` text NOT NULL,
  `SORT` int(11) NOT NULL DEFAULT '100',
  `TYPE` varchar(255) NOT NULL,
  `REQUIRED` char(1) NOT NULL,
  `HIDDEN` char(1) NOT NULL,
  `INTERFACE_ID` int(11) NOT NULL,
  `PARAMS` longtext NOT NULL,
  `DATE_CREATED` datetime NOT NULL,
  `DATE_MODIFIED` datetime NOT NULL,
  PRIMARY KEY (`ID`)
);

CREATE TABLE IF NOT EXISTS `b_wd_reviews2_interface` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) NOT NULL,
  `SORT` int(11) NOT NULL DEFAULT '100',
  `DESCRIPTION` text NOT NULL,
  `URL` varchar(255) NOT NULL,
  `JQUERY_INIT_URL` text NOT NULL,
  `PRE_MODERATION` char(1) NOT NULL,
  `ALLOW_UNREGISTERED` char(1) NOT NULL,
  `CAPTCHA_MODE` char(1) NOT NULL,
  `SUCCESS_MESSAGE` text NOT NULL,
  `DATE_CREATED` datetime NOT NULL,
  `DATE_MODIFIED` datetime NOT NULL,
  `DATE_LAST_REVIEW` datetime NOT NULL,
  `RATING_IS_REQUIRED` char(1) NOT NULL,
  `RATING_STARS_COUNT` tinyint(4) NOT NULL DEFAULT '5',
  `RATING_STARS_COUNT_DEF` tinyint(4) NOT NULL DEFAULT '5',
  `RATING_STARS_HINTS` varchar(255) NOT NULL,
  `RATING_IMG_ACTIVE` varchar(255) NOT NULL,
  `RATING_IMG_HALF` varchar(255) NOT NULL,
  `RATING_IMG_INACTIVE` varchar(255) NOT NULL,
  `RATING_IMG_RANGE` text NOT NULL,
  `RATING_HALF_SHOW` char(1) NOT NULL,
  `RATING_SHOW_SPACES` char(1) NOT NULL,
  `RATING_USE_RANGE` char(1) NOT NULL,
  `REVIEWS_COUNT` int(11) NOT NULL DEFAULT '0',
  `EMAIL_ON_ADD` char(1) NOT NULL,
  `EMAIL_ON_ANSWER` char(1) NOT NULL,
  `EMAIL_ON_MODERATED` char(1) NOT NULL,
  PRIMARY KEY (`ID`)
);

CREATE TABLE IF NOT EXISTS `b_wd_reviews2_ratings` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) NOT NULL,
  `SORT` int(11) NOT NULL DEFAULT '100',
  `DESCRIPTION` text NOT NULL,
  `PARTICIPATES` char(1) NOT NULL,
  `INTERFACE_ID` int(11) NOT NULL,
  `DATE_CREATED` datetime NOT NULL,
  `DATE_MODIFIED` datetime NOT NULL,
  PRIMARY KEY (`ID`)
);

CREATE TABLE IF NOT EXISTS `b_wd_reviews2_ratingsvalues` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `REVIEW_ID` int(11) NOT NULL,
  `RATING_ID` int(11) NOT NULL,
  `VALUE` int(11) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ONE_RATING_FOR_REVIEW` (`REVIEW_ID`,`RATING_ID`)
);

CREATE TABLE IF NOT EXISTS `b_wd_reviews2_reviews` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `INTERFACE_ID` int(11) NOT NULL,
  `TARGET` varchar(255) NOT NULL,
  `USER_ID` int(11) NOT NULL,
  `DATE_CREATED` datetime NOT NULL,
  `DATE_MODIFIED` datetime NOT NULL,
  `DATE_VOTING` datetime NOT NULL,
  `MODERATED` char(1) NOT NULL,
  `ANSWER` text NOT NULL,
  `ANSWER_USER_ID` int(11) NOT NULL,
  `DATE_ANSWER` datetime NOT NULL,
  `USER_ANSWER_NOTIFIED` char(1) NOT NULL,
  `USER_MODERATED_NOTIFIED` char(1) NOT NULL,
  `VOTES_Y` int(11) NOT NULL DEFAULT '0',
  `VOTES_N` int(11) NOT NULL DEFAULT '0',
  `VOTE_RESULT` int(11) NOT NULL DEFAULT '0',
  `DATA_FIELDS` text NOT NULL,
  `DATA_RATINGS` text NOT NULL,
  `EXTERNAL_ID` varchar(255) NOT NULL,
  PRIMARY KEY (`ID`)
);

CREATE TABLE IF NOT EXISTS `b_wd_reviews2_voting` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `USER_ID` int(11) NOT NULL,
  `USER_IP` int(10) unsigned NOT NULL,
  `REVIEW_ID` int(11) NOT NULL,
  `VALUE` tinyint(4) NOT NULL,
  `DATE_CREATED` datetime NOT NULL,
  PRIMARY KEY (`ID`)
);

CREATE TABLE IF NOT EXISTS `b_webdebug_reviews` (
  `ID` int(18) NOT NULL AUTO_INCREMENT,
  `IBLOCK_ID` int(18) NOT NULL,
  `ELEMENT_ID` int(18) NOT NULL,
  `MODERATED` enum('Y','N') NOT NULL DEFAULT 'Y',
  `SITE_ID` char(2) NOT NULL,
  `USER_ID` int(18) DEFAULT NULL,
  `NAME` varchar(255) DEFAULT NULL,
  `EMAIL` varchar(255) DEFAULT NULL,
  `EMAIL_PUBLIC` enum('Y','N') NOT NULL DEFAULT 'N',
  `WWW` varchar(255) DEFAULT NULL,
  `DATETIME` datetime NOT NULL,
  `TEXT_PLUS` text,
  `TEXT_MINUS` text,
  `TEXT_COMMENTS` text,
  `VOTE_0` int(18) DEFAULT NULL,
  `VOTE_1` int(18) DEFAULT NULL,
  `VOTE_2` int(18) DEFAULT NULL,
  `VOTE_3` int(18) DEFAULT NULL,
  `VOTE_4` int(18) DEFAULT NULL,
  `VOTE_5` int(18) DEFAULT NULL,
  `VOTE_6` int(18) DEFAULT NULL,
  `VOTE_7` int(18) DEFAULT NULL,
  `VOTE_8` int(18) DEFAULT NULL,
  `VOTE_9` int(18) DEFAULT NULL,
  PRIMARY KEY (`ID`)
);