<?
$arTooltips = array(
	"IBLOCK_TYPE" => GetMessage("IBLOCK_TYPE_TIP"),
	"SITE_LIST" => GetMessage("SITE_LIST_TIP"),
	"INTERVAL" => GetMessage("INTERVAL_TIP"),
	"GROUP_PERMISSIONS" => GetMessage("GROUP_PERMISSIONS_TIP"),
	"ELEMENT_ACTION" => GetMessage("ELEMENT_ACTION_TIP"),
	"SECTION_ACTION" => GetMessage("SECTION_ACTION_TIP"),
	"FILE_SIZE_LIMIT" => GetMessage("FILE_SIZE_LIMIT_TIP"),
	"USE_CRC" => GetMessage("USE_CRC_TIP"),
	"USE_ZIP" => GetMessage("USE_ZIP_TIP"),
	"GENERATE_PREVIEW" => GetMessage("GENERATE_PREVIEW_TIP"),
	"PREVIEW_WIDTH" => GetMessage("PREVIEW_WIDTH_TIP"),
	"PREVIEW_HEIGHT" => GetMessage("PREVIEW_HEIGHT_TIP"),
	"DETAIL_RESIZE" => GetMessage("DETAIL_RESIZE_TIP"),
	"DETAIL_WIDTH" => GetMessage("DETAIL_WIDTH_TIP"),
	"DETAIL_HEIGHT" => GetMessage("DETAIL_HEIGHT_TIP"),
	"USE_OFFERS" => GetMessage("USE_OFFERS_TIP"),
);
?>