<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Catalog");

$APPLICATION->IncludeComponent(
	"bitrix:catalog",
	"al",
	array(
		"COMPONENT_TEMPLATE" => "al",
		"IBLOCK_TYPE" => "catalog",
		"IBLOCK_ID" => "#CATALOG_IBLOCK_ID#",
		"HIDE_NOT_AVAILABLE" => "N",
		"SEF_MODE" => "Y",
		"SEF_FOLDER" => "#SITE_DIR#catalog/",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "N",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "36000000",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"USE_MAIN_ELEMENT_SECTION" => "Y",
		"SET_LAST_MODIFIED" => "Y",
		"SET_TITLE" => "Y",
		"ADD_SECTIONS_CHAIN" => "Y",
		"ADD_ELEMENT_CHAIN" => "Y",
		"ICON_MEN_PROP" => "FOR_MEN",
		"ICON_WOMEN_PROP" => "FOR_WOMEN",
		"ICON_NOVELTY_PROP" => "NEW_ICON",
		"NOVELTY_TIME" => "720",
		"ICON_DISCOUNT_PROP" => "DISCOUNT_ICON",
		"ICON_DEALS_PROP" => "ACTION_ICON",
		"ADDITIONAL_PICT_PROP" => "MORE_PHOTO",
		"ARTICLE_PROP" => "CML2_ARTICKLE",
		"DELIVERY_PROP" => "DOSTAVKA_INFO",
		"BRAND_PROP" => "BRANDS",
		"BRAND_LOGO_PROP" => "-",
		"ACCESSORIES_PROP" => "ACCESSORIES",
		"USE_QUANTITY_AND_STORES" => "Y",
		"LIKES_COUNT_PROP" => "LIKES_COUNT",
		"USE_LIKES" => "Y",
		"USE_SHARE" => "Y",
		"COUNT_RESULT_NOT_CATALOG" => "10",
		"BRAND_IBLOCK_ID" => "49",
		"BRAND_IBLOCK_BRAND_PROP" => "BRAND",
		"USE_FILTER" => "Y",
		"FILTER_NAME" => "",
		"FILTER_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"FILTER_PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"FILTER_PRICE_CODE" => array(
			0 => "BASE",
		),
		"FILTER_OFFERS_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"FILTER_OFFERS_PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"FILTER_USE_AJAX" => "Y",
		"FILTER_SCROLL_PROPS" => array(
			0 => "BRANDS",
		),
		"FILTER_SEARCH_PROPS" => array(
			0 => "BRANDS",
		),
		"FILTER_PRICES_GROUPED" => array(
		),
		"FILTER_PRICES_GROUPED_FOR" => "products",
		"OFFER_FILTER_SCROLL_PROPS" => array(
		),
		"OFFER_FILTER_SEARCH_PROPS" => array(
		),
		"USE_REVIEW" => "Y",
		"MESSAGES_PER_PAGE" => "10",
		"USE_CAPTCHA" => "Y",
		"REVIEW_AJAX_POST" => "Y",
		"PATH_TO_SMILE" => "/bitrix/images/forum/smile/",
		"FORUM_ID" => "#FORUM_ID#",
		"URL_TEMPLATES_READ" => "",
		"SHOW_LINK_TO_FORUM" => "Y",
		"ACTION_VARIABLE" => "action",
		"PRODUCT_ID_VARIABLE" => "id",
		"USE_COMPARE" => "Y",
		"COMPARE_NAME" => "CATALOG_COMPARE_LIST",
		"COMPARE_FIELD_CODE" => array(
			0 => "PREVIEW_PICTURE",
			1 => "DETAIL_PICTURE",
			2 => "",
		),
		"COMPARE_PROPERTY_CODE" => array(
			0 => "CML2_ARTICKLE",
			1 => "BRANDS",
			2 => "YEARS_LIMIT",
			3 => "TEST_COLOR",
			4 => "YEAR",
			5 => "RAMA",
			6 => "VILKA",
			7 => "OBODA",
			8 => "TORMOZA",
			9 => "POSHIV",
			10 => "VOZRASTNAYA_GRUPPA",
			11 => "DOSTAVKA_INFO",
			12 => "TEST_MULTI_PROP",
			13 => "DOSTAVKA",
			14 => "",
		),
		"COMPARE_OFFERS_FIELD_CODE" => array(
			0 => "PREVIEW_PICTURE",
			1 => "DETAIL_PICTURE",
			2 => "",
		),
		"COMPARE_OFFERS_PROPERTY_CODE" => array(
			0 => "SKU_COLOR_2",
			1 => "SKU_COLOR_1",
			2 => "SKU_COLOR",
			3 => "SKU_SIZE",
			4 => "CML2_ARTICKLE",
			5 => "SKU_TKAN",
			6 => "SKU_COLOR_ZERO",
			7 => "",
		),
		"COMPARE_ELEMENT_SORT_FIELD" => "sort",
		"COMPARE_ELEMENT_SORT_ORDER" => "asc",
		"DISPLAY_ELEMENT_SELECT_BOX" => "N",
		"PRICE_CODE" => array(
			0 => "BASE",
		),
		"USE_PRICE_COUNT" => "N",
		"SHOW_PRICE_COUNT" => "1",
		"PRICE_VAT_INCLUDE" => "N",
		"PRICE_VAT_SHOW_VALUE" => "N",
		"CONVERT_CURRENCY" => "Y",
		"CURRENCY_ID" => "RUB",
		"SHOW_OLD_PRICE" => "Y",
		"SHOW_DISCOUNT_PERCENT" => "Y",
		"BASKET_URL" => "#SITE_DIR#personal/cart/",
		"USE_PRODUCT_QUANTITY" => "Y",
		"PRODUCT_QUANTITY_VARIABLE" => "",
		"ADD_PROPERTIES_TO_BASKET" => "N",
		"PRODUCT_PROPS_VARIABLE" => "prop",
		"PARTIAL_PRODUCT_PROPERTIES" => "N",
		"PRODUCT_PROPERTIES" => array(
		),
		"OFFERS_CART_PROPERTIES" => array(
		),
		"SHOW_TOP_ELEMENTS" => "N",
		"SECTION_COUNT_ELEMENTS" => "Y",
		"SECTION_TOP_DEPTH" => "4",
		"PAGE_ELEMENT_COUNT" => "30",
		"LINE_ELEMENT_COUNT" => "3",
		"ELEMENT_SORT_FIELD" => "sort",
		"ELEMENT_SORT_ORDER" => "asc",
		"ELEMENT_SORT_FIELD2" => "id",
		"ELEMENT_SORT_ORDER2" => "desc",
		"LIST_PROPERTY_CODE" => array(
			0 => "BRANDS",
			1 => "",
		),
		"INCLUDE_SUBSECTIONS" => "A",
		"LIST_META_KEYWORDS" => "-",
		"LIST_META_DESCRIPTION" => "-",
		"LIST_BROWSER_TITLE" => "-",
		"SECTION_BACKGROUND_IMAGE" => "-",
		"LIST_OFFERS_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"LIST_OFFERS_PROPERTY_CODE" => array(
			0 => "SKU_COLOR_2",
			1 => "SKU_COLOR_1",
			2 => "SKU_COLOR",
			3 => "SKU_SIZE",
			4 => "SKU_TKAN",
			5 => "SKU_COLOR_ZERO",
			6 => "",
		),
		"LIST_OFFERS_LIMIT" => "0",
		"SHOW_SECTION_PICTURE" => "Y",
		"POPUP_DETAIL_VARIABLE" => "ON_LUPA",
		"ERROR_EMPTY_ITEMS" => "Y",
		"SHOW_SECTION_DESCRIPTION" => "top",
		"SECTION_PICTURE_WIDTH" => "",
		"SECTION_PICTURE_HEIGHT" => "",
		"DETAIL_PROPERTY_CODE" => array(
			0 => "CML2_ARTICKLE",
			1 => "FOR_MEN",
			2 => "FOR_WOMEN",
			3 => "BRANDS",
			4 => "YEARS_LIMIT",
			5 => "TEST_COLOR",
			6 => "YEAR",
			7 => "RAMA",
			8 => "VILKA",
			9 => "OBODA",
			10 => "TORMOZA",
			11 => "POSHIV",
			12 => "VOZRASTNAYA_GRUPPA",
			13 => "DOSTAVKA_INFO",
			14 => "TEST_MULTI_PROP",
			15 => "DOSTAVKA",
			16 => "",
		),
		"DETAIL_META_KEYWORDS" => "-",
		"DETAIL_META_DESCRIPTION" => "-",
		"DETAIL_BROWSER_TITLE" => "-",
		"DETAIL_SET_CANONICAL_URL" => "N",
		"SECTION_ID_VARIABLE" => "SECTION_ID",
		"DETAIL_CHECK_SECTION_ID_VARIABLE" => "N",
		"DETAIL_BACKGROUND_IMAGE" => "-",
		"SHOW_DEACTIVATED" => "N",
		"DETAIL_OFFERS_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"DETAIL_OFFERS_PROPERTY_CODE" => array(
			0 => "SKU_COLOR_2",
			1 => "SKU_COLOR_1",
			2 => "SKU_COLOR",
			3 => "SKU_SIZE",
			4 => "CML2_ARTICKLE",
			5 => "SKU_TKAN",
			6 => "SKU_COLOR_ZERO",
			7 => "",
		),
		"LINKED_ITEMS_PROPS" => array(
			0 => "ACCESSORIES",
		),
		"TAB_IBLOCK_PROPS" => array(
			0 => "DOCS",
			1 => "ACCESSORIES",
			2 => "",
		),
		"SIZE_TABLE_USER_FIELD_CODE" => "UF_SIZE_TABLE",
		"USE_KREDIT" => "Y",
		"KREDIT_URL" => "#SITE_DIR#kredit/",
		"USE_PICTURE_ZOOM" => "Y",
		"USE_PICTURE_GALLERY" => "Y",
		"LINK_IBLOCK_TYPE" => "",
		"LINK_IBLOCK_ID" => "",
		"LINK_PROPERTY_SID" => "",
		"LINK_ELEMENTS_URL" => "link.php?PARENT_ELEMENT_ID=#ELEMENT_ID#",
		"USE_ALSO_BUY" => "Y",
		"ALSO_BUY_ELEMENT_COUNT" => "5",
		"ALSO_BUY_MIN_BUYES" => "1",
		"USE_GIFTS_DETAIL" => "Y",
		"USE_GIFTS_SECTION" => "N",
		"USE_GIFTS_MAIN_PR_SECTION_LIST" => "Y",
		"GIFTS_DETAIL_PAGE_ELEMENT_COUNT" => "3",
		"GIFTS_DETAIL_HIDE_BLOCK_TITLE" => "N",
		"GIFTS_DETAIL_BLOCK_TITLE" => "Choose one of the gifts",
		"GIFTS_DETAIL_TEXT_LABEL_GIFT" => "Gift",
		"GIFTS_SHOW_DISCOUNT_PERCENT" => "Y",
		"GIFTS_SHOW_OLD_PRICE" => "Y",
		"GIFTS_SHOW_NAME" => "Y",
		"GIFTS_SHOW_IMAGE" => "Y",
		"GIFTS_MESS_BTN_BUY" => "Choose",
		"GIFTS_MAIN_PRODUCT_DETAIL_PAGE_ELEMENT_COUNT" => "3",
		"GIFTS_MAIN_PRODUCT_DETAIL_HIDE_BLOCK_TITLE" => "N",
		"GIFTS_MAIN_PRODUCT_DETAIL_BLOCK_TITLE" => "Select one of the items to get a gift",
		"USE_STORE" => "Y",
		"STORES" => array(
			0 => "1",
			1 => "2",
		),
		"USE_MIN_AMOUNT" => "Y",
		"USER_FIELDS" => array(
			0 => "",
			1 => "",
		),
		"FIELDS" => array(
			0 => "",
			1 => "",
		),
		"MIN_AMOUNT" => "10",
		"SHOW_EMPTY_STORE" => "Y",
		"SHOW_GENERAL_STORE_INFORMATION" => "N",
		"STORE_PATH" => "#SITE_DIR#store/#store_id#",
		"MAIN_TITLE" => "Availability",
		"OFFERS_SORT_FIELD" => "sort",
		"OFFERS_SORT_ORDER" => "asc",
		"OFFERS_SORT_FIELD2" => "id",
		"OFFERS_SORT_ORDER2" => "desc",
		"OFFER_ADDITIONAL_PICT_PROP" => "SKU_MORE_PHOTO",
		"OFFER_ARTICLE_PROP" => "-",
		"OFFER_TREE_PROPS" => array(
			0 => "SKU_COLOR_2",
			1 => "SKU_COLOR_1",
			2 => "SKU_COLOR",
			3 => "SKU_SIZE",
			4 => "SKU_TKAN",
			5 => "SKU_COLOR_ZERO",
		),
		"OFFER_TREE_COLOR_PROPS" => array(
			0 => "SKU_COLOR_2",
			1 => "SKU_COLOR_1",
			2 => "SKU_COLOR",
			3 => "SKU_COLOR_ZERO",
		),
		"OFFER_TREE_BTN_PROPS" => array(
			0 => "SKU_SIZE",
		),
		"USE_BIG_DATA" => "Y",
		"BIG_DATA_RCM_TYPE" => "bestsell",
		"PAGER_TEMPLATE" => "al",
		"DISPLAY_TOP_PAGER" => "Y",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"PAGER_TITLE" => "Goods",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_BASE_LINK_ENABLE" => "Y",
		"PAGER_BASE_LINK" => "",
		"PAGER_PARAMS_NAME" => "arrPager",
		"TEMPLATE_AJAXID" => "catalog",
		"USE_AJAXPAGES" => "Y",
		"SET_STATUS_404" => "Y",
		"SHOW_404" => "Y",
		"FILE_404" => "",
		"USE_ELEMENT_COUNTER" => "Y",
		"DISABLE_INIT_JS_IN_COMPONENT" => "Y",
		"DETAIL_SET_VIEWED_IN_COMPONENT" => "N",
		"PREVIEW_TRUNCATE_LEN" => "128",
		"USE_BUY1CLICK" => "Y",
		"LIST_SOCIAL_SERVICES" => array(
			0 => "facebook",
			1 => "gplus",
			2 => "odnoklassniki",
			3 => "telegram",
			4 => "twitter",
			5 => "viber",
			6 => "vkontakte",
			7 => "whatsapp",
			8 => "",
		),
		"DETAIL_SOCIAL_SERVICES" => array(
			0 => "facebook",
			1 => "gplus",
			2 => "odnoklassniki",
			3 => "telegram",
			4 => "twitter",
			5 => "viber",
			6 => "vkontakte",
			7 => "whatsapp",
			8 => "",
		),
		"SOCIAL_COUNTER" => "Y",
		"SOCIAL_COPY" => "first",
		"SOCIAL_LIMIT" => "",
		"SOCIAL_SIZE" => "m",
		"SEF_URL_TEMPLATES" => array(
			"sections" => "",
			"section" => "#SECTION_CODE_PATH#/",
			"element" => "#SECTION_CODE_PATH#/#ELEMENT_CODE#/",
			"compare" => "compare/?action=#ACTION_CODE#",
			"smart_filter" => "#SECTION_CODE_PATH#/filter/#SMART_FILTER_PATH#/apply/",
		),
		"VARIABLE_ALIASES" => array(
			"compare" => array(
				"ACTION_CODE" => "action",
			),
		)
	),
	false
);
?><?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>
