<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Проекты");
?><?$APPLICATION->IncludeComponent(
	"bitrix:news.list",
	"services_main",
	array(
		"ACTIVE_DATE_FORMAT" => "d.m.Y",
		"ADD_SECTIONS_CHAIN" => "N",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "A",
		"CHECK_DATES" => "Y",
		"DETAIL_URL" => "",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"DISPLAY_TOP_PAGER" => "N",
		"FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"FILTER_NAME" => "",
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"IBLOCK_ID" => "#IBLOCK_ID_projects_finished#",
		"IBLOCK_TYPE" => "projects",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"INCLUDE_SUBSECTIONS" => "Y",
		"MESSAGE_404" => "",
		"NEWS_COUNT" => "12",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => "flyaway",
		"PAGER_TITLE" => "Новости",
		"PARENT_SECTION" => "",
		"PARENT_SECTION_CODE" => "",
		"PREVIEW_TRUNCATE_LEN" => "",
		"PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"RSFLYAWAY_BLOCK_NAME_IS_LINK" => "Y",
		"RSFLYAWAY_COLS_IN_ROW" => "3",
		"RSFLYAWAY_SHOW_BLOCK_NAME" => "Y",
		"RSFLYAWAY_USE_OWL" => "Y",
		"RSMONOPOLY_BLOCK_NAME_IS_LINK" => "Y",
		"RSMONOPOLY_OWL_CHANGE_DELAY" => "8000",
		"RSMONOPOLY_OWL_CHANGE_SPEED" => "2000",
		"RSMONOPOLY_OWL_PC" => "3",
		"RSMONOPOLY_OWL_PHONE" => "1",
		"RSMONOPOLY_OWL_TABLET" => "2",
		"RSMONOPOLY_SHOW_BLOCK_NAME" => "Y",
		"RSMONOPOLY_USE_OWL" => "Y",
		"SET_BROWSER_TITLE" => "N",
		"SET_LAST_MODIFIED" => "N",
		"SET_META_DESCRIPTION" => "N",
		"SET_META_KEYWORDS" => "N",
		"SET_STATUS_404" => "N",
		"SET_TITLE" => "N",
		"SHOW_404" => "N",
		"SORT_BY1" => "ACTIVE_FROM",
		"SORT_BY2" => "SORT",
		"SORT_ORDER1" => "DESC",
		"SORT_ORDER2" => "ASC",
		"COMPONENT_TEMPLATE" => "services_main",
		"RSFLYAWAY_OWL_CHANGE_SPEED" => "2000",
		"RSFLYAWAY_OWL_CHANGE_DELAY" => "8000",
		"RSFLYAWAY_OWL_PHONE" => "1",
		"RSFLYAWAY_OWL_TABLET" => "2",
		"RSFLYAWAY_OWL_PC" => "4"
	),
	false
);?><br>
 <?$APPLICATION->IncludeComponent(
	"bitrix:news.list",
	"services_main",
	array(
		"ACTIVE_DATE_FORMAT" => "d.m.Y",
		"ADD_SECTIONS_CHAIN" => "N",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "A",
		"CHECK_DATES" => "Y",
		"DETAIL_URL" => "",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"DISPLAY_TOP_PAGER" => "N",
		"FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"FILTER_NAME" => "",
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"IBLOCK_ID" => "#IBLOCK_ID_projects_current#",
		"IBLOCK_TYPE" => "projects",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"INCLUDE_SUBSECTIONS" => "Y",
		"MESSAGE_404" => "",
		"NEWS_COUNT" => "12",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => "flyaway",
		"PAGER_TITLE" => "Новости",
		"PARENT_SECTION" => "",
		"PARENT_SECTION_CODE" => "",
		"PREVIEW_TRUNCATE_LEN" => "",
		"PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"RSFLYAWAY_BLOCK_NAME_IS_LINK" => "Y",
		"RSFLYAWAY_COLS_IN_ROW" => "4",
		"RSFLYAWAY_SHOW_BLOCK_NAME" => "Y",
		"RSFLYAWAY_USE_OWL" => "Y",
		"RSMONOPOLY_BLOCK_NAME_IS_LINK" => "Y",
		"RSMONOPOLY_OWL_CHANGE_DELAY" => "8000",
		"RSMONOPOLY_OWL_CHANGE_SPEED" => "2000",
		"RSMONOPOLY_OWL_PC" => "3",
		"RSMONOPOLY_OWL_PHONE" => "1",
		"RSMONOPOLY_OWL_TABLET" => "2",
		"RSMONOPOLY_SHOW_BLOCK_NAME" => "Y",
		"RSMONOPOLY_USE_OWL" => "Y",
		"SET_BROWSER_TITLE" => "N",
		"SET_LAST_MODIFIED" => "N",
		"SET_META_DESCRIPTION" => "N",
		"SET_META_KEYWORDS" => "N",
		"SET_STATUS_404" => "N",
		"SET_TITLE" => "N",
		"SHOW_404" => "N",
		"SORT_BY1" => "ACTIVE_FROM",
		"SORT_BY2" => "SORT",
		"SORT_ORDER1" => "DESC",
		"SORT_ORDER2" => "ASC",
		"COMPONENT_TEMPLATE" => "services_main",
		"RSFLYAWAY_OWL_CHANGE_SPEED" => "2000",
		"RSFLYAWAY_OWL_CHANGE_DELAY" => "8000",
		"RSFLYAWAY_OWL_PHONE" => "1",
		"RSFLYAWAY_OWL_TABLET" => "2",
		"RSFLYAWAY_OWL_PC" => "4"
	),
	false
);?><br>
 <?$APPLICATION->IncludeComponent(
	"bitrix:news.list",
	"services_main",
	array(
		"ACTIVE_DATE_FORMAT" => "d.m.Y",
		"ADD_SECTIONS_CHAIN" => "N",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "A",
		"CHECK_DATES" => "Y",
		"DETAIL_URL" => "",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"DISPLAY_TOP_PAGER" => "N",
		"FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"FILTER_NAME" => "",
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"IBLOCK_ID" => "#IBLOCK_ID_projects_perspective#",
		"IBLOCK_TYPE" => "projects",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"INCLUDE_SUBSECTIONS" => "Y",
		"MESSAGE_404" => "",
		"NEWS_COUNT" => "12",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => "flyaway",
		"PAGER_TITLE" => "Новости",
		"PARENT_SECTION" => "",
		"PARENT_SECTION_CODE" => "",
		"PREVIEW_TRUNCATE_LEN" => "",
		"PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"RSFLYAWAY_BLOCK_NAME_IS_LINK" => "Y",
		"RSFLYAWAY_COLS_IN_ROW" => "4",
		"RSFLYAWAY_SHOW_BLOCK_NAME" => "Y",
		"RSFLYAWAY_USE_OWL" => "Y",
		"RSMONOPOLY_BLOCK_NAME_IS_LINK" => "Y",
		"RSMONOPOLY_OWL_CHANGE_DELAY" => "8000",
		"RSMONOPOLY_OWL_CHANGE_SPEED" => "2000",
		"RSMONOPOLY_OWL_PC" => "3",
		"RSMONOPOLY_OWL_PHONE" => "1",
		"RSMONOPOLY_OWL_TABLET" => "2",
		"RSMONOPOLY_SHOW_BLOCK_NAME" => "Y",
		"RSMONOPOLY_USE_OWL" => "Y",
		"SET_BROWSER_TITLE" => "N",
		"SET_LAST_MODIFIED" => "N",
		"SET_META_DESCRIPTION" => "N",
		"SET_META_KEYWORDS" => "N",
		"SET_STATUS_404" => "N",
		"SET_TITLE" => "N",
		"SHOW_404" => "N",
		"SORT_BY1" => "ACTIVE_FROM",
		"SORT_BY2" => "SORT",
		"SORT_ORDER1" => "DESC",
		"SORT_ORDER2" => "ASC",
		"COMPONENT_TEMPLATE" => "services_main",
		"RSFLYAWAY_OWL_CHANGE_SPEED" => "2000",
		"RSFLYAWAY_OWL_CHANGE_DELAY" => "8000",
		"RSFLYAWAY_OWL_PHONE" => "1",
		"RSFLYAWAY_OWL_TABLET" => "2",
		"RSFLYAWAY_OWL_PC" => "4"
	),
	false
);?><br><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>
