<?if(!defined("B_PROLOG_INCLUDED")||B_PROLOG_INCLUDED!==true)die();function ___writeToAreasFile($fn,$text)
{if(file_exists($fn)&&!is_writable($abs_path)&&defined("BX_FILE_PERMISSIONS"))@chmod($abs_path,BX_FILE_PERMISSIONS);$fd=@fopen($fn,"wb");if(!$fd)
return false;if(false===fwrite($fd,$text))
{fclose($fd);return false;}
fclose($fd);if(defined("BX_FILE_PERMISSIONS"))@chmod($fn,BX_FILE_PERMISSIONS);}
if(!defined("WIZARD_SITE_ID"))return;if(!defined("WIZARD_SITE_DIR"))return;if(COption::GetOptionString("main","upload_dir")=="")
COption::SetOptionString("main","upload_dir","upload");$wizard=&$this->GetWizard();$path=str_replace("//","/",WIZARD_ABSOLUTE_PATH."/site/public/".LANGUAGE_ID."/");$handle=@opendir($path);if($handle)
{while($file=readdir($handle))
{if(in_array($file,array(".","..")))
continue;CopyDirFiles($path.$file,WIZARD_SITE_PATH.$file,$rewrite=true,$recursive=true,$delete_after_copy=false,$exclude="bitrix");}}@copy($path."404.php",$_SERVER["DOCUMENT_ROOT"]."/404.php");WizardServices::PatchHtaccess(WIZARD_SITE_PATH);WizardServices::ReplaceMacrosRecursive(WIZARD_SITE_PATH."about/",Array("EMAIL"=>$wizard->GetVar("shopEmail")));WizardServices::ReplaceMacrosRecursive(WIZARD_SITE_PATH."contacts/",Array("SITE_DIR"=>WIZARD_SITE_DIR,"COMPANY_SCHEDULE"=>$wizard->GetVar("siteSchedule"),"COMPANY_TELEPHONE"=>$wizard->GetVar("siteTelephone"),"SHOP_ADR"=>$wizard->GetVar("shopAdr"),"EMAIL"=>$wizard->GetVar("shopEmail")));WizardServices::ReplaceMacrosRecursive(WIZARD_SITE_PATH."delivery/",Array("COMPANY_TELEPHONE"=>$wizard->GetVar("siteTelephone"),"EMAIL"=>$wizard->GetVar("shopEmail")));WizardServices::ReplaceMacrosRecursive(WIZARD_SITE_PATH."include/",Array("SITE_DIR"=>WIZARD_SITE_DIR,"VK"=>$wizard->GetVar("shopVk"),"FACEBOOK"=>$wizard->GetVar("shopFacebook"),"TWITTER"=>$wizard->GetVar("shopTwitter"),"COMPANY_TELEPHONE"=>$wizard->GetVar("siteTelephone")));WizardServices::ReplaceMacrosRecursive(WIZARD_SITE_PATH."personal/",Array("SITE_DIR"=>WIZARD_SITE_DIR));$siteMetaKeywords=WIZARD_INSTALL_DEMO_DATA?htmlspecialcharsbx($wizard->GetVar("siteMetaKeywords")):"";$siteMetaDescription=WIZARD_INSTALL_DEMO_DATA?htmlspecialcharsbx($wizard->GetVar("siteMetaDescription")):"";CWizardUtil::ReplaceMacros(WIZARD_SITE_PATH.".section.php",Array("SITE_KEYWORDS"=>$siteMetaKeywords,"SITE_DESCRIPTION"=>$siteMetaDescription));$banner_head=$wizard->GetVar("banner_head");$banner_text=$wizard->GetVar("banner_text");$replaceMacros=array("SITE_DIR"=>WIZARD_SITE_DIR);for($i=0;$i<count($banner_head);$i++)
{$replaceMacros["BANNER_HEAD_$i"]=$banner_head["banner_head_$i"];$replaceMacros["BANNER_TEXT_$i"]=$banner_text["banner_text_$i"];}
CWizardUtil::ReplaceMacros(WIZARD_SITE_PATH."_index.php",$replaceMacros);$arUrlRewrite=array();if(file_exists(WIZARD_SITE_ROOT_PATH."/urlrewrite.php"))
include(WIZARD_SITE_ROOT_PATH."/urlrewrite.php");$arNewUrlRewrite[]=array("CONDITION"=>"#^".WIZARD_SITE_DIR."news/#","RULE"=>"","ID"=>"bitrix:news","PATH"=>WIZARD_SITE_DIR."news/index.php",);$arNewUrlRewrite[]=array("CONDITION"=>"#^".WIZARD_SITE_DIR."catalog/#","RULE"=>"","ID"=>"bitrix:catalog","PATH"=>WIZARD_SITE_DIR."catalog/index.php",);$arNewUrlRewrite[]=array("CONDITION"=>"#^".WIZARD_SITE_DIR."new/#","RULE"=>"","ID"=>"bitrix:catalog","PATH"=>WIZARD_SITE_DIR."new/index.php",);$arNewUrlRewrite[]=array("CONDITION"=>"#^".WIZARD_SITE_DIR."actions/#","RULE"=>"","ID"=>"bitrix:catalog","PATH"=>WIZARD_SITE_DIR."actions/index.php",);$arNewUrlRewrite[]=array("CONDITION"=>"#^".WIZARD_SITE_DIR."sale/#","RULE"=>"","ID"=>"bitrix:catalog","PATH"=>WIZARD_SITE_DIR."sale/index.php",);$arNewUrlRewrite[]=array("CONDITION"=>"#^".WIZARD_SITE_DIR."articles/#","RULE"=>"","ID"=>"bitrix:news","PATH"=>WIZARD_SITE_DIR."articles/index.php",);$arNewUrlRewrite[]=array("CONDITION"=>"#^".WIZARD_SITE_DIR."personal/order/#","RULE"=>"","ID"=>"bitrix:sale.personal.order","PATH"=>WIZARD_SITE_DIR."personal/order/index.php",);foreach($arNewUrlRewrite as $arUrl)
if(!in_array($arUrl,$arUrlRewrite))
{$arUrl["SITE_ID"]=WIZARD_SITE_ID;CUrlRewriter::Add($arUrl);}
$siteLogo=$wizard->GetVar("siteLogo");$siteLogo_=$wizard->GetVar("siteLogo_");if($siteLogo>0||$siteLogo_>0)
{$ff=CFile::GetByID($siteLogo_);if($zr=$ff->Fetch())
{$strOldFile=str_replace("//","/",WIZARD_SITE_ROOT_PATH."/".(COption::GetOptionString("main","upload_dir","upload"))."/".$zr["SUBDIR"]."/".$zr["FILE_NAME"]);@copy($strOldFile,WIZARD_SITE_PATH."images/logo.png");___writeToAreasFile(WIZARD_SITE_PATH."include/company_logo.php",'<a href="'.WIZARD_SITE_DIR.'"><img src="'.WIZARD_SITE_DIR.'images/logo.png"  /></a>');CFile::Delete($siteLogo_);}
$ff=CFile::GetByID($siteLogo);if($zr=$ff->Fetch())
{$strOldFile=str_replace("//","/",WIZARD_SITE_ROOT_PATH."/".(COption::GetOptionString("main","upload_dir","upload"))."/".$zr["SUBDIR"]."/".$zr["FILE_NAME"]);@copy($strOldFile,WIZARD_SITE_PATH."images/logo.png");___writeToAreasFile(WIZARD_SITE_PATH."include/company_logo.php",'<a href="'.WIZARD_SITE_DIR.'"><img src="'.WIZARD_SITE_DIR.'images/logo.png"  /></a>');CFile::Delete($siteLogo);}}
DeleteDirFilesEx("/upload/tmp/");?>