<?if(!defined("B_PROLOG_INCLUDED") || B_PROLOG_INCLUDED!==true)die();?>

<?$APPLICATION->IncludeComponent(
	"westpower:auction.list",
	".default",
	Array(
		"AUCTION_IBLOCK_TYPE" => $arParams["AUCTION_IBLOCK_TYPE"],
		"AUCTION_IBLOCK_ID" => $arParams["AUCTION_IBLOCK_ID"],
		"BETS_IBLOCK_TYPE" => $arParams["BETS_IBLOCK_TYPE"],
		"BETS_IBLOCK_ID" => $arParams["BETS_IBLOCK_ID"],
		"SECTION_ID" => $arParams["SECTION_ID"],
		"SECTION_CODE" => $arParams["SECTION_CODE"],
		"DETAIL_URL" => $arParams["DETAIL_URL"],
		"AUCTION_JQUERY" => $arParams["AUCTION_JQUERY"],
		"AUCTION_PRODUCT_PROPERTY" => $arParams["AUCTION_PRODUCT_PROPERTY"],
		"AUCTION_LAST_BETS" => $arParams["AUCTION_LAST_BETS"],
		"AUCTION_PERMISSIONS" => $arParams["AUCTION_PERMISSIONS"],
		"FILTER_NAME" => $arParams["FILTER_NAME"],
		"FILTER_NAME_LOT" => $arParams["FILTER_NAME_LOT"],
		"LOT_SORT_FIELD1" => $arParams["LOT_SORT_FIELD1"],
		"LOT_SORT_ORDER1" => $arParams["LOT_SORT_ORDER1"],
		"LOT_SORT_FIELD2" => $arParams["LOT_SORT_FIELD2"],
		"LOT_SORT_ORDER2" => $arParams["LOT_SORT_ORDER2"],
		"AUCTION_HIDE" => $arParams["AUCTION_HIDE"],
		"PAGE_ELEMENT_COUNT" => $arParams["PAGE_ELEMENT_COUNT"],
		"LINE_ELEMENT_COUNT" => $arParams["LINE_ELEMENT_COUNT"],
		"AUCTION_NAME" => $arParams["AUCTION_NAME"],
		"AUCTION_LOT" => $arParams["AUCTION_LOT"],
		"IMG_WIDTH" => $arParams["IMG_WIDTH"],
		"IMG_HEIGHT" => $arParams["IMG_HEIGHT"],
		"AUCTION_SET_TITLE" => $arParams["AUCTION_SET_TITLE"],
		"AUCTION_TITLE" => $arParams["AUCTION_TITLE"],
		"CACHE_TYPE" => $arParams["CACHE_TYPE"],
		"CACHE_TIME" => $arParams["CACHE_TIME"],
		"DISPLAY_TOP_PAGER" => $arParams["DISPLAY_TOP_PAGER"],
		"DISPLAY_BOTTOM_PAGER" => $arParams["DISPLAY_BOTTOM_PAGER"],
		"PAGER_TITLE" => $arParams["PAGER_TITLE"],
		"PAGER_SHOW_ALWAYS" => $arParams["PAGER_SHOW_ALWAYS"],
		"PAGER_TEMPLATE" => $arParams["PAGER_TEMPLATE"],
		"PAGER_DESC_NUMBERING" => $arParams["PAGER_DESC_NUMBERING"],
		"PAGER_DESC_NUMBERING_CACHE_TIME" => $arParams["PAGER_DESC_NUMBERING_CACHE_TIME"],
		"PAGER_SHOW_ALL" => $arParams["PAGER_SHOW_ALL"],
		"DETAIL_URL" => $arResult["FOLDER"].$arResult["URL_TEMPLATES"]["element"],
	),
	$component
);?>