<?
$PERM["test"]["2"]="R";
$PERM["test"]["3"]="X";
$PERM["test"]["4"]="X";
$PERM["test"]["5"]="X";
$PERM["test"]["*"]="X";
$PERM["desktop_app"]["*"]="R";
$PERM["news"]["5"]="W";
$PERM["services"]["5"]="W";
$PERM["products"]["5"]="W";
$PERM["contacts"]["5"]="W";
$PERM["company"]["5"]="W";
$PERM["index.php"]["5"]="W";
$PERM["/"]["*"]="R";
?>