CREATE TABLE IF NOT EXISTS `smartrealt_catalog_element` (
  `Id` char(36) NOT NULL,
  `Number` int(11) NOT NULL,
  `SectionId` int(11) NOT NULL,
  `SectionFullName` varchar(255) NOT NULL,
  `SectionFullNameSign` varchar(255) NOT NULL,
  `Status` enum('PUBLISH','ARCHIVE') NOT NULL,
  `TypeId` int(11) NOT NULL,
  `TypeName` varchar(255) NOT NULL,
  `TransactionType` enum('SALE','RENT','DAILY_RENT') NOT NULL,
  `EstateMarket` enum('PRIMARY','SECONDARY') NOT NULL,
  `Developer` varchar(255) DEFAULT NULL,
  `DesignDeclaration` varchar(255) DEFAULT NULL,
  `BuiltYear` int(11) DEFAULT NULL,
  `BuiltQuarter` varchar(255) DEFAULT NULL,
  `ComplexDemand` enum('Y','N') NOT NULL,
  `AgentName` varchar(255) NOT NULL,
  `AgentPhone` varchar(255) NOT NULL,
  `AgentEmail` varchar(255) NOT NULL,
  `Latitude` varbinary(255) DEFAULT NULL,
  `Longitude` varbinary(255) DEFAULT NULL,
  `Zoom` int(11) DEFAULT '13',
  `LatitudeYandex` varbinary(255) DEFAULT NULL,
  `LongitudeYandex` varbinary(255) DEFAULT NULL,
  `ZoomYandex` int(11) DEFAULT '13',
  `CountryId` char(36) NOT NULL,
  `CountryName` varchar(255) NOT NULL,
  `RegionId` char(36) DEFAULT NULL,
  `RegionName` varchar(255) DEFAULT NULL,
  `RegionAreaId` char(36) DEFAULT NULL,
  `RegionAreaName` varchar(255) DEFAULT NULL,
  `CityId` char(36) DEFAULT NULL,
  `CityName` varchar(255) DEFAULT NULL,
  `ForeignCity` varchar(255) DEFAULT NULL,
  `TownId` char(36) DEFAULT NULL,
  `TownName` varchar(255) DEFAULT NULL,
  `CityAreaId` char(36) DEFAULT NULL,
  `CityAreaName` varchar(255) DEFAULT NULL,
  `MetroStationId` char(36) DEFAULT NULL,
  `MetroStationName` varchar(255) DEFAULT NULL,
  `HighwayId` char(36) DEFAULT NULL,
  `HighwayName` varchar(255) DEFAULT NULL,
  `Remoteness` varchar(255) DEFAULT NULL,
  `Street` varchar(255) DEFAULT NULL,
  `HouseNumber` varchar(255) DEFAULT NULL,
  `Floor` int(11) DEFAULT NULL,
  `FloorQuantity` int(11) DEFAULT NULL,
  `FloorHeight` double DEFAULT NULL,
  `RoomQuantity` int(11) DEFAULT NULL,
  `RoomOffer` int(11) DEFAULT NULL,
  `GeneralArea` double NOT NULL,
  `KitchenArea` double DEFAULT NULL,
  `LifeArea` double DEFAULT NULL,
  `AreaUnitId` int(11) NOT NULL,
  `AreaUnitName` varchar(255) NOT NULL,
  `LandArea` double DEFAULT NULL,
  `LandAreaUnitId` int(11) DEFAULT NULL,
  `LandAreaUnitName` varchar(255) DEFAULT NULL,
  `Description` text CHARACTER SET utf8 COLLATE utf8_unicode_ci,
  `SpecialOffer` enum('Y','N') NOT NULL,
  `Price` double NOT NULL,
  `PricePerMetr` double NOT NULL,
  `CurrencyId` varchar(3) NOT NULL,
  `CurrencySymbol` varchar(255) DEFAULT NULL,
  `CurrencyPattern` varchar(255) DEFAULT NULL,
  `CurrencyPatternThousand` varchar(255) DEFAULT NULL,
  `PriceCurrencyRate` double DEFAULT NULL,
  `Mortgage` enum('Y','N') DEFAULT NULL,
  `ConditionId` char(36) DEFAULT NULL,
  `ConditionName` varchar(255) DEFAULT NULL,
  `ToiletTypeId` int(11) DEFAULT NULL,
  `ToiletTypeName` varchar(255) DEFAULT NULL,
  `BalconyTypeId` int(11) DEFAULT NULL,
  `BalconyTypeName` varchar(255) DEFAULT NULL,
  `LiftTypeId` int(11) DEFAULT NULL,
  `LiftTypeName` varchar(255) DEFAULT NULL,
  `HouseTypeName` varchar(255) DEFAULT NULL,
  `HouseProjectName` varchar(255) DEFAULT NULL,
  `BuildingName` varchar(255) DEFAULT NULL,
  `LandCategoryId` int(11) DEFAULT NULL,
  `LandCategoryName` varchar(255) DEFAULT NULL,
  `LandUseTypeId` int(11) DEFAULT NULL,
  `LandUseTypeName` varchar(255) DEFAULT NULL,
  `ElectricPower` double DEFAULT NULL,
  `StreetRetail` enum('Y','N') DEFAULT NULL,
  `Deleted` enum('Y','N') NOT NULL DEFAULT 'N',
  `CreateDate` datetime NOT NULL,
  `UpdateDate` datetime NOT NULL,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `smartrealt_catalog_element_photo` (
  `Id` char(36) NOT NULL,
  `CatalogElementId` char(36) NOT NULL,
  `FileId` int(11) NOT NULL,
  `Url` varchar(255) NOT NULL,
  `Sort` int(11) NOT NULL,
  `Deleted` enum('Y','N') NOT NULL DEFAULT 'N',
  `CreateDate` datetime NOT NULL,
  `UpdateDate` datetime NOT NULL,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `smartrealt_catalog_element_type` (
  `Id` int(11) NOT NULL,
  `Name` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `smartrealt_rubric` (
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `Active` enum('Y','N') NOT NULL DEFAULT 'Y',
  `Name` varchar(255) NOT NULL,
  `RubricGroupId` int(11) NOT NULL,
  `TypeName` varchar(255) NOT NULL,
  `TransactionType` enum('SALE','RENT','DAILY_RENT') DEFAULT NULL,
  `TypeId` varbinary(255) NOT NULL,
  `Code` varchar(255) DEFAULT NULL,
  `PageTitle` varchar(255) DEFAULT NULL,
  `Description` text DEFAULT NULL,
  `Sort` int(11) NOT NULL DEFAULT '100',
  `CreateDate` datetime NOT NULL,
  `UpdateDate` datetime NOT NULL,
  `SectionId` varchar(1) DEFAULT NULL,
  `EstateMarket` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `smartrealt_rubric_group` (
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `Name` varchar(255) NOT NULL,
  `Active` enum('Y','N') NOT NULL DEFAULT 'Y',
  `Sort` int(11) NOT NULL DEFAULT '100',
  `CreateDate` datetime NOT NULL,
  `UpdateDate` datetime NOT NULL,
  `Code` varchar(255) NOT NULL,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB;