<?
if(@$_REQUEST["ajax"] && $_REQUEST["ajax"] == "Y") {
  require($_SERVER["DOCUMENT_ROOT"]."/bitrix/modules/main/include/prolog_before.php");
} else {
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Каталог");

$GLOBALS['arrFilter'] = $_POST;
?> 
<div class="catalog"> <?}?> <?CSubsections::Init();?> <?$APPLICATION->IncludeComponent("bitrix:catalog", "main_catalogue", array(
	"IBLOCK_TYPE" => "catalog",
	"IBLOCK_ID" => "1",
	"BASKET_URL" => "/personal/basket.php",
	"ACTION_VARIABLE" => "action",
	"PRODUCT_ID_VARIABLE" => "id",
	"SECTION_ID_VARIABLE" => "SECTION_ID",
	"PRODUCT_QUANTITY_VARIABLE" => "quantity",
	"PRODUCT_PROPS_VARIABLE" => "prop",
	"SEF_MODE" => "Y",
	"SEF_FOLDER" => "/catalogue/",
	"AJAX_MODE" => "N",
	"AJAX_OPTION_JUMP" => "N",
	"AJAX_OPTION_STYLE" => "Y",
	"AJAX_OPTION_HISTORY" => "N",
	"CACHE_TYPE" => "N",
	"CACHE_TIME" => "36000000",
	"CACHE_FILTER" => "N",
	"CACHE_GROUPS" => "Y",
	"SET_TITLE" => "Y",
	"SET_STATUS_404" => "Y",
	"USE_ELEMENT_COUNTER" => "Y",
	"USE_FILTER" => "Y",
	"FILTER_NAME" => "arrFilter",
	"FILTER_FIELD_CODE" => array(
		0 => "",
		1 => "",
	),
	"FILTER_PROPERTY_CODE" => array(
		0 => "article",
		1 => "country",
		2 => "rating",
		3 => "sale",
		4 => "navi",
		5 => "",
	),
	"FILTER_PRICE_CODE" => array(
		0 => "price",
		1 => "clearing",
	),
	"USE_REVIEW" => "N",
	"USE_COMPARE" => "Y",
	"COMPARE_NAME" => "CATALOG_COMPARE_LIST",
	"COMPARE_FIELD_CODE" => array(
		0 => "NAME",
		1 => "PREVIEW_PICTURE",
		2 => "DETAIL_PICTURE",
		3 => "",
	),
	"COMPARE_PROPERTY_CODE" => array(
		0 => "model",
		1 => "article",
		2 => "country",
		3 => "rating",
		4 => "navi",
		5 => "",
	),
	"COMPARE_ELEMENT_SORT_FIELD" => "sort",
	"COMPARE_ELEMENT_SORT_ORDER" => "asc",
	"DISPLAY_ELEMENT_SELECT_BOX" => "N",
	"PRICE_CODE" => array(
		0 => "price",
		1 => "clearing",
	),
	"USE_PRICE_COUNT" => "N",
	"SHOW_PRICE_COUNT" => "1",
	"PRICE_VAT_INCLUDE" => "Y",
	"PRICE_VAT_SHOW_VALUE" => "N",
	"PRODUCT_PROPERTIES" => array(
	),
	"USE_PRODUCT_QUANTITY" => "Y",
	"CONVERT_CURRENCY" => "N",
	"SHOW_TOP_ELEMENTS" => "N",
	"SECTION_COUNT_ELEMENTS" => "Y",
	"SECTION_TOP_DEPTH" => "2",
	"PAGE_ELEMENT_COUNT" => "6",
	"LINE_ELEMENT_COUNT" => "3",
	"ELEMENT_SORT_FIELD" => "sort",
	"ELEMENT_SORT_ORDER" => "asc",
	"LIST_PROPERTY_CODE" => array(
		0 => "type",
		1 => "model",
		2 => "article",
		3 => "",
	),
	"INCLUDE_SUBSECTIONS" => "Y",
	"LIST_META_KEYWORDS" => "-",
	"LIST_META_DESCRIPTION" => "-",
	"LIST_BROWSER_TITLE" => "-",
	"DETAIL_PROPERTY_CODE" => array(
		0 => "warranty",
		1 => "country",
		2 => "display_size",
		3 => "display_screen_type",
		4 => "display_resolution",
		5 => "display_type",
		6 => "display_touch",
		7 => "display_touch_type",
		8 => "display_touch_multi",
		9 => "support_3d",
		10 => "display_screen_type_tech",
		11 => "product_weight",
		12 => "processor_technology",
		13 => "processor_socket",
		14 => "processor_core",
		15 => "processor_manufacturer",
		16 => "processor_type",
		17 => "processor_code",
		18 => "processor_frequency",
		19 => "processor_cache_l1",
		20 => "processor_cache_l2",
		21 => "processor_cache_l3",
		22 => "processor_number_of_cores",
		23 => "chipset",
		24 => "system_bus_frequency",
		25 => "memory_form_factor",
		26 => "memory_size",
		27 => "memory_type",
		28 => "memory_frequency",
		29 => "memory_slots_count",
		30 => "memory_size_maximum",
		31 => "internal_memory_size",
		32 => "total_hdd_size",
		33 => "hdd_type",
		34 => "hdd_round_speed",
		35 => "hdd_count_two",
		36 => "optical_drive",
		37 => "optical_drive_placement",
		38 => "wifi_present",
		39 => "wifi_standart",
		40 => "wifi_direct_support",
		41 => "dlna_support",
		42 => "bluetooth_present",
		43 => "bluetooth_version",
		44 => "a2dp_support",
		45 => "nfc_support",
		46 => "lte_present",
		47 => "wimax_present",
		48 => "gsm_gprs_support",
		49 => "umts_3g_present",
		50 => "edge_support",
		51 => "hsdpa_support",
		52 => "hsupa_support",
		53 => "hspa_plus_support",
		54 => "work_as_mobile_phone",
		55 => "sim_card",
		56 => "video_controller_type",
		57 => "videocard_chipset_vendor",
		58 => "videocard_chipset",
		59 => "videomemory_size",
		60 => "videomemory_type",
		61 => "battery_type",
		62 => "battery_capacity",
		63 => "battery_cells",
		64 => "work_time",
		65 => "work_time_on_music",
		66 => "work_time_on_video",
		67 => "time_of_charge",
		68 => "work_time_with_optional_battery",
		69 => "usb_charge",
		70 => "operating_system",
		71 => "windows_version",
		72 => "macosx_version",
		73 => "android_version",
		74 => "operating_system_support",
		75 => "cardreader_present",
		76 => "memory_card_support",
		77 => "memory_card_max_size",
		78 => "expresscard_slot",
		79 => "expresscard_standart",
		80 => "internal_local_network",
		81 => "local_network_speed",
		82 => "faxmodem_present",
		83 => "usb20_count",
		84 => "usb30_count",
		85 => "firewire_present",
		86 => "usb_connect_to_pc",
		87 => "firewire800_present",
		88 => "external_usb_connect",
		89 => "tvin_input",
		90 => "tvout_ouput",
		91 => "vga_output",
		92 => "minivga_output",
		93 => "dvi_output",
		94 => "hdmi_output",
		95 => "microhdmi_output",
		96 => "displayport_outout",
		97 => "minidisplayport_output",
		98 => "lpt_present",
		99 => "thunderbolt_present",
		100 => "esata_present",
		101 => "irda_present",
		102 => "com_port",
		103 => "dockstation_port",
		104 => "dockstation_retail_pack",
		105 => "audio_input",
		106 => "microphone_input",
		107 => "audio_output",
		108 => "spdif_present",
		109 => "microphone_present",
		110 => "subwoofer_present",
		111 => "speakers_present",
		112 => "audio_type",
		113 => "qwerty_keyboard",
		114 => "keyboard_keys_count",
		115 => "keyboard_backlight",
		116 => "positioning_device",
		117 => "stylus_pen_retail_pack",
		118 => "gps_present",
		119 => "agps_support",
		120 => "glonass_present",
		121 => "compas_present",
		122 => "accelerometer_present",
		123 => "gyroscope_present",
		124 => "proximity_sensor_present",
		125 => "light_sensor_present",
		126 => "barometer_present",
		127 => "webcamera_present",
		128 => "webcamera_resolution",
		129 => "front_camera",
		130 => "front_camera_resolution",
		131 => "back_camera",
		132 => "back_camera_resolution",
		133 => "flash_light",
		134 => "autofocus",
		135 => "fingerprint_sensor",
		136 => "tv_tuner",
		137 => "remote_control",
		138 => "fm_tuner_present",
		139 => "fm_transmitter_present",
		140 => "kensington_lock",
		141 => "shell_shockproof",
		142 => "shell_metal",
		143 => "shell_waterproof",
		144 => "case_material",
		145 => "audio_format_support",
		146 => "video_format_support",
		147 => "",
	),
	"DETAIL_META_KEYWORDS" => "-",
	"DETAIL_META_DESCRIPTION" => "-",
	"DETAIL_BROWSER_TITLE" => "-",
	"LINK_IBLOCK_TYPE" => "",
	"LINK_IBLOCK_ID" => "",
	"LINK_PROPERTY_SID" => "",
	"LINK_ELEMENTS_URL" => "link.php?PARENT_ELEMENT_ID=#ELEMENT_ID#",
	"USE_ALSO_BUY" => "N",
	"USE_STORE" => "N",
	"DISPLAY_TOP_PAGER" => "N",
	"DISPLAY_BOTTOM_PAGER" => "Y",
	"PAGER_TITLE" => "Товары",
	"PAGER_SHOW_ALWAYS" => "N",
	"PAGER_TEMPLATE" => "ajaxmode",
	"PAGER_DESC_NUMBERING" => "N",
	"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
	"PAGER_SHOW_ALL" => "N",
	"N1" => "3",
	"N2" => "6",
	"N3" => "10",
	"N4" => "30",
	"AJAX_OPTION_ADDITIONAL" => "",
	"SEF_URL_TEMPLATES" => array(
		"sections" => "",
		"section" => "#SECTION_ID#/",
		"element" => "#SECTION_ID#/#ELEMENT_ID#/",
		"compare" => "compare.php?action=#ACTION_CODE#",
	),
	"VARIABLE_ALIASES" => array(
		"compare" => array(
			"ACTION_CODE" => "action",
		),
	)
	),
	false
);?> <?
if(@$_REQUEST["ajax"] && $_REQUEST["ajax"] == "Y") {
?>
<script src="/js/js.js"></script>
<?
} else {?> </div>
 <?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");
}
?>