<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Просмотренные товары");
?><?$APPLICATION->IncludeComponent(
	"bitrix:catalog.viewed.products", 
	"personal", 
	array(
		"ACTION_VARIABLE" => "action",
		"ADDITIONAL_PICT_PROP_2" => "MORE_PHOTO",
		"ADDITIONAL_PICT_PROP_29" => "MORE_PHOTO",
		"ADD_PROPERTIES_TO_BASKET" => "Y",
		"BASKET_URL" => "/personal/cart/",
		"CACHE_GROUPS" => "Y",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "A",
		"CART_PROPERTIES_2" => array(
			0 => "",
			1 => "",
		),
		"CART_PROPERTIES_29" => array(
			0 => "",
			1 => "",
		),
		"COMPONENT_TEMPLATE" => "personal",
		"CONVERT_CURRENCY" => "N",
		"DEPTH" => "",
		"DETAIL_URL" => "",
		"HIDE_NOT_AVAILABLE" => "N",
		"IBLOCK_ID" => "2",
		"IBLOCK_TYPE" => "catalog",
		"LABEL_PROP_2" => "-",
		"LINE_ELEMENT_COUNT" => "3",
		"MESS_BTN_BUY" => "Купить",
		"MESS_BTN_DETAIL" => "Подробнее",
		"MESS_BTN_SUBSCRIBE" => "Подписаться",
		"OFFER_TREE_PROPS_29" => array(
			0 => "COLOR_DIRECTORY",
			1 => "SKU_FASOVKA",
		),
		"OFFER_TREE_COLOR_PROPS_29" => array(
			0 => "COLOR_DIRECTORY",
		),
		"PAGE_ELEMENT_COUNT" => "5",
		"PARTIAL_PRODUCT_PROPERTIES" => "N",
		"PRICE_CODE" => array(
			0 => "BASE",
		),
		"PRICE_VAT_INCLUDE" => "Y",
		"PRODUCT_ID_VARIABLE" => "id",
		"PRODUCT_PROPS_VARIABLE" => "prop",
		"PRODUCT_QUANTITY_VARIABLE" => "",
		"PRODUCT_SUBSCRIPTION" => "N",
		"PROPERTY_CODE_2" => array(
			0 => "31",
			1 => "32",
			2 => "33",
			3 => "35",
			4 => "36",
			5 => "37",
			6 => "CML2_ARTICLE",
			7 => "ACTION_ITEM",
			8 => "BEST_SELLER",
			9 => "NEW_ITEM",
			10 => "BRAND",
			11 => "MOSHNOST",
			12 => "DIAMETR",
			13 => "WE_RECCOMENDED",
			14 => "DATE_SALE",
			15 => "DOCS",
			16 => "FORUM_MESSAGE_CNT",
			17 => "vote_count",
			18 => "HOD",
			19 => "SIMILAR_PRODUCTS",
			20 => "rating",
			21 => "vote_sum",
			22 => "FORUM_TOPIC_ID",
			23 => "AKKUMULATOR",
			24 => "COLOR_KORPUS",
			25 => "FOR_TAB_SOSTAV",
			26 => "ACCESSORIES",
			27 => "MORE_PHOTO",
			28 => "COLOR_HL",
			29 => "PRICE",
			30 => "DISCOUNT",
			31 => "CURRENCY",
			32 => "QUANTITY",
			33 => "",
		),
		"PROPERTY_CODE_29" => array(
			0 => "COLOR_DIRECTORY",
			1 => "SKU_FASOVKA",
			2 => "MORE_PHOTO",
			3 => "",
		),
		"RSFLYAWAY_PROP_ARTICLE" => "31",
		"RSFLYAWAY_PROP_CURRENCY" => "31",
		"RSFLYAWAY_PROP_DISCOUNT" => "-",
		"RSFLYAWAY_PROP_MORE_PHOTO" => "MORE_PHOTO",
		"RSFLYAWAY_PROP_OFF_POPUP" => "Y",
		"RSFLYAWAY_PROP_PRICE" => "-",
		"RSFLYAWAY_PROP_PRICE_DECIMALS" => "0",
		"RSFLYAWAY_PROP_QUANTITY" => "-",
		"SECTION_CODE" => "",
		"SECTION_ELEMENT_CODE" => "",
		"SECTION_ELEMENT_ID" => "",
		"SECTION_ID" => "",
		"SHOW_DISCOUNT_PERCENT" => "Y",
		"SHOW_FROM_SECTION" => "N",
		"SHOW_IMAGE" => "Y",
		"SHOW_NAME" => "Y",
		"SHOW_OLD_PRICE" => "N",
		"SHOW_PRICE_COUNT" => "1",
		"SHOW_PRODUCTS_2" => "Y",
		"TEMPLATE_THEME" => "blue",
		"USE_PRODUCT_QUANTITY" => "N",
		"RSFLYAWAY_PROP_PRICE" => "-",
		"RSFLYAWAY_PROP_DISCOUNT" => "-",
		"RSFLYAWAY_PROP_CURRENCY" => "-",
		"RSFLYAWAY_PROP_PRICE_DECIMALS" => "0",
		"RSFLYAWAY_PROP_QUANTITY" => "-",
		"RSFLYAWAY_PROP_MORE_PHOTO" => "MORE_PHOTO",
		"RSFLYAWAY_PROP_ARTICLE" => "CML2_ARTICLE",
		"RSFLYAWAY_PROP_OFF_POPUP" => "N",
		"PROPERTY_CODE_29" => array(
			0 => "",
			1 => "",
		),
		"CART_PROPERTIES_29" => array(
			0 => "",
			1 => "",
		),
		"ADDITIONAL_PICT_PROP_29" => "MORE_PHOTO",
		"OFFER_TREE_PROPS_29" => array(
			0 => "COLOR_DIRECTORY",
			1 => "SKU_FASOVKA",
		)
	),
	false
);?><br><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>