SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;


CREATE TABLE IF NOT EXISTS `slobel_canonical_list` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ACTIVE` char(1) COLLATE utf8_unicode_ci NOT NULL DEFAULT 'Y',
  `RULE` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `FILE` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `BASE` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=4 ;

INSERT INTO `slobel_canonical_list` (`ID`, `ACTIVE`, `RULE`, `FILE`, `BASE`) VALUES
(1, 'Y', '/PAGEN_(\\\\d+)=(\\\\d+)/is', '', ''),
(2, 'Y', '/sort=((?:[a-z][a-z]+))/is', '', ''),
(3, 'Y', '/order=((?:[a-z][a-z0-9_]*))/is', '', '');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;