<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Текущие проекты");
?><?$APPLICATION->IncludeComponent(
	"bitrix:news",
	"flyaway",
	array(
		"ADD_ELEMENT_CHAIN" => "Y",
		"ADD_SECTIONS_CHAIN" => "N",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"BROWSER_TITLE" => "-",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "A",
		"CHECK_DATES" => "Y",
		"COMPONENT_TEMPLATE" => "flyaway",
		"DETAIL_ACTIVE_DATE_FORMAT" => "",
		"DETAIL_DISPLAY_BOTTOM_PAGER" => "Y",
		"DETAIL_DISPLAY_TOP_PAGER" => "N",
		"DETAIL_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"DETAIL_PAGER_SHOW_ALL" => "Y",
		"DETAIL_PAGER_TEMPLATE" => "",
		"DETAIL_PAGER_TITLE" => "Страница",
		"DETAIL_PROPERTY_CODE" => array(
			0 => "",
			1 => "MORE_PHOTO",
			2 => "",
		),
		"DETAIL_SET_CANONICAL_URL" => "N",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"DISPLAY_DATE" => "N",
		"DISPLAY_NAME" => "Y",
		"DISPLAY_TOP_PAGER" => "N",
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"IBLOCK_ID" => "#IBLOCK_ID_projects_current#",
		"IBLOCK_TYPE" => "projects",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"LIST_ACTIVE_DATE_FORMAT" => "d.m.Y",
		"LIST_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"LIST_PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"MESSAGE_404" => "",
		"META_DESCRIPTION" => "-",
		"META_KEYWORDS" => "-",
		"NEWS_COUNT" => "12",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => "flyaway",
		"PAGER_TITLE" => "Новости",
		"PREVIEW_TRUNCATE_LEN" => "",
		"RSFLYAWAY_BLOCK_NAME_IS_LINK_LIST" => "N",
		"RSFLYAWAY_COLS_IN_ROW_LIST" => "3",
		"RSFLYAWAY_DETAIL_SUBSCRIBE_NOTE" => "",
		"RSFLYAWAY_DETAIL_SUBSCRIBE_PAGE" => "",
		"RSFLYAWAY_DETAIL_TEMPLATES" => "gallery",
		"RSFLYAWAY_DETAIL_USE_SUBSCRIBE" => "Y",
		"RSFLYAWAY_DETAIL_SUBSCRIBE_PAGE" => "/about/press_center/subscribe/",
		"RSFLYAWAY_LIST_TEMPLATES_DETAIL_USE" => "N",
		"RSFLYAWAY_LIST_TEMPLATES_LIST" => "services_main",
		"RSFLYAWAY_SHOW_BLOCK_NAME_LIST" => "N",
		"RSFLYAWAY_USE_OWL_LIST" => "N",
		"RSMONOPOLY_BLOCK_NAME_IS_LINK_DETAIL" => "Y",
		"RSMONOPOLY_BLOCK_NAME_IS_LINK_LIST" => "N",
		"RSMONOPOLY_COLS_IN_ROW_LIST" => "4",
		"RSMONOPOLY_DETAIL_TEMPLATES" => "gallery",
		"RSMONOPOLY_LIST_TEMPLATES_DETAIL" => "gallery",
		"RSMONOPOLY_LIST_TEMPLATES_DETAIL_USE" => "Y",
		"RSMONOPOLY_LIST_TEMPLATES_LIST" => "gallery",
		"RSMONOPOLY_OWL_CHANGE_DELAY_DETAIL" => "8000",
		"RSMONOPOLY_OWL_CHANGE_SPEED_DETAIL" => "500",
		"RSMONOPOLY_OWL_PC_DETAIL" => "3",
		"RSMONOPOLY_OWL_PHONE_DETAIL" => "1",
		"RSMONOPOLY_OWL_TABLET_DETAIL" => "2",
		"RSMONOPOLY_PROP_MORE_PHOTO" => "MORE_PHOTO",
		"RSMONOPOLY_SHOW_BLOCK_NAME_DETAIL" => "Y",
		"RSMONOPOLY_SHOW_BLOCK_NAME_LIST" => "N",
		"RSMONOPOLY_USE_OWL_DETAIL" => "Y",
		"RSMONOPOLY_USE_OWL_LIST" => "N",
		"SEF_FOLDER" => "#SITE_DIR#projects/current/",
		"SEF_MODE" => "Y",
		"SET_LAST_MODIFIED" => "N",
		"SET_STATUS_404" => "N",
		"SET_TITLE" => "Y",
		"SHOW_404" => "N",
		"SORT_BY1" => "ACTIVE_FROM",
		"SORT_BY2" => "SORT",
		"SORT_ORDER1" => "DESC",
		"SORT_ORDER2" => "ASC",
		"USE_CATEGORIES" => "N",
		"USE_FILTER" => "N",
		"USE_PERMISSIONS" => "N",
		"USE_RATING" => "N",
		"USE_REVIEW" => "N",
		"USE_RSS" => "N",
		"USE_SEARCH" => "N",
		"RSFLYAWAY_PROP_MORE_PHOTO" => "MORE_PHOTO",
		"SEF_URL_TEMPLATES" => array(
			"news" => "",
			"section" => "",
			"detail" => "#ELEMENT_CODE#/",
		)
	),
	false
);?><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>
