CREATE TABLE IF NOT EXISTS `api_orderstatus_file` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `ORDER_ID` INT(11) NULL DEFAULT NULL,
  `FILE_ID` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`)
);
CREATE TABLE IF NOT EXISTS `api_orderstatus_option` (
	`ID` INT(11) NOT NULL AUTO_INCREMENT,
	`NAME` VARCHAR(255) NOT NULL,
	`VALUE` TEXT NULL,
	`SITE_ID` CHAR(2) NOT NULL,
	PRIMARY KEY (`ID`),
	INDEX `NAME` (`NAME`),
	INDEX `SITE_ID` (`SITE_ID`)
);
CREATE TABLE IF NOT EXISTS `api_orderstatus_history` (
	`ID` INT(11) NOT NULL AUTO_INCREMENT,
	`ORDER_ID` INT(11) NULL DEFAULT '0',
	`USER_ID` INT(11) NULL DEFAULT '0',
	`STATUS` CHAR(2) NULL DEFAULT NULL,
	`DATE_CREATE` DATETIME NULL DEFAULT NULL,
	`DESCRIPTION` TEXT NULL,
	`LID` CHAR(2) NOT NULL DEFAULT 's1',
	`MAIL` CHAR(1) NOT NULL DEFAULT 'Y',
  `FILES` CHAR(1) NOT NULL DEFAULT 'N',
	PRIMARY KEY (`ID`),
	INDEX `ORDER_ID` (`ORDER_ID`),
	INDEX `USER_ID` (`USER_ID`)
);
CREATE TABLE IF NOT EXISTS `api_orderstatus_tpl` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `ACTIVE` CHAR(1) NULL DEFAULT 'Y',
  `NAME` VARCHAR(255) NULL DEFAULT NULL,
  `STATUS_ID` CHAR(2) NULL DEFAULT NULL,
  `DESCRIPTION` LONGTEXT NULL,
  `DESCRIPTION_TYPE` CHAR(4) NULL DEFAULT 'text',
  `DATE_MODIFY` DATETIME NULL DEFAULT NULL,
  `MODIFIED_BY` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`)
);
CREATE TABLE IF NOT EXISTS `api_orderstatus_macros` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(255) NULL DEFAULT NULL,
  `VALUE` LONGTEXT NULL,
  `VALUE_TYPE` CHAR(4) NULL DEFAULT 'text',
  `DATE_MODIFY` DATETIME NULL DEFAULT NULL,
  `MODIFIED_BY` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`)
);
CREATE TABLE IF NOT EXISTS `api_orderstatus_sms_gateway` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(255) NULL DEFAULT NULL,
  `ACTIVE` CHAR(1) NULL DEFAULT 'Y',
  `SORT` INT(11) NULL DEFAULT '500',
  `PARAMS` LONGTEXT NULL,
  `DATE_MODIFY` DATETIME NULL DEFAULT NULL,
  `MODIFIED_BY` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`)
);
CREATE TABLE IF NOT EXISTS `api_orderstatus_sms_history` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `ORDER_ID` INT(11) NULL DEFAULT NULL,
  `USER_ID` INT(11) NULL DEFAULT NULL,
  `SITE_ID` CHAR(2) NOT NULL DEFAULT 's1',
  `STATUS_ID` CHAR(2) NULL DEFAULT NULL,
  `DATE_CREATE` DATETIME NULL DEFAULT NULL,
  `GATEWAY_ID` INT(2) NULL DEFAULT NULL,
  `SMS_ID` TEXT NULL,
  `SMS_TEXT` TEXT NULL,
  `SMS_ERROR` TEXT NULL,
  PRIMARY KEY (`ID`),
  INDEX `ORDER_ID` (`ORDER_ID`),
  INDEX `USER_ID` (`USER_ID`)
);
CREATE TABLE IF NOT EXISTS `api_orderstatus_sms_status` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `STATUS_ID` CHAR(2) NOT NULL,
  `SITE_ID` VARCHAR(255) NULL DEFAULT 's1',
  `ACTIVE` CHAR(1) NULL DEFAULT 'Y',
  `SORT` INT(11) NULL DEFAULT '500',
  `DESCRIPTION` LONGTEXT NULL,
  `NOTIFY` CHAR(1) NULL DEFAULT 'Y',
  `DATE_MODIFY` DATETIME NULL DEFAULT NULL,
  `MODIFIED_BY` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`)
);
