<div class="block">
	When rendering services we guarantee professional and ethical standards accepted in the professional community.
</div>
<div class="block doc">
	<i class="fa fa-file-text-o"></i><a href="#SITE_DIR#services/price.xls">Download price list for services</a><span class="file-type">[XLSX, 13,5 kB]</span>
</div>
<?$APPLICATION->IncludeComponent("bitrix:catalog.section", "banner", Array(
		"IBLOCK_TYPE" => "#IBLOCK_TYPE_BANNER_SERVICES#",
		"IBLOCK_ID" => "#IBLOCK_ID_BANNER_SERVICES#",
		"SECTION_ID" => $_REQUEST["SECTION_ID"],
		"SECTION_CODE" => "",
		"SECTION_USER_FIELDS" => "",
		"ELEMENT_SORT_FIELD" => "sort",
		"ELEMENT_SORT_ORDER" => "asc",
		"ELEMENT_SORT_FIELD2" => "name",
		"ELEMENT_SORT_ORDER2" => "asc",
		"FILTER_NAME" => "arrFilter",
		"INCLUDE_SUBSECTIONS" => "Y",
		"SHOW_ALL_WO_SECTION" => "Y",
		"PAGE_ELEMENT_COUNT" => "1000000",
		"LINE_ELEMENT_COUNT" => "1",
		"PROPERTY_CODE" => array(
			0 => "HREF",
			1 => "PREVIEW_PICTURE_DESCRIPTION",
		),
		"OFFERS_LIMIT" => "5",
		"ADD_PICT_PROP" => "-",
		"LABEL_PROP" => "-",
		"SECTION_URL" => "",
		"DETAIL_URL" => "",
		"SECTION_ID_VARIABLE" => "SECTION_ID",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "N",
		"AJAX_OPTION_HISTORY" => "N",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "36000000",
		"CACHE_GROUPS" => "Y",
		"SET_META_KEYWORDS" => "Y",
		"META_KEYWORDS" => "-",
		"SET_META_DESCRIPTION" => "Y",
		"META_DESCRIPTION" => "-",
		"BROWSER_TITLE" => "-",
		"ADD_SECTIONS_CHAIN" => "N",
		"DISPLAY_COMPARE" => "N",
		"SET_TITLE" => "N",
		"SET_STATUS_404" => "N",
		"CACHE_FILTER" => "Y",
		"PRICE_CODE" => "",
		"USE_PRICE_COUNT" => "N",
		"SHOW_PRICE_COUNT" => "1",
		"PRICE_VAT_INCLUDE" => "Y",
		"ACTION_VARIABLE" => "action",
		"PRODUCT_ID_VARIABLE" => "id",
		"USE_PRODUCT_QUANTITY" => "N",
		"ADD_PROPERTIES_TO_BASKET" => "Y",
		"PRODUCT_PROPS_VARIABLE" => "prop",
		"PARTIAL_PRODUCT_PROPERTIES" => "N",
		"PRODUCT_PROPERTIES" => "",
		"PAGER_TEMPLATE" => "",
		"DISPLAY_TOP_PAGER" => "N",
		"DISPLAY_BOTTOM_PAGER" => "N",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"PRODUCT_QUANTITY_VARIABLE" => "quantity",
		"TEMPLATE_THEME" => "blue",
		"MESS_BTN_BUY" => "",
		"MESS_BTN_ADD_TO_BASKET" => "",
		"MESS_BTN_SUBSCRIBE" => "",
		"MESS_BTN_DETAIL" => "",
		"MESS_NOT_AVAILABLE" => "",
		"SET_BROWSER_TITLE" => "Y",
		"BASKET_URL" => "/personal/basket.php",
		"PAGER_TITLE" => "",
		"AUTOPLAY" => (!empty($_SESSION["QUICK_THEME"][SITE_ID]["BANNER_AUTOPLAY"]) ? $_SESSION["QUICK_THEME"][SITE_ID]["BANNER_AUTOPLAY"] : COption::GetOptionString("businesscard", "QUICK_THEME_BANNER_AUTOPLAY", "content-slider-with-controls-bottom-autoplay", SITE_ID)),
	),
	false
);?>
<div class="block">
	<blockquote class="margin-clear">
		<p>Who is afraid of failure, that limits their activities.</p>	
		<footer><cite title="Генри Форд">Henry Ford</cite></footer>
	</blockquote>
</div>