<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Главная");
$MSFichi = RSMonopoly::getSettings('MSFichi', 'Y');
$MSCatalog = RSMonopoly::getSettings('MSCatalog', 'Y');
$MSService = RSMonopoly::getSettings('MSService', 'Y');
$MSAboutAndReviews = RSMonopoly::getSettings('MSAboutAndReviews', 'Y');
$MSNews = RSMonopoly::getSettings('MSNews', 'Y');
$MSPartners = RSMonopoly::getSettings('MSPartners', 'Y');
$MSGallery = RSMonopoly::getSettings('MSGallery', 'Y');
$MSSmallBanner = RSMonopoly::getSettings('MSSmallBanners', 'N');
$sidebarPos = RSMonopoly::getSettings('sidebarPos', 'pos1');
$headType = RSMonopoly::getSettings('headType', 'type1');
?>

<?$APPLICATION->IncludeComponent(
	"bitrix:news.list",
	"features2",
	array(
		"IBLOCK_TYPE" => "services",
		"IBLOCK_ID" => "#FEATURES_IBLOCK_ID#",
		"NEWS_COUNT" => "3",
		"SORT_BY1" => "ACTIVE_FROM",
		"SORT_ORDER1" => "DESC",
		"SORT_BY2" => "SORT",
		"SORT_ORDER2" => "ASC",
		"FILTER_NAME" => "",
		"FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"PROPERTY_CODE" => array(
			0 => "LINK",
			1 => "BLANK",
			2 => "",
		),
		"CHECK_DATES" => "Y",
		"DETAIL_URL" => "",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"AJAX_OPTION_HISTORY" => "N",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "36000000",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"PREVIEW_TRUNCATE_LEN" => "",
		"ACTIVE_DATE_FORMAT" => "d.m.Y",
		"SET_TITLE" => "N",
		"SET_BROWSER_TITLE" => "N",
		"SET_META_KEYWORDS" => "N",
		"SET_META_DESCRIPTION" => "N",
		"SET_STATUS_404" => "N",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"ADD_SECTIONS_CHAIN" => "N",
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"PARENT_SECTION" => "",
		"PARENT_SECTION_CODE" => "",
		"INCLUDE_SUBSECTIONS" => "Y",
		"RSMONOPOLY_USE_OWL" => "Y",
		"RSMONOPOLY_SHOW_BLOCK_NAME" => "N",
		"RSMONOPOLY_LINK" => "LINK",
		"RSMONOPOLY_BLANK" => "BLANK",
		"RSMONOPOLY_CHANGE_SPEED" => "2000",
		"RSMONOPOLY_CHANGE_DELAY" => "80000000",
		"PAGER_TEMPLATE" => "monopoly2",
		"DISPLAY_TOP_PAGER" => "N",
		"DISPLAY_BOTTOM_PAGER" => "N",
		"PAGER_TITLE" => "Новости",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"RSMONOPOLY_COLS_IN_ROW" => "4",
		"RSMONOPOLY_BLOCK_NAME_IS_LINK" => "N",
		"RSMONOPOLY_OWL_CHANGE_SPEED" => "500",
		"RSMONOPOLY_OWL_CHANGE_DELAY" => "8000",
		"RSMONOPOLY_OWL_PHONE" => "1",
		"RSMONOPOLY_OWL_TABLET" => "2",
		"RSMONOPOLY_OWL_PC" => "3",
		"COMPONENT_TEMPLATE" => "features2",
		"SET_LAST_MODIFIED" => "N",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"SHOW_404" => "N",
		"MESSAGE_404" => ""
	),
	false,
	array(
		"ACTIVE_COMPONENT" => $MSFichi
	)
);?>
<?$APPLICATION->IncludeComponent(
	"bitrix:news.list",
	"small_banners",
	array(
		"IBLOCK_TYPE" => "services",
		"IBLOCK_ID" => "#SMALL_BANNERS_IBLOCK_ID#",
		"NEWS_COUNT" => "3",
		"SORT_BY1" => "ACTIVE_FROM",
		"SORT_ORDER1" => "DESC",
		"SORT_BY2" => "SORT",
		"SORT_ORDER2" => "ASC",
		"FILTER_NAME" => "",
		"FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"PROPERTY_CODE" => array(
			0 => "BLANK",
			1 => "LINK",
			2 => "TEXT",
			3 => "",
		),
		"CHECK_DATES" => "Y",
		"DETAIL_URL" => "",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"AJAX_OPTION_HISTORY" => "N",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "36000000",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"PREVIEW_TRUNCATE_LEN" => "",
		"ACTIVE_DATE_FORMAT" => "d.m.Y",
		"SET_TITLE" => "N",
		"SET_BROWSER_TITLE" => "N",
		"SET_META_KEYWORDS" => "N",
		"SET_META_DESCRIPTION" => "N",
		"SET_STATUS_404" => "N",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"ADD_SECTIONS_CHAIN" => "N",
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"PARENT_SECTION" => "",
		"PARENT_SECTION_CODE" => "",
		"INCLUDE_SUBSECTIONS" => "Y",
		"RSMONOPOLY_USE_OWL" => "Y",
		"RSMONOPOLY_SHOW_BLOCK_NAME" => "N",
		"RSMONOPOLY_LINK" => "LINK",
		"RSMONOPOLY_BLANK" => "BLANK",
		"RSMONOPOLY_CHANGE_SPEED" => "2000",
		"RSMONOPOLY_CHANGE_DELAY" => "80000000",
		"PAGER_TEMPLATE" => "monopoly2",
		"DISPLAY_TOP_PAGER" => "N",
		"DISPLAY_BOTTOM_PAGER" => "N",
		"PAGER_TITLE" => "",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"RSMONOPOLY_COLS_IN_ROW" => "4",
		"RSMONOPOLY_BLOCK_NAME_IS_LINK" => "N",
		"RSMONOPOLY_OWL_CHANGE_SPEED" => "1500",
		"RSMONOPOLY_OWL_CHANGE_DELAY" => "800000",
		"RSMONOPOLY_OWL_PHONE" => "1",
		"RSMONOPOLY_OWL_TABLET" => "2",
		"RSMONOPOLY_OWL_PC" => "3",
		"COMPONENT_TEMPLATE" => "small_banners",
		"SET_LAST_MODIFIED" => "N",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"SHOW_404" => "N",
		"MESSAGE_404" => "",
		"RSMONOPOLY_NAME" => "TEXT",
		"RSMONOPOLY_TEXT" => "TEXT"
	),
	false,
	array(
		"ACTIVE_COMPONENT" => $MSSmallBanner
	)
);?>
<?$APPLICATION->IncludeComponent(
	"bitrix:catalog.section.list",
	"gallery",
	array(
		"COMPONENT_TEMPLATE" => "gallery",
		"IBLOCK_TYPE" => "catalog",
		"IBLOCK_ID" => "#CATALOG_IBLOCK_ID#",
		"SECTION_ID" => "",
		"SECTION_CODE" => "",
		"COUNT_ELEMENTS" => "Y",
		"TOP_DEPTH" => "1",
		"SECTION_FIELDS" => array(
			0 => "",
			1 => "",
		),
		"SECTION_USER_FIELDS" => array(
			0 => "",
			1 => "",
		),
		"VIEW_MODE" => "LINE",
		"SHOW_PARENT_NAME" => "Y",
		"SECTION_URL" => "",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "36000000",
		"CACHE_GROUPS" => "Y",
		"ADD_SECTIONS_CHAIN" => "Y",
		"RSMONOPOLY_USE_OWL" => "N",
		"RSMONOPOLY_CHANGE_SPEED" => "2000",
		"RSMONOPOLY_CHANGE_DELAY" => "8000",
		"RSMONOPOLY_COLS_IN_ROW" => "3",
		"RSMONOPOLY_BLOCK_NAME" => "Каталог",
		"RSMONOPOLY_BLOCK_LINK" => "",
		"RSMONOPOLY_SHOW_BLOCK_NAME" => "Y",
		"RSMONOPOLY_BLOCK_NAME_IS_LINK" => "N",
		"RSMONOPOLY_SHOW_DESC_IN_SECTION" => "Y"
	),
	false,
	array(
		"ACTIVE_COMPONENT" => $MSCatalog
	)
);?><?$APPLICATION->IncludeComponent(
	"bitrix:news.list",
	"services",
	array(
		"COMPONENT_TEMPLATE" => "services",
		"IBLOCK_TYPE" => "services",
		"IBLOCK_ID" => "#SERVICES_IBLOCK_ID#",
		"NEWS_COUNT" => "10",
		"SORT_BY1" => "ACTIVE_FROM",
		"SORT_ORDER1" => "DESC",
		"SORT_BY2" => "SORT",
		"SORT_ORDER2" => "ASC",
		"FILTER_NAME" => "",
		"FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"CHECK_DATES" => "Y",
		"DETAIL_URL" => "",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"AJAX_OPTION_HISTORY" => "N",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "36000000",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"PREVIEW_TRUNCATE_LEN" => "",
		"ACTIVE_DATE_FORMAT" => "d.m.Y",
		"SET_TITLE" => "N",
		"SET_BROWSER_TITLE" => "N",
		"SET_META_KEYWORDS" => "N",
		"SET_META_DESCRIPTION" => "N",
		"SET_STATUS_404" => "N",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"ADD_SECTIONS_CHAIN" => "N",
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"PARENT_SECTION" => "",
		"PARENT_SECTION_CODE" => "",
		"INCLUDE_SUBSECTIONS" => "Y",
		"DISPLAY_DATE" => "Y",
		"DISPLAY_NAME" => "Y",
		"DISPLAY_PICTURE" => "Y",
		"DISPLAY_PREVIEW_TEXT" => "Y",
		"PAGER_TEMPLATE" => "monopoly2",
		"DISPLAY_TOP_PAGER" => "N",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"PAGER_TITLE" => "Новости",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"RSMONOPOLY_USE_OWL" => "Y",
		"RSMONOPOLY_CHANGE_SPEED" => "2000",
		"RSMONOPOLY_CHANGE_DELAY" => "100",
		"RSMONOPOLY_COLS_IN_ROW" => "3",
		"RSMONOPOLY_SHOW_BLOCK_NAME" => "Y",
		"AJAX_OPTION_ADDITIONAL" => "",
		"RSMONOPOLY_OWL_CHANGE_SPEED" => "500",
		"RSMONOPOLY_OWL_CHANGE_DELAY" => "8000",
		"RSMONOPOLY_OWL_PHONE" => "2",
		"RSMONOPOLY_OWL_TABLET" => "3",
		"RSMONOPOLY_OWL_PC" => "4",
		"RSMONOPOLY_BLOCK_NAME_IS_LINK" => "N"
	),
	false,
	array(
		"ACTIVE_COMPONENT" => $MSService
	)
);?>
<?if($MSAboutAndReviews=='Y'):?>
<?$APPLICATION->IncludeComponent(
	"bitrix:main.include",
	".default",
	array(
		"AREA_FILE_SHOW" => "file",
		"PATH" => "#SITE_DIR#include_areas/mainabout.php",
		"EDIT_TEMPLATE" => ""
	),
	false
);?>
<?endif;?>

<?$APPLICATION->IncludeComponent(
	"bitrix:news.line",
	"mshop",
	array(
		"IBLOCK_TYPE" => "company",
		"IBLOCKS" => Array(
			0 => "#NEWS_IBLOCK_ID#",
			1 => "#STOCKS_IBLOCK_ID#"
		),
		"NEWS_COUNT" => "20",
		"FIELD_CODE" => array(
			0 => "PREVIEW_TEXT",
			1 => "",
		),
		"SORT_BY1" => "ACTIVE_FROM",
		"SORT_ORDER1" => "DESC",
		"SORT_BY2" => "SORT",
		"SORT_ORDER2" => "ASC",
		"ACTIVE_DATE_FORMAT" => "d.m.Y",
		"RSMONOPOLY_USE_OWL" => "Y",
		"RSMONOPOLY_SHOW_BLOCK_NAME" => "Y",
		"RSMONOPOLY_CHANGE_SPEED" => "2000",
		"RSMONOPOLY_CHANGE_DELAY" => "8000",
		"RSMONOPOLY_SHOW_DATE" => "Y",
		"RSMONOPOLY_COLS_IN_ROW" => "3",
		"AJAX_OPTION_ADDITIONAL" => "",
		"RSMONOPOLY_OWL_CHANGE_SPEED" => "500",
		"RSMONOPOLY_OWL_CHANGE_DELAY" => "80000000",
		"RSMONOPOLY_OWL_PHONE" => "1",
		"RSMONOPOLY_OWL_TABLET" => "2",
		"RSMONOPOLY_OWL_PC" => "3",
		"RSMONOPOLY_BLOCK_NAME_IS_LINK" => "N",
		"RS_BLOCK_NAME" => "Новости сайта",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "300",
		"CACHE_GROUPS" => "Y"
	),
	false,
	array(
		"ACTIVE_COMPONENT" => $MSNews
	)
);?>

<?$APPLICATION->IncludeComponent(
	"bitrix:news.list",
	"partners",
	array(
		"COMPONENT_TEMPLATE" => "partners",
		"IBLOCK_TYPE" => "services",
		"IBLOCK_ID" => "#PARTNERS_IBLOCK_ID#",
		"NEWS_COUNT" => "10",
		"SORT_BY1" => "ACTIVE_FROM",
		"SORT_ORDER1" => "DESC",
		"SORT_BY2" => "SORT",
		"SORT_ORDER2" => "ASC",
		"FILTER_NAME" => "",
		"FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"CHECK_DATES" => "Y",
		"DETAIL_URL" => "",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"AJAX_OPTION_HISTORY" => "N",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "36000000",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"PREVIEW_TRUNCATE_LEN" => "",
		"ACTIVE_DATE_FORMAT" => "d.m.Y",
		"SET_TITLE" => "N",
		"SET_BROWSER_TITLE" => "N",
		"SET_META_KEYWORDS" => "N",
		"SET_META_DESCRIPTION" => "N",
		"SET_STATUS_404" => "N",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"ADD_SECTIONS_CHAIN" => "N",
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"PARENT_SECTION" => "",
		"PARENT_SECTION_CODE" => "",
		"INCLUDE_SUBSECTIONS" => "Y",
		"DISPLAY_DATE" => "Y",
		"DISPLAY_NAME" => "Y",
		"DISPLAY_PICTURE" => "Y",
		"DISPLAY_PREVIEW_TEXT" => "Y",
		"PAGER_TEMPLATE" => ".default",
		"DISPLAY_TOP_PAGER" => "N",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"PAGER_TITLE" => "Новости",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"RSMONOPOLY_USE_OWL" => "Y",
		"RSMONOPOLY_CHANGE_SPEED" => "2000",
		"RSMONOPOLY_CHANGE_DELAY" => "8000",
		"RSMONOPOLY_COLS_IN_ROW" => "3",
		"AJAX_OPTION_ADDITIONAL" => "",
		"RSMONOPOLY_SHOW_BLOCK_NAME" => "Y",
		"RSMONOPOLY_OWL_CHANGE_SPEED" => "500",
		"RSMONOPOLY_OWL_CHANGE_DELAY" => "8000",
		"RSMONOPOLY_OWL_PHONE" => "2",
		"RSMONOPOLY_OWL_TABLET" => "4",
		"RSMONOPOLY_OWL_PC" => "6",
		"RSMONOPOLY_BLOCK_NAME_IS_LINK" => "N"
	),
	false,
	array(
		"ACTIVE_COMPONENT" => $MSPartners
	)
);?><?$APPLICATION->IncludeComponent(
	"bitrix:news.list",
	"gallery",
	array(
		"COMPONENT_TEMPLATE" => "gallery",
		"IBLOCK_TYPE" => "services",
		"IBLOCK_ID" => "#PROJECTPHOTOGALLERY_IBLOCK_ID#",
		"NEWS_COUNT" => "10",
		"SORT_BY1" => "ACTIVE_FROM",
		"SORT_ORDER1" => "DESC",
		"SORT_BY2" => "SORT",
		"SORT_ORDER2" => "ASC",
		"FILTER_NAME" => "",
		"FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"CHECK_DATES" => "Y",
		"DETAIL_URL" => "",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"AJAX_OPTION_HISTORY" => "N",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "36000000",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"PREVIEW_TRUNCATE_LEN" => "",
		"ACTIVE_DATE_FORMAT" => "d.m.Y",
		"SET_TITLE" => "N",
		"SET_BROWSER_TITLE" => "N",
		"SET_META_KEYWORDS" => "N",
		"SET_META_DESCRIPTION" => "N",
		"SET_STATUS_404" => "N",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"ADD_SECTIONS_CHAIN" => "N",
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"PARENT_SECTION" => "",
		"PARENT_SECTION_CODE" => "",
		"INCLUDE_SUBSECTIONS" => "Y",
		"DISPLAY_DATE" => "Y",
		"DISPLAY_NAME" => "Y",
		"DISPLAY_PICTURE" => "Y",
		"DISPLAY_PREVIEW_TEXT" => "Y",
		"PAGER_TEMPLATE" => "monopoly2",
		"DISPLAY_TOP_PAGER" => "N",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"PAGER_TITLE" => "Новости",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"RSMONOPOLY_SHOW_BLOCK_NAME" => "Y",
		"RSMONOPOLY_USE_OWL" => "Y",
		"RSMONOPOLY_CHANGE_SPEED" => "2000",
		"RSMONOPOLY_CHANGE_DELAY" => "8000",
		"RSMONOPOLY_COLS_IN_ROW" => "3",
		"AJAX_OPTION_ADDITIONAL" => "",
		"RSMONOPOLY_OWL_CHANGE_SPEED" => "500",
		"RSMONOPOLY_OWL_CHANGE_DELAY" => "8000",
		"RSMONOPOLY_OWL_PHONE" => "1",
		"RSMONOPOLY_OWL_TABLET" => "2",
		"RSMONOPOLY_OWL_PC" => "4",
		"RSMONOPOLY_BLOCK_NAME_IS_LINK" => "N"
	),
	false,
	array(
		"ACTIVE_COMPONENT" => $MSGallery
	)
);?><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>