<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Акции");
$APPLICATION->AddChainItem("Акции", SITE_DIR."campaign/");?>
<?$APPLICATION->IncludeComponent(
	"bitrix:news.list", 
	"campaign", 
	array(
		"IBLOCK_TYPE" => "campaign",
		"IBLOCK_ID" => BEJET_SELLER_CAMPAIGN,
		"NEWS_COUNT" => "20",
		"SORT_BY1" => "ACTIVE_FROM",
		"SORT_ORDER1" => "DESC",
		"SORT_BY2" => "SORT",
		"SORT_ORDER2" => "ASC",
		"FILTER_NAME" => "",
		"FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"CHECK_DATES" => "Y",
		"DETAIL_URL" => "",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"AJAX_OPTION_HISTORY" => "N",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "36000000",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"PREVIEW_TRUNCATE_LEN" => "",
		"ACTIVE_DATE_FORMAT" => "d.m.Y",
		"SET_TITLE" => "N",
		"SET_BROWSER_TITLE" => "N",
		"SET_META_KEYWORDS" => "Y",
		"SET_META_DESCRIPTION" => "Y",
		"SET_STATUS_404" => "N",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"ADD_SECTIONS_CHAIN" => "N",
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"PARENT_SECTION" => "",
		"PARENT_SECTION_CODE" => "",
		"INCLUDE_SUBSECTIONS" => "Y",
		"PAGER_TEMPLATE" => ".default",
		"DISPLAY_TOP_PAGER" => "N",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"PAGER_TITLE" => "Новости",
		"PAGER_SHOW_ALWAYS" => "Y",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "Y",
		"DISPLAY_DATE" => "Y",
		"DISPLAY_NAME" => "Y",
		"DISPLAY_PICTURE" => "Y",
		"DISPLAY_PREVIEW_TEXT" => "Y",
		"AJAX_OPTION_ADDITIONAL" => "",
		"COMPONENT_TEMPLATE" => "campaign",
		"SET_LAST_MODIFIED" => "N",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"SHOW_404" => "N",
		"MESSAGE_404" => ""
	),
	false
);?>
<hr class="i-size-L">
<?$APPLICATION->IncludeComponent(
	"bitrix:catalog.viewed.products", 
	"bejetstore", 
	array(
		"IBLOCK_TYPE" => "catalog",
		"IBLOCK_ID" => BEJET_SELLER_CLOTHES,//"CATALOG_IBLOK_ID"
		"SHOW_FROM_SECTION" => "Y",
		"HIDE_NOT_AVAILABLE" => "N",
		"SHOW_DISCOUNT_PERCENT" => "Y",
		"PRODUCT_SUBSCRIPTION" => "N",
		"SHOW_NAME" => "Y",
		"SHOW_IMAGE" => "Y",
		"MESS_BTN_BUY" => "Купить",
		"MESS_BTN_DETAIL" => "Подробнее",
		"MESS_BTN_SUBSCRIBE" => "Подписаться",
		"PAGE_ELEMENT_COUNT" => "6",
		"LINE_ELEMENT_COUNT" => "6",
		"TEMPLATE_THEME" => "blue",
		"DETAIL_URL" => "",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "36000000",
		"CACHE_GROUPS" => "Y",
		"SHOW_OLD_PRICE" => "Y",
		"PRICE_CODE" => array(
			0 => "BASE",
		),
		"SHOW_PRICE_COUNT" => "1",
		"PRICE_VAT_INCLUDE" => "N",
		"CONVERT_CURRENCY" => "N",
		"BASKET_URL" => "/personal/cart/",
		"ACTION_VARIABLE" => "action",
		"PRODUCT_ID_VARIABLE" => "id",
		"ADD_PROPERTIES_TO_BASKET" => "Y",
		"PRODUCT_PROPS_VARIABLE" => "prop",
		"PARTIAL_PRODUCT_PROPERTIES" => "N",
		"USE_PRODUCT_QUANTITY" => "N",
		"SHOW_PRODUCTS_2" => "Y",
		"SECTION_ID" => $GLOBALS["CATALOG_CURRENT_SECTION_ID"],
		"SECTION_CODE" => "",
		"SECTION_ELEMENT_ID" => $GLOBALS["CATALOG_CURRENT_ELEMENT_ID"],
		"SECTION_ELEMENT_CODE" => "",
		"DEPTH" => "2",
		"PRODUCT_QUANTITY_VARIABLE" => $arParams["CONVERPRODUCT_QUANTITY_VARIABLET_CURRENCY"],
		"PROPERTY_CODE_2" => array(
			0 => "MORE_PHOTO",
			1 => "BLOG_COMMENTS_CNT",
			2 => "FORUM_MESSAGE_CNT",
			3 => "vote_count",
			4 => "rating",
			5 => "RECOMMEND",
			6 => "vote_sum",
			7 => "FORUM_TOPIC_ID",
			8 => "MINIMUM_PRICE",
			9 => "",
		),
		"CART_PROPERTIES_2" => array(
			0 => "",
			1 => "",
		),
		"ADDITIONAL_PICT_PROP_2" => "MORE_PHOTO",
		"LABEL_PROP_2" => "NEWPRODUCT",
		"PROPERTY_CODE_3" => array(
			0 => "ARTNUMBER",
			1 => "COLOR_REF",
			2 => "SIZES_SHOES",
			3 => "SIZES_CLOTHES",
			4 => "MORE_PHOTO",
			5 => "",
		),
		"CART_PROPERTIES_3" => array(
			0 => "COLOR_REF",
			1 => "SIZES_SHOES",
			2 => "SIZES_CLOTHES",
			3 => "",
		),
		"ADDITIONAL_PICT_PROP_3" => "MORE_PHOTO",
		"OFFER_TREE_PROPS_3" => array(
			0 => "COLOR_REF",
			1 => "SIZES_SHOES",
			2 => "SIZES_CLOTHES",
		),
		"COMPONENT_TEMPLATE" => "bejetstore"
	),
	false
);?>

<?$APPLICATION->IncludeComponent(
	"bitrix:catalog.bigdata.products", 
	"bejet.v2", 
	array(
		"RCM_TYPE" => "personal",
		"ID" => "",
		"IBLOCK_TYPE" => "catalog",
		"IBLOCK_ID" => $arParams['IBLOCK_ID'],
		"HIDE_NOT_AVAILABLE" => "N",
		"SHOW_DISCOUNT_PERCENT" => "Y",
		"PRODUCT_SUBSCRIPTION" => "N",
		"SHOW_NAME" => "Y",
		"SHOW_IMAGE" => "Y",
		"MESS_BTN_BUY" => "Купить",
		"MESS_BTN_DETAIL" => "Подробнее",
		"MESS_BTN_SUBSCRIBE" => "Подписаться",
		"PAGE_ELEMENT_COUNT" => "4",
		"LINE_ELEMENT_COUNT" => "3",
		"TEMPLATE_THEME" => "blue",
		"DETAIL_URL" => "/catalog/#SECTION_CODE#/#ELEMENT_CODE#/",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "36000000",
		"CACHE_GROUPS" => "N",
		"SHOW_OLD_PRICE" => "Y",
		"PRICE_CODE" => array(
			0 => "BASE",
		),
		"SHOW_PRICE_COUNT" => "1",
		"PRICE_VAT_INCLUDE" => "Y",
		"CONVERT_CURRENCY" => "Y",
		"BASKET_URL" => "/personal/cart/",
		"ACTION_VARIABLE" => "action",
		"PRODUCT_ID_VARIABLE" => "id",
		"ADD_PROPERTIES_TO_BASKET" => "Y",
		"PRODUCT_PROPS_VARIABLE" => "prop",
		"PARTIAL_PRODUCT_PROPERTIES" => "N",
		"USE_PRODUCT_QUANTITY" => "Y",
		"SHOW_PRODUCTS_2" => "Y",
		"CURRENCY_ID" => "RUB",
		"PROPERTY_CODE_2" => array(
			0 => "",
			1 => "",
		),
		"CART_PROPERTIES_2" => array(
			0 => "",
			1 => "",
		),
		"ADDITIONAL_PICT_PROP_2" => "MORE_PHOTO",
		"LABEL_PROP_2" => "NEWPRODUCT",
		"PROPERTY_CODE_3" => array(
			0 => "SIZES_CLOTHES",
			1 => "MORE_PHOTO",
			2 => "",
		),
		"CART_PROPERTIES_3" => array(
			0 => "COLOR_REF",
			1 => "SIZES_SHOES",
			2 => "SIZES_CLOTHES",
			3 => "",
		),
		"ADDITIONAL_PICT_PROP_3" => "MORE_PHOTO",
		"OFFER_TREE_PROPS_3" => array(
			0 => "COLOR_REF",
			1 => "SIZES_SHOES",
			2 => "SIZES_CLOTHES",
		),
		"PRODUCT_QUANTITY_VARIABLE" => "quantity",
		"COMPONENT_TEMPLATE" => "bejet.v2",
		"SHOW_FROM_SECTION" => "N",
		"SECTION_ID" => "",
		"SECTION_CODE" => "",
		"SECTION_ELEMENT_ID" => "",
		"SECTION_ELEMENT_CODE" => "",
		"DEPTH" => "",
		"SHOW_PRODUCTS_#BEJET_SELLER_CLOTHES#" => "Y",
		"PROPERTY_CODE_#BEJET_SELLER_CLOTHES#" => array(
			0 => "",
			1 => "",
		),
		"CART_PROPERTIES_#BEJET_SELLER_CLOTHES#" => array(
			0 => "",
			1 => "",
		),
		"ADDITIONAL_PICT_PROP_#BEJET_SELLER_CLOTHES#" => "MORE_PHOTO",
		"LABEL_PROP_#BEJET_SELLER_CLOTHES#" => "-",
		"PROPERTY_CODE_#BEJET_SELLER_OFFERS_CLOTHES#" => array(
			0 => "CML2_LINK",
			1 => "ARTNUMBER",
			2 => "COLOR_REF",
			3 => "SIZES_SHOES",
			4 => "SIZES_CLOTHES",
			5 => "MORE_PHOTO",
			6 => "",
		),
		"CART_PROPERTIES_#BEJET_SELLER_OFFERS_CLOTHES#" => array(
			0 => "COLOR_REF",
			1 => "SIZES_SHOES",
			2 => "SIZES_CLOTHES",
			3 => "",
		),
		"ADDITIONAL_PICT_PROP_#BEJET_SELLER_OFFERS_CLOTHES#" => "MORE_PHOTO",
		"OFFER_TREE_PROPS_#BEJET_SELLER_OFFERS_CLOTHES#" => array(
			0 => "COLOR_REF",
			1 => "SIZES_SHOES",
			2 => "SIZES_CLOTHES",
		)
	),
	false
);?>

<?$APPLICATION->IncludeComponent(
	"bitrix:catalog.viewed.products", 
	"bejetstore", 
	array(
		"IBLOCK_TYPE" => "catalog",
		"IBLOCK_ID" => BEJET_SELLER_CLOTHES,
		"SHOW_FROM_SECTION" => "Y",
		"HIDE_NOT_AVAILABLE" => "N",
		"SHOW_DISCOUNT_PERCENT" => "Y",
		"PRODUCT_SUBSCRIPTION" => "N",
		"SHOW_NAME" => "Y",
		"SHOW_IMAGE" => "Y",
		"MESS_BTN_BUY" => "Купить",
		"MESS_BTN_DETAIL" => "Подробнее",
		"MESS_BTN_SUBSCRIBE" => "Подписаться",
		"PAGE_ELEMENT_COUNT" => "6",
		"LINE_ELEMENT_COUNT" => "6",
		"TEMPLATE_THEME" => "blue",
		"DETAIL_URL" => "",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "36000000",
		"CACHE_GROUPS" => "Y",
		"SHOW_OLD_PRICE" => "Y",
		"PRICE_CODE" => array(
			0 => "BASE",
		),
		"SHOW_PRICE_COUNT" => "1",
		"PRICE_VAT_INCLUDE" => "N",
		"CONVERT_CURRENCY" => "N",
		"BASKET_URL" => "/personal/cart/",
		"ACTION_VARIABLE" => "action",
		"PRODUCT_ID_VARIABLE" => "id",
		"ADD_PROPERTIES_TO_BASKET" => "Y",
		"PRODUCT_PROPS_VARIABLE" => "prop",
		"PARTIAL_PRODUCT_PROPERTIES" => "N",
		"USE_PRODUCT_QUANTITY" => "N",
		"SHOW_PRODUCTS_2" => "Y",
		"SECTION_ID" => $GLOBALS["CATALOG_CURRENT_SECTION_ID"],
		"SECTION_CODE" => "",
		"SECTION_ELEMENT_ID" => $GLOBALS["CATALOG_CURRENT_ELEMENT_ID"],
		"SECTION_ELEMENT_CODE" => "",
		"DEPTH" => "2",
		"PRODUCT_QUANTITY_VARIABLE" => $arParams["CONVERPRODUCT_QUANTITY_VARIABLET_CURRENCY"],
		"PROPERTY_CODE_2" => array(
			0 => "MORE_PHOTO",
			1 => "BLOG_COMMENTS_CNT",
			2 => "FORUM_MESSAGE_CNT",
			3 => "vote_count",
			4 => "rating",
			5 => "RECOMMEND",
			6 => "vote_sum",
			7 => "FORUM_TOPIC_ID",
			8 => "MINIMUM_PRICE",
			9 => "",
		),
		"CART_PROPERTIES_2" => array(
			0 => "",
			1 => "",
		),
		"ADDITIONAL_PICT_PROP_2" => "MORE_PHOTO",
		"LABEL_PROP_2" => "NEWPRODUCT",
		"PROPERTY_CODE_3" => array(
			0 => "ARTNUMBER",
			1 => "COLOR_REF",
			2 => "SIZES_SHOES",
			3 => "SIZES_CLOTHES",
			4 => "MORE_PHOTO",
			5 => "",
		),
		"CART_PROPERTIES_3" => array(
			0 => "COLOR_REF",
			1 => "SIZES_SHOES",
			2 => "SIZES_CLOTHES",
			3 => "",
		),
		"ADDITIONAL_PICT_PROP_3" => "MORE_PHOTO",
		"OFFER_TREE_PROPS_3" => array(
			0 => "COLOR_REF",
			1 => "SIZES_SHOES",
			2 => "SIZES_CLOTHES",
		),
		"COMPONENT_TEMPLATE" => "bejetstore",
		"SHOW_PRODUCTS_#BEJET_SELLER_CLOTHES#" => "Y",
		"PROPERTY_CODE_#BEJET_SELLER_CLOTHES#" => array(
			0 => "TITLE",
			1 => "KEYWORDS",
			2 => "META_DESCRIPTION",
			3 => "BRAND_REF",
			4 => "NEWPRODUCT",
			5 => "SALELEADER",
			6 => "SALE_RECOMMEND",
			7 => "SPECIALOFFER",
			8 => "ARTNUMBER",
			9 => "MANUFACTURER",
			10 => "MATERIAL",
			11 => "COLOR",
			12 => "BRAND",
			13 => "BLOG_POST_ID",
			14 => "MORE_PHOTO",
			15 => "BLOG_COMMENTS_CNT",
			16 => "FORUM_MESSAGE_CNT",
			17 => "vote_count",
			18 => "rating",
			19 => "RECOMMEND",
			20 => "vote_sum",
			21 => "FORUM_TOPIC_ID",
			22 => "MINIMUM_PRICE",
			23 => "MAXIMUM_PRICE",
			24 => "CHARACTERISTICS",
			25 => "",
		),
		"CART_PROPERTIES_#BEJET_SELLER_CLOTHES#" => array(
			0 => "BRAND_REF",
			1 => "NEWPRODUCT",
			2 => "SALELEADER",
			3 => "SALE_RECOMMEND",
			4 => "SPECIALOFFER",
			5 => "BRAND",
			6 => "RECOMMEND",
			7 => "",
		),
		"ADDITIONAL_PICT_PROP_#BEJET_SELLER_CLOTHES#" => "MORE_PHOTO",
		"LABEL_PROP_#BEJET_SELLER_CLOTHES#" => "-",
		"PROPERTY_CODE_#BEJET_SELLER_OFFERS_CLOTHES#" => array(
			0 => "",
			1 => "",
		),
		"CART_PROPERTIES_#BEJET_SELLER_OFFERS_CLOTHES#" => array(
			0 => "",
			1 => "",
		),
		"ADDITIONAL_PICT_PROP_#BEJET_SELLER_OFFERS_CLOTHES#" => "MORE_PHOTO",
		"OFFER_TREE_PROPS_#BEJET_SELLER_OFFERS_CLOTHES#" => array(
		)
	),
	false
);?>

<hr class="i-size-L">
<?include($_SERVER["DOCUMENT_ROOT"].SITE_DIR."small_banners.php");?>
<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>