<?php
/**
 * Created by http://bitcall.ru
 * User: Kurdikov P.S.
 * Date: 17.05.2014
 */


namespace Bitcall\Client\Models\Requests;


class TextTaskCall extends TaskCall {
    private $text;

    function __construct($text, $phone, $id = null)
    {
        parent::__construct($phone, $id); // TODO: Change the autogenerated stub
        $this->text = $text;
    }


    /**
     * @param string $text
     */
    public function setText($text)
    {
        $this->text = $text;
    }

    /**
     * @return string
     */
    public function getText()
    {
        return $this->text;
    }



} 